# GENERATED 1:1 from monitoring-v4.0.yaml — resource 'Event'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-monitoring-event
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-monitoring-event-oas/event.yaml
  resourceGroup: monitoring.nutanix.krateo.io
  resource:
    kind: Event
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $limit
    - $orderby
    - $page
    - $select
    verbsDescription:
    - action: findby
      method: GET
      path: /monitoring/v4.0/serviceability/events
    - action: get
      method: GET
      path: /monitoring/v4.0/serviceability/events/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
