# GENERATED 1:1 from nke-v1.yaml — resource 'AddNode'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-nke-addnode
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-nke-addnode-oas/addnode.yaml
  resourceGroup: nke.nutanix.krateo.io
  resource:
    kind: AddNode
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /karbon/v1-alpha.1/k8s/clusters/{name}/node-pools/{node-pool-name}/add-nodes
      requestFieldMapping:
      - inPath: name
        inCustomResource: spec.name
      - inPath: node-pool-name
        inCustomResource: spec.node-pool-name
