# GENERATED 1:1 from nke-v1.yaml — resource 'Addon'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-nke-addon
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-nke-addon-oas/addon.yaml
  resourceGroup: nke.nutanix.krateo.io
  resource:
    kind: Addon
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - force
    - name
    verbsDescription:
    - action: findby
      method: GET
      path: /karbon/v1-beta.1/k8s/clusters/{uuid}/addons
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
    - action: create
      method: POST
      path: /karbon/v1-beta.1/k8s/clusters/{uuid}/addons
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
    - action: get
      method: GET
      path: /karbon/v1-beta.1/k8s/clusters/{uuid}/addons/{name}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
      - inPath: name
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /karbon/v1-beta.1/k8s/clusters/{uuid}/addons/{name}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
      - inPath: name
        inCustomResource: status.extId
