# GENERATED 1:1 from nke-v1.yaml — resource 'Agent'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-nke-agent
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-nke-agent-oas/agent.yaml
  resourceGroup: nke.nutanix.krateo.io
  resource:
    kind: Agent
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /karbon/v1-beta.1/k8s/clusters/{uuid}/agent
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
