# GENERATED 1:1 from nke-v1.yaml — resource 'AvailableUpdate'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-nke-availableupdate
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-nke-availableupdate-oas/availableupdate.yaml
  resourceGroup: nke.nutanix.krateo.io
  resource:
    kind: AvailableUpdate
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /karbon/v1-beta.1/k8s/clusters/available-updates
