# GENERATED 1:1 from nke-v1.yaml — resource 'CertificateRotation'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-nke-certificaterotation
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-nke-certificaterotation-oas/certificaterotation.yaml
  resourceGroup: nke.nutanix.krateo.io
  resource:
    kind: CertificateRotation
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - skip-health-checks
    verbsDescription:
    - action: create
      method: POST
      path: /karbon/v1-alpha.1/airgap/certificate-rotation
