# GENERATED 1:1 from nke-v1.yaml — resource 'Health'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-nke-health
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-nke-health-oas/health.yaml
  resourceGroup: nke.nutanix.krateo.io
  resource:
    kind: Health
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /karbon/v1/k8s/clusters/{name}/health
      requestFieldMapping:
      - inPath: name
        inCustomResource: spec.name
