# GENERATED 1:1 from nke-v1.yaml — resource 'K8sCertificateRotation'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-nke-k8scertificaterotation
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-nke-k8scertificaterotation-oas/k8scertificaterotation.yaml
  resourceGroup: nke.nutanix.krateo.io
  resource:
    kind: K8sCertificateRotation
    identifiers:
    - name
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - skip-health-checks
    verbsDescription:
    - action: create
      method: POST
      path: /karbon/v1-alpha.1/k8s/clusters/certificate-rotation
