# GENERATED 1:1 from nke-v1.yaml — resource 'K8sCluster'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-nke-k8scluster
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-nke-k8scluster-oas/k8scluster.yaml
  resourceGroup: nke.nutanix.krateo.io
  resource:
    kind: K8sCluster
    identifiers:
    - name
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - name
    - skip-prechecks
    verbsDescription:
    - action: create
      method: POST
      path: /karbon/v1/k8s/clusters
    - action: get
      method: GET
      path: /karbon/v1/k8s/clusters/{name}
      requestFieldMapping:
      - inPath: name
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /karbon/v1/k8s/clusters/{name}
      requestFieldMapping:
      - inPath: name
        inCustomResource: status.extId
