# GENERATED 1:1 from nke-v1.yaml — resource 'K8sNodePool'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-nke-k8snodepool
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-nke-k8snodepool-oas/k8snodepool.yaml
  resourceGroup: nke.nutanix.krateo.io
  resource:
    kind: K8sNodePool
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - node-pool-name
    verbsDescription:
    - action: get
      method: GET
      path: /karbon/v1-beta.1/k8s/clusters/{name}/node-pools/{node-pool-name}
      requestFieldMapping:
      - inPath: name
        inCustomResource: spec.name
      - inPath: node-pool-name
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /karbon/v1-beta.1/k8s/clusters/{name}/node-pools/{node-pool-name}
      requestFieldMapping:
      - inPath: name
        inCustomResource: spec.name
      - inPath: node-pool-name
        inCustomResource: status.extId
