# GENERATED 1:1 from nke-v1.yaml — resource 'K8sUpgrade'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-nke-k8supgrade
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-nke-k8supgrade-oas/k8supgrade.yaml
  resourceGroup: nke.nutanix.krateo.io
  resource:
    kind: K8sUpgrade
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /k8s/cluster/{uuid}/k8s_upgrade
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
    - action: create
      method: POST
      path: /k8s/cluster/{uuid}/k8s_upgrade
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
