# GENERATED 1:1 from nke-v1.yaml — resource 'LogForwarding'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-nke-logforwarding
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-nke-logforwarding-oas/logforwarding.yaml
  resourceGroup: nke.nutanix.krateo.io
  resource:
    kind: LogForwarding
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /karbon/v1-alpha.1/k8s/clusters/{name}/log-forwarding
      requestFieldMapping:
      - inPath: name
        inCustomResource: spec.name
