# GENERATED 1:1 from nke-v1.yaml — resource 'NodePool'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-nke-nodepool
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-nke-nodepool-oas/nodepool.yaml
  resourceGroup: nke.nutanix.krateo.io
  resource:
    kind: NodePool
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /karbon/v1-alpha.1/k8s/clusters/{name}/node-pools
      requestFieldMapping:
      - inPath: name
        inCustomResource: spec.name
