# GENERATED 1:1 from nke-v1.yaml — resource 'Registry'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-nke-registry
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-nke-registry-oas/registry.yaml
  resourceGroup: nke.nutanix.krateo.io
  resource:
    kind: Registry
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - registry_name
    verbsDescription:
    - action: findby
      method: GET
      path: /karbon/v1-alpha.1/k8s/clusters/{cluster_name}/registries
      requestFieldMapping:
      - inPath: cluster_name
        inCustomResource: spec.cluster_name
    - action: create
      method: POST
      path: /karbon/v1-alpha.1/k8s/clusters/{cluster_name}/registries
      requestFieldMapping:
      - inPath: cluster_name
        inCustomResource: spec.cluster_name
    - action: delete
      method: DELETE
      path: /karbon/v1-alpha.1/k8s/clusters/{cluster_name}/registries/{registry_name}
      requestFieldMapping:
      - inPath: cluster_name
        inCustomResource: spec.cluster_name
      - inPath: registry_name
        inCustomResource: status.extId
