# GENERATED 1:1 from nke-v1.yaml — resource 'Registry2'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-nke-registry2
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-nke-registry2-oas/registry2.yaml
  resourceGroup: nke.nutanix.krateo.io
  resource:
    kind: Registry2
    identifiers:
    - name
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - name
    verbsDescription:
    - action: findby
      method: GET
      path: /karbon/v1-alpha.1/registries
    - action: create
      method: POST
      path: /karbon/v1-alpha.1/registries
    - action: get
      method: GET
      path: /karbon/v1-alpha.1/registries/{name}
      requestFieldMapping:
      - inPath: name
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /karbon/v1-alpha.1/registries/{name}
      requestFieldMapping:
      - inPath: name
        inCustomResource: status.extId
