# GENERATED 1:1 from nke-v1.yaml — resource 'RemoveNode'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-nke-removenode
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-nke-removenode-oas/removenode.yaml
  resourceGroup: nke.nutanix.krateo.io
  resource:
    kind: RemoveNode
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - skip-prechecks
    verbsDescription:
    - action: create
      method: POST
      path: /karbon/v1-alpha.1/k8s/clusters/{name}/node-pools/{node-pool-name}/remove-nodes
      requestFieldMapping:
      - inPath: name
        inCustomResource: spec.name
      - inPath: node-pool-name
        inCustomResource: spec.node-pool-name
