# GENERATED 1:1 from nke-v1.yaml — resource 'UpdateLabel'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-nke-updatelabel
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-nke-updatelabel-oas/updatelabel.yaml
  resourceGroup: nke.nutanix.krateo.io
  resource:
    kind: UpdateLabel
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /karbon/v1-alpha.1/k8s/clusters/{name}/node-pools/{node-pool-name}/update-labels
      requestFieldMapping:
      - inPath: name
        inCustomResource: spec.name
      - inPath: node-pool-name
        inCustomResource: spec.node-pool-name
