# GENERATED 1:1 from nke-v1.yaml — resource 'Version2'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-nke-version2
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-nke-version2-oas/version2.yaml
  resourceGroup: nke.nutanix.krateo.io
  resource:
    kind: Version2
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /karbon/v1-alpha.1/version
