# GENERATED 1:1 from microseg-v4.0.yaml — resource 'AddressGroup'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-microseg-addressgroup
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-microseg-addressgroup-oas/addressgroup.yaml
  resourceGroup: microseg.nutanix.krateo.io
  resource:
    kind: AddressGroup
    identifiers:
    - name
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $limit
    - $orderby
    - $page
    - $select
    verbsDescription:
    - action: findby
      method: GET
      path: /microseg/v4.0/config/address-groups
    - action: create
      method: POST
      path: /microseg/v4.0/config/address-groups
    - action: get
      method: GET
      path: /microseg/v4.0/config/address-groups/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /microseg/v4.0/config/address-groups/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /microseg/v4.0/config/address-groups/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
