# GENERATED 1:1 from microseg-v4.0.yaml — resource 'CategoryMapping'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-microseg-categorymapping
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-microseg-categorymapping-oas/categorymapping.yaml
  resourceGroup: microseg.nutanix.krateo.io
  resource:
    kind: CategoryMapping
    identifiers:
    - name
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $limit
    - $orderby
    - $page
    - $select
    verbsDescription:
    - action: findby
      method: GET
      path: /microseg/v4.0/config/category-mappings
    - action: create
      method: POST
      path: /microseg/v4.0/config/category-mappings
    - action: get
      method: GET
      path: /microseg/v4.0/config/category-mappings/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /microseg/v4.0/config/category-mappings/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /microseg/v4.0/config/category-mappings/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
