# GENERATED 1:1 from microseg-v4.0.yaml — resource 'DirectoryServerConfig'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-microseg-directoryserverconfig
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-microseg-directoryserverconfig-oas/directoryserverconfig.yaml
  resourceGroup: microseg.nutanix.krateo.io
  resource:
    kind: DirectoryServerConfig
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $select
    verbsDescription:
    - action: findby
      method: GET
      path: /microseg/v4.0/config/directory-server-configs
    - action: create
      method: POST
      path: /microseg/v4.0/config/directory-server-configs
    - action: get
      method: GET
      path: /microseg/v4.0/config/directory-server-configs/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /microseg/v4.0/config/directory-server-configs/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /microseg/v4.0/config/directory-server-configs/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
