# GENERATED 1:1 from microseg-v4.0.yaml — resource 'Policy'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-microseg-policy
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-microseg-policy-oas/policy.yaml
  resourceGroup: microseg.nutanix.krateo.io
  resource:
    kind: Policy
    identifiers:
    - name
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $limit
    - $orderby
    - $page
    - $select
    verbsDescription:
    - action: findby
      method: GET
      path: /microseg/v4.0/config/policies
    - action: create
      method: POST
      path: /microseg/v4.0/config/policies
    - action: get
      method: GET
      path: /microseg/v4.0/config/policies/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /microseg/v4.0/config/policies/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /microseg/v4.0/config/policies/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
