# GENERATED 1:1 from opsmgmt-v4.0.yaml — resource 'ContentFile'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-opsmgmt-contentfile
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-opsmgmt-contentfile-oas/contentfile.yaml
  resourceGroup: opsmgmt.nutanix.krateo.io
  resource:
    kind: ContentFile
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /opsmgmt/v4.0/content/reports/{reportExtId}/file
      requestFieldMapping:
      - inPath: reportExtId
        inCustomResource: spec.reportExtId
