# GENERATED 1:1 from opsmgmt-v4.0.yaml — resource 'File'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-opsmgmt-file
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-opsmgmt-file-oas/file.yaml
  resourceGroup: opsmgmt.nutanix.krateo.io
  resource:
    kind: File
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /opsmgmt/v4.0/content/report-artifacts/{reportArtifactExtId}/file
      requestFieldMapping:
      - inPath: reportArtifactExtId
        inCustomResource: spec.reportArtifactExtId
