# GENERATED 1:1 from opsmgmt-v4.0.yaml — resource 'GlobalReportSetting'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-opsmgmt-globalreportsetting
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-opsmgmt-globalreportsetting-oas/globalreportsetting.yaml
  resourceGroup: opsmgmt.nutanix.krateo.io
  resource:
    kind: GlobalReportSetting
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /opsmgmt/v4.0/config/user/{userExtId}/global-report-setting
      requestFieldMapping:
      - inPath: userExtId
        inCustomResource: spec.userExtId
