# GENERATED 1:1 from opsmgmt-v4.0.yaml — resource 'Report'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-opsmgmt-report
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-opsmgmt-report-oas/report.yaml
  resourceGroup: opsmgmt.nutanix.krateo.io
  resource:
    kind: Report
    identifiers:
    - name
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $limit
    - $orderby
    - $page
    - $select
    verbsDescription:
    - action: findby
      method: GET
      path: /opsmgmt/v4.0/config/reports
    - action: create
      method: POST
      path: /opsmgmt/v4.0/config/reports
    - action: get
      method: GET
      path: /opsmgmt/v4.0/config/reports/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /opsmgmt/v4.0/config/reports/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
