# GENERATED 1:1 from nc2-v1.yaml — resource 'AuditTrail'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-nc2-audittrail
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-nc2-audittrail-oas/audittrail.yaml
  resourceGroup: nc2.nutanix.krateo.io
  resource:
    kind: AuditTrail
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /organizations/{id}/audit-trails
      requestFieldMapping:
      - inPath: id
        inCustomResource: spec.id
