# GENERATED 1:1 from nc2-v1.yaml — resource 'CloudAccount'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-nc2-cloudaccount
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-nc2-cloudaccount-oas/cloudaccount.yaml
  resourceGroup: nc2.nutanix.krateo.io
  resource:
    kind: CloudAccount
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - id
    verbsDescription:
    - action: get
      method: GET
      path: /cloud-accounts/{id}
      requestFieldMapping:
      - inPath: id
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /cloud-accounts/{id}
      requestFieldMapping:
      - inPath: id
        inCustomResource: status.extId
