# GENERATED 1:1 from nc2-v1.yaml — resource 'CloudResource'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-nc2-cloudresource
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-nc2-cloudresource-oas/cloudresource.yaml
  resourceGroup: nc2.nutanix.krateo.io
  resource:
    kind: CloudResource
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /clusters/{cluster_id}/cloud-resources
      requestFieldMapping:
      - inPath: cluster_id
        inCustomResource: spec.cluster_id
