# GENERATED 1:1 from nc2-v1.yaml — resource 'Notification'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-nc2-notification
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-nc2-notification-oas/notification.yaml
  resourceGroup: nc2.nutanix.krateo.io
  resource:
    kind: Notification
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - acknowledged
    - cluster_id
    - from
    - id
    - order
    - order_by
    - organization_id
    - severity
    - to
    verbsDescription:
    - action: findby
      method: GET
      path: /notifications
    - action: update
      method: PUT
      path: /notifications/{id}
      requestFieldMapping:
      - inPath: id
        inCustomResource: status.extId
