# GENERATED 1:1 from nc2-v1.yaml — resource 'Region'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-nc2-region
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-nc2-region-oas/region.yaml
  resourceGroup: nc2.nutanix.krateo.io
  resource:
    kind: Region
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - cloud_account_id
    verbsDescription:
    - action: findby
      method: GET
      path: /cloud-accounts/{cloud_account_id}/regions
      requestFieldMapping:
      - inPath: cloud_account_id
        inCustomResource: spec.cloud_account_id
    - action: create
      method: POST
      path: /cloud-accounts/{cloud_account_id}/regions
      requestFieldMapping:
      - inPath: cloud_account_id
        inCustomResource: spec.cloud_account_id
