# GENERATED 1:1 from nc2-v1.yaml — resource 'RemoteStorageProfile'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-nc2-remotestorageprofile
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-nc2-remotestorageprofile-oas/remotestorageprofile.yaml
  resourceGroup: nc2.nutanix.krateo.io
  resource:
    kind: RemoteStorageProfile
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - host_type
    - tag
    verbsDescription:
    - action: findby
      method: GET
      path: /remote-storage-profiles
