# GENERATED 1:1 from nc2-v1.yaml — resource 'ScaleOutFgw'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-nc2-scaleoutfgw
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-nc2-scaleoutfgw-oas/scaleoutfgw.yaml
  resourceGroup: nc2.nutanix.krateo.io
  resource:
    kind: ScaleOutFgw
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /clusters/{id}/scale-out-fgw
      requestFieldMapping:
      - inPath: id
        inCustomResource: spec.id
