# GENERATED 1:1 from nc2-v1.yaml — resource 'SshKey'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-nc2-sshkey
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-nc2-sshkey-oas/sshkey.yaml
  resourceGroup: nc2.nutanix.krateo.io
  resource:
    kind: SshKey
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /cloud-accounts/{cloud_account_id}/regions/{region_id}/ssh-keys
      requestFieldMapping:
      - inPath: cloud_account_id
        inCustomResource: spec.cloud_account_id
      - inPath: region_id
        inCustomResource: spec.region_id
