# GENERATED 1:1 from nc2-v1.yaml — resource 'Terminate'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-nc2-terminate
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-nc2-terminate-oas/terminate.yaml
  resourceGroup: nc2.nutanix.krateo.io
  resource:
    kind: Terminate
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /clusters/{id}/terminate
      requestFieldMapping:
      - inPath: id
        inCustomResource: spec.id
