# GENERATED 1:1 from nc2-v1.yaml — resource 'UpdateCredential'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-nc2-updatecredential
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-nc2-updatecredential-oas/updatecredential.yaml
  resourceGroup: nc2.nutanix.krateo.io
  resource:
    kind: UpdateCredential
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - cloud_account_id
    verbsDescription:
    - action: create
      method: POST
      path: /cloud-accounts/{id}/update-credentials
      requestFieldMapping:
      - inPath: id
        inCustomResource: spec.id
