# GENERATED 1:1 from nc2-v1.yaml — resource 'UpdateResourceTag'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-nc2-updateresourcetag
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-nc2-updateresourcetag-oas/updateresourcetag.yaml
  resourceGroup: nc2.nutanix.krateo.io
  resource:
    kind: UpdateResourceTag
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /clusters/{id}/update-resource-tags
      requestFieldMapping:
      - inPath: id
        inCustomResource: spec.id
