openapi: 3.0.1
info:
  description: "**Nutanix Database Service** (NDB) is a database as a service (DBaaS) that automates and simplifies database\
    \ administration, brings one-click simplicity and invisible operations to database provisioning and life-cycle management.\
    \ NDB enables database administrators to provision, clone, and refresh the databases at any point in time. NDB allows\
    \ administrators to define standards for their database provisioning needs with end-state driven functionality that includes\
    \ High Availability (HA) database deployments. NDB automates and simplifies the operations such as provisioning of databases\
    \ and copy data management. \n\n\n# Notes\n\nWhile making Nutanix API requests to the NDB services by using the default\
    \ self-signed certificates, the request needs to be configured to ignore SSL certificate verification requests. For example,\
    \ in case of a cURL, use _- - insecure_ flag to ensure that the SSL certificate used to encrypt the request should not\
    \ be verified."
  title: Nutanix NDB
  version: '0.9'
servers:
- url: /era/v0.9
security:
- era_token: []
- era_auth: []
paths:
  /alerts:
    get:
      operationId: getAllAlerts
      parameters:
      - description: The time zone (e.g. 'America/New_York', 'UTC') to convert the timestamps in the response to the client's
          local time zone.
        in: header
        name: client_tz
        schema:
          type: string
      - description: Includes the resolved alerts in the response.
        in: query
        name: resolved
        schema:
          type: string
      - description: Look-back time interval in minutes for fetching the alerts.
        in: query
        name: timeInterval
        schema:
          type: string
      - description: Returns a concise response.
        in: query
        name: summary
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ERAAlertDTO'
                type: array
          description: Operation completed.
      summary: Get a list of all alerts
      tags:
      - Alerts
      x-codeSamples:
      - lang: cURL
        source: "curl --request GET \\\n    --url :///era/v0.9/alerts \\\n    --header 'Authorization: Basic <basic_auth_token>'\
          \ \\\n     "
      - lang: Wget
        source: "wget --quiet \\\n    --method GET \\\n    --header 'Authorization: Basic <basic_auth_token>' \\\n      \\\
          \n    --output-document \\\n    - :///era/v0.9/alerts"
      - lang: Python
        source: "import http.client\n\nconn = http.client.HTTPSConnection(\"\")\n\nheaders = {\n    \"Authorization\": \"\
          Basic <basic_auth_token>\"\n}\n \nconn.request(\"GET\",\"/era/v0.9/alerts\", headers=headers)\n\nres = conn.getresponse()\n\
          data = res.read()\n\nprint(data.decode(\"utf-8\"))"
      - lang: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl\
          \ := \":///era/v0.9/alerts\"\n\t \n\treq, err := http.NewRequest(\"GET\", url, nil)\n\tif err != nil {\n\t\tfmt.Println(\"\
          Error creating request:\", err)\n\t\treturn\n\t}\n\n        req.Header.Add(\"Authorization\", \"Basic <basic_auth_token>\"\
          )\n    \n\tres, err := http.DefaultClient.Do(req)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating request:\"\
          , err)\n\t\treturn\n\t}\n\n\tdefer res.Body.Close()\n\tbody, err := io.ReadAll(res.Body)\n\tif err != nil {\n\t\t\
          fmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n\tfmt.Println(res)\n\tfmt.Println(string(body))\n\
          \n}"
      - lang: Java
        source: "AsyncHttpClient client = new DefaultAsyncHttpClient();\nclient.prepare(\"GET\", \":///era/v0.9/alerts\")\n\
          \  .setHeader(\"Authorization\", \"Basic <basic_auth_token>\")\n  .execute()\n  .toCompletableFuture()\n  .thenAccept(System.out::println)\n\
          \  .join();\n\nclient.close();"
      - lang: JavaScript
        source: "const url = ':///era/v0.9/alerts';\nconst options = {\n  method: 'GET',\n  headers: {'Authorization': 'Basic\
          \ <basic_auth_token>'} \n};\n\ntry {\n  const response = await fetch(url, options);\n  const data = await response.json();\n\
          \  console.log(data);\n} catch (error) {\n  console.error(error);\n}"
    put:
      description: Resolves/acknowledges one or more alerts.
      operationId: updateAlertsBulk
      requestBody:
        content:
          '*/*':
            schema:
              items:
                $ref: '#/components/schemas/UpdateAlertModel'
              type: array
        required: false
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ERAAlertDTO'
                type: array
          description: Operation completed.
      summary: Resolve/acknowledge alerts
      tags:
      - Alerts
      x-codeSamples:
      - lang: cURL
        source: "curl --request PUT \\\n    --url :///era/v0.9/alerts \\\n    --header 'Authorization: Basic <basic_auth_token>'\
          \ \\\n     "
      - lang: Wget
        source: "wget --quiet \\\n    --method PUT \\\n    --header 'Authorization: Basic <basic_auth_token>' \\\n      \\\
          \n    --output-document \\\n    - :///era/v0.9/alerts"
      - lang: Python
        source: "import http.client\n\nconn = http.client.HTTPSConnection(\"\")\n\nheaders = {\n    \"Authorization\": \"\
          Basic <basic_auth_token>\"\n}\n\npayload =  \"\"\"{}\"\"\"\n\nconn.request(\"PUT\",\"/era/v0.9/alerts\", payload,\
          \ headers)\n\nres = conn.getresponse()\ndata = res.read()\n\nprint(data.decode(\"utf-8\"))"
      - lang: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl\
          \ := \":///era/v0.9/alerts\"\n\t \n\treq, err := http.NewRequest(\"PUT\", url, nil)\n\tif err != nil {\n\t\tfmt.Println(\"\
          Error creating request:\", err)\n\t\treturn\n\t}\n\n        req.Header.Add(\"Authorization\", \"Basic <basic_auth_token>\"\
          )\n    \n\tres, err := http.DefaultClient.Do(req)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating request:\"\
          , err)\n\t\treturn\n\t}\n\n\tdefer res.Body.Close()\n\tbody, err := io.ReadAll(res.Body)\n\tif err != nil {\n\t\t\
          fmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n\tfmt.Println(res)\n\tfmt.Println(string(body))\n\
          \n}"
      - lang: Java
        source: "AsyncHttpClient client = new DefaultAsyncHttpClient();\nclient.prepare(\"PUT\", \":///era/v0.9/alerts\")\n\
          \  .setHeader(\"Authorization\", \"Basic <basic_auth_token>\")\n  .execute()\n  .toCompletableFuture()\n  .thenAccept(System.out::println)\n\
          \  .join();\n\nclient.close();"
      - lang: JavaScript
        source: "const url = ':///era/v0.9/alerts';\nconst options = {\n  method: 'PUT',\n  headers: {'Authorization': 'Basic\
          \ <basic_auth_token>'} \n};\n\ntry {\n  const response = await fetch(url, options);\n  const data = await response.json();\n\
          \  console.log(data);\n} catch (error) {\n  console.error(error);\n}"
  /alerts/{alertId}:
    get:
      operationId: getAlertById
      parameters:
      - description: The time zone (e.g. 'America/New_York', 'UTC') to convert the timestamps in the response to the client's
          local time zone.
        in: header
        name: client_tz
        schema:
          type: string
      - in: path
        name: alertId
        required: true
        schema:
          format: uuid
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERAAlertDTO'
          description: Operation completed.
      summary: Get an alert by alert ID
      tags:
      - Alerts
      x-codeSamples:
      - lang: cURL
        source: "curl --request GET \\\n    --url :///era/v0.9/alerts/{alertId} \\\n    --header 'Authorization: Basic <basic_auth_token>'\
          \ \\\n     "
      - lang: Wget
        source: "wget --quiet \\\n    --method GET \\\n    --header 'Authorization: Basic <basic_auth_token>' \\\n      \\\
          \n    --output-document \\\n    - :///era/v0.9/alerts/{alertId}"
      - lang: Python
        source: "import http.client\n\nconn = http.client.HTTPSConnection(\"\")\n\nheaders = {\n    \"Authorization\": \"\
          Basic <basic_auth_token>\"\n}\n \nconn.request(\"GET\",\"/era/v0.9/alerts/{alertId}\", headers=headers)\n\nres =\
          \ conn.getresponse()\ndata = res.read()\n\nprint(data.decode(\"utf-8\"))"
      - lang: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl\
          \ := \":///era/v0.9/alerts/{alertId}\"\n\t \n\treq, err := http.NewRequest(\"GET\", url, nil)\n\tif err != nil {\n\
          \t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n        req.Header.Add(\"Authorization\",\
          \ \"Basic <basic_auth_token>\")\n    \n\tres, err := http.DefaultClient.Do(req)\n\tif err != nil {\n\t\tfmt.Println(\"\
          Error creating request:\", err)\n\t\treturn\n\t}\n\n\tdefer res.Body.Close()\n\tbody, err := io.ReadAll(res.Body)\n\
          \tif err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n\tfmt.Println(res)\n\t\
          fmt.Println(string(body))\n\n}"
      - lang: Java
        source: "AsyncHttpClient client = new DefaultAsyncHttpClient();\nclient.prepare(\"GET\", \":///era/v0.9/alerts/{alertId}\"\
          )\n  .setHeader(\"Authorization\", \"Basic <basic_auth_token>\")\n  .execute()\n  .toCompletableFuture()\n  .thenAccept(System.out::println)\n\
          \  .join();\n\nclient.close();"
      - lang: JavaScript
        source: "const url = ':///era/v0.9/alerts/{alertId}';\nconst options = {\n  method: 'GET',\n  headers: {'Authorization':\
          \ 'Basic <basic_auth_token>'} \n};\n\ntry {\n  const response = await fetch(url, options);\n  const data = await\
          \ response.json();\n  console.log(data);\n} catch (error) {\n  console.error(error);\n}"
    put:
      operationId: updateAlert
      parameters:
      - in: path
        name: alertId
        required: true
        schema:
          format: uuid
          type: string
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/UpdateAlertModel'
        required: false
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERAAlertDTO'
          description: Operation completed.
      summary: Update an Alert
      tags:
      - Alerts
      x-codeSamples:
      - lang: cURL
        source: "curl --request PUT \\\n    --url :///era/v0.9/alerts/{alertId} \\\n    --header 'Authorization: Basic <basic_auth_token>'\
          \ \\\n     "
      - lang: Wget
        source: "wget --quiet \\\n    --method PUT \\\n    --header 'Authorization: Basic <basic_auth_token>' \\\n      \\\
          \n    --output-document \\\n    - :///era/v0.9/alerts/{alertId}"
      - lang: Python
        source: "import http.client\n\nconn = http.client.HTTPSConnection(\"\")\n\nheaders = {\n    \"Authorization\": \"\
          Basic <basic_auth_token>\"\n}\n\npayload =  \"\"\"{}\"\"\"\n\nconn.request(\"PUT\",\"/era/v0.9/alerts/{alertId}\"\
          , payload, headers)\n\nres = conn.getresponse()\ndata = res.read()\n\nprint(data.decode(\"utf-8\"))"
      - lang: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl\
          \ := \":///era/v0.9/alerts/{alertId}\"\n\t \n\treq, err := http.NewRequest(\"PUT\", url, nil)\n\tif err != nil {\n\
          \t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n        req.Header.Add(\"Authorization\",\
          \ \"Basic <basic_auth_token>\")\n    \n\tres, err := http.DefaultClient.Do(req)\n\tif err != nil {\n\t\tfmt.Println(\"\
          Error creating request:\", err)\n\t\treturn\n\t}\n\n\tdefer res.Body.Close()\n\tbody, err := io.ReadAll(res.Body)\n\
          \tif err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n\tfmt.Println(res)\n\t\
          fmt.Println(string(body))\n\n}"
      - lang: Java
        source: "AsyncHttpClient client = new DefaultAsyncHttpClient();\nclient.prepare(\"PUT\", \":///era/v0.9/alerts/{alertId}\"\
          )\n  .setHeader(\"Authorization\", \"Basic <basic_auth_token>\")\n  .execute()\n  .toCompletableFuture()\n  .thenAccept(System.out::println)\n\
          \  .join();\n\nclient.close();"
      - lang: JavaScript
        source: "const url = ':///era/v0.9/alerts/{alertId}';\nconst options = {\n  method: 'PUT',\n  headers: {'Authorization':\
          \ 'Basic <basic_auth_token>'} \n};\n\ntry {\n  const response = await fetch(url, options);\n  const data = await\
          \ response.json();\n  console.log(data);\n} catch (error) {\n  console.error(error);\n}"
components:
  schemas:
    UpdateAlertModel:
      properties:
        acknowledged:
          type: boolean
        id:
          format: uuid
          type: string
        resetAcknowledged:
          type: boolean
        resetResolved:
          type: boolean
        resolved:
          type: boolean
      type: object
    ERAAlertDTO:
      properties:
        acknowledged:
          type: boolean
        dateAcknowledged:
          type: string
        dateCreated:
          type: string
        dateModified:
          type: string
        dateResolved:
          type: string
        entityId:
          format: uuid
          type: string
        entityName:
          type: string
        entityType:
          type: string
        id:
          format: uuid
          type: string
        message:
          type: string
        notified:
          type: boolean
        operationId:
          format: uuid
          type: string
        ownerId:
          format: uuid
          type: string
        policyId:
          format: uuid
          type: string
        resetAcknowledged:
          type: boolean
        resetResolved:
          type: boolean
        resolved:
          type: boolean
        severity:
          type: string
      type: object
  securitySchemes:
    era_auth:
      description: NDB username and password.
      scheme: basic
      type: http
    era_token:
      description: NDB API token.
      in: header
      name: Authorization
      type: apiKey
