openapi: 3.0.1
info:
  description: "**Nutanix Database Service** (NDB) is a database as a service (DBaaS) that automates and simplifies database\
    \ administration, brings one-click simplicity and invisible operations to database provisioning and life-cycle management.\
    \ NDB enables database administrators to provision, clone, and refresh the databases at any point in time. NDB allows\
    \ administrators to define standards for their database provisioning needs with end-state driven functionality that includes\
    \ High Availability (HA) database deployments. NDB automates and simplifies the operations such as provisioning of databases\
    \ and copy data management. \n\n\n# Notes\n\nWhile making Nutanix API requests to the NDB services by using the default\
    \ self-signed certificates, the request needs to be configured to ignore SSL certificate verification requests. For example,\
    \ in case of a cURL, use _- - insecure_ flag to ensure that the SSL certificate used to encrypt the request should not\
    \ be verified."
  title: Nutanix NDB
  version: '0.9'
servers:
- url: /era/v0.9
security:
- era_token: []
- era_auth: []
paths:
  /dbservers/enable-winrm-over-https:
    post:
      description: 'Migrates a batch of DBVMs from WinRM over HTTP to HTTPS. For brownfield VMs,

        requires explicit acknowledgment for listener configuration.


        **Note**: At least one of `dbservers` or `dbserverClusters` is required.'
      operationId: enableWinRMOverHttps
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ERAEnableWinRMOverHttpsTaskInfoDTO'
        description: Payload required to enable WinRM over HTTPS for a Database Server/Cluster.
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskInfoSummary'
          description: Operation completed.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad Request. - Invalid DBVM IDs - Batch size exceeds limit (>10) - Invalid port number
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized. - Missing authentication token - Invalid authentication token - Token expired
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Forbidden. - User doesn't have required permissions
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Not Found. - Certificate not found
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Server Error. - Deletion failed - System error
      summary: Enable WinRM over HTTPS for Database Servers and Clusters
      tags:
      - Database Servers
      x-codeSamples:
      - lang: cURL
        source: "curl --request POST \\\n    --url :///era/v0.9/dbservers/enable-winrm-over-https \\\n    --header 'Accept:\
          \ application/json' \\\n    --header 'Authorization: Basic <basic_auth_token>' \\\n    --header 'Content-Type: application/json'\
          \ \\\n    --data '{\n    \"dbserverClusters\": [\n        \"b4d15375-1097-4c96-a4c4-4cb5809b05bb\"\n    ],\n   \
          \ \"dbservers\": [\n        \"b4d15375-1097-4c96-a4c4-4cb5809b05bb\"\n    ],\n    \"winrmHttpsPort\": 0\n}'"
      - lang: Wget
        source: "wget --quiet \\\n    --method POST \\\n    --header 'Accept: application/json' \\\n    --header 'Authorization:\
          \ Basic <basic_auth_token>' \\\n    --header 'Content-Type: application/json' \\\n    --body-data '{\n    \"dbserverClusters\"\
          : [\n        \"b4d15375-1097-4c96-a4c4-4cb5809b05bb\"\n    ],\n    \"dbservers\": [\n        \"b4d15375-1097-4c96-a4c4-4cb5809b05bb\"\
          \n    ],\n    \"winrmHttpsPort\": 0\n}' \\\n    --output-document \\\n    - :///era/v0.9/dbservers/enable-winrm-over-https"
      - lang: Python
        source: "import http.client\n\nconn = http.client.HTTPSConnection(\"\")\n\nheaders = {\n    \"Accept\": \"application/json\"\
          ,\n    \"Authorization\": \"Basic <basic_auth_token>\",\n    \"Content-Type\": \"application/json\"\n}\n\npayload\
          \ =  \"\"\"{\n    \"dbserverClusters\": [\n        \"b4d15375-1097-4c96-a4c4-4cb5809b05bb\"\n    ],\n    \"dbservers\"\
          : [\n        \"b4d15375-1097-4c96-a4c4-4cb5809b05bb\"\n    ],\n    \"winrmHttpsPort\": 0\n}\"\"\"\n\nconn.request(\"\
          POST\",\"/era/v0.9/dbservers/enable-winrm-over-https\", payload, headers)\n\nres = conn.getresponse()\ndata = res.read()\n\
          \nprint(data.decode(\"utf-8\"))"
      - lang: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl\
          \ := \":///era/v0.9/dbservers/enable-winrm-over-https\"\n\t\n\tpayload :=  strings.NewReader(`{\"dbserverClusters\"\
          : [\"b4d15375-1097-4c96-a4c4-4cb5809b05bb\"], \"dbservers\": [\"b4d15375-1097-4c96-a4c4-4cb5809b05bb\"], \"winrmHttpsPort\"\
          : 0}`)\n\treq, err := http.NewRequest(\"POST\", url, payload)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating\
          \ request:\", err)\n\t\treturn\n\t}\n\n        req.Header.Add(\"Accept\", \"application/json\")\n        req.Header.Add(\"\
          Authorization\", \"Basic <basic_auth_token>\")\n        req.Header.Add(\"Content-Type\", \"application/json\")\n\
          \    \n\tres, err := http.DefaultClient.Do(req)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating request:\"\
          , err)\n\t\treturn\n\t}\n\n\tdefer res.Body.Close()\n\tbody, err := io.ReadAll(res.Body)\n\tif err != nil {\n\t\t\
          fmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n\tfmt.Println(res)\n\tfmt.Println(string(body))\n\
          \n}"
      - lang: Java
        source: "AsyncHttpClient client = new DefaultAsyncHttpClient();\nclient.prepare(\"POST\", \":///era/v0.9/dbservers/enable-winrm-over-https\"\
          )\n  .setHeader(\"Accept\", \"application/json\")\n  .setHeader(\"Authorization\", \"Basic <basic_auth_token>\"\
          )\n  .setHeader(\"Content-Type\", \"application/json\")\n  .setBody(\"{\\\"dbserverClusters\\\": [\\\"b4d15375-1097-4c96-a4c4-4cb5809b05bb\\\
          \"], \\\"dbservers\\\": [\\\"b4d15375-1097-4c96-a4c4-4cb5809b05bb\\\"], \\\"winrmHttpsPort\\\": 0}\")\n  .execute()\n\
          \  .toCompletableFuture()\n  .thenAccept(System.out::println)\n  .join();\n\nclient.close();"
      - lang: JavaScript
        source: "const url = ':///era/v0.9/dbservers/enable-winrm-over-https';\nconst options = {\n  method: 'POST',\n  headers:\
          \ {'Accept': 'application/json', 'Authorization': 'Basic <basic_auth_token>', 'Content-Type': 'application/json'},\n\
          \  body:  `{\"dbserverClusters\": [\"b4d15375-1097-4c96-a4c4-4cb5809b05bb\"], \"dbservers\": [\"b4d15375-1097-4c96-a4c4-4cb5809b05bb\"\
          ], \"winrmHttpsPort\": 0}`\n};\n\ntry {\n  const response = await fetch(url, options);\n  const data = await response.json();\n\
          \  console.log(data);\n} catch (error) {\n  console.error(error);\n}"
components:
  schemas:
    ERAPropertyValue:
      properties:
        description:
          type: string
        name:
          type: string
        ref_id:
          type: string
        secure:
          type: boolean
        value:
          type: string
      type: object
    ERAEnableWinRMOverHttpsTaskInfoDTO:
      properties:
        dbserverClusters:
          items:
            format: uuid
            type: string
          type: array
        dbservers:
          items:
            format: uuid
            type: string
          type: array
        winrmHttpsPort:
          format: int32
          type: integer
      type: object
    ERAEntity:
      properties:
        id:
          format: uuid
          type: string
        name:
          type: string
        properties:
          items:
            $ref: '#/components/schemas/ERAPropertyValue'
          type: array
        type:
          type: string
      type: object
    TaskInfoSummary:
      properties:
        associatedOperations:
          items:
            $ref: '#/components/schemas/TaskInfoSummary'
          type: array
        dbserverId:
          description: ID of the Database Server. associated with the NDB Operation.
          format: uuid
          type: string
        dependencyReport:
          $ref: '#/components/schemas/EraDependencyReport'
        entityId:
          description: ID of the entity associated with the NDB Operation. For example, Time Machine ID.
          format: uuid
          type: string
        entityName:
          description: Name of the entity associated with the NDB Operation. For example, Time Machine ID.
          type: string
        entityType:
          type: string
        message:
          type: string
        name:
          description: Name of the Operation created in NDB.
          type: string
        operationId:
          description: ID of the Operation entry created in NDB.
          format: uuid
          type: string
        status:
          description: Status of the NDB Operation.
          type: string
        workId:
          description: ID of the work entry created in NDB.
          format: uuid
          type: string
      type: object
    EraDependencyReport:
      properties:
        dependenciesSatisfied:
          type: boolean
        dependenciesVerified:
          type: boolean
        ipAddress:
          type: string
        missingConfigurations:
          items:
            $ref: '#/components/schemas/EraDependencyInfo'
          type: array
        missingDependencies:
          items:
            $ref: '#/components/schemas/EraDependencyInfo'
          type: array
      type: object
    ErrorResponse:
      properties:
        dependentEntities:
          items:
            $ref: '#/components/schemas/ERAEntity'
          type: array
        errorCode:
          type: string
        message:
          type: string
        reason:
          type: string
        remedy:
          type: string
      type: object
    EraDependencyInfo:
      properties:
        dependencyName:
          type: string
        description:
          type: string
        isPresent:
          type: boolean
        isSoftware:
          type: boolean
        name:
          type: string
        requiredAction:
          type: string
      type: object
  securitySchemes:
    era_auth:
      description: NDB username and password.
      scheme: basic
      type: http
    era_token:
      description: NDB API token.
      in: header
      name: Authorization
      type: apiKey
