openapi: 3.0.1
info:
  description: "**Nutanix Database Service** (NDB) is a database as a service (DBaaS) that automates and simplifies database\
    \ administration, brings one-click simplicity and invisible operations to database provisioning and life-cycle management.\
    \ NDB enables database administrators to provision, clone, and refresh the databases at any point in time. NDB allows\
    \ administrators to define standards for their database provisioning needs with end-state driven functionality that includes\
    \ High Availability (HA) database deployments. NDB automates and simplifies the operations such as provisioning of databases\
    \ and copy data management. \n\n\n# Notes\n\nWhile making Nutanix API requests to the NDB services by using the default\
    \ self-signed certificates, the request needs to be configured to ignore SSL certificate verification requests. For example,\
    \ in case of a cURL, use _- - insecure_ flag to ensure that the SSL certificate used to encrypt the request should not\
    \ be verified."
  title: Nutanix NDB
  version: '0.9'
servers:
- url: /era/v0.9
security:
- era_token: []
- era_auth: []
paths:
  /slas:
    get:
      operationId: getAllSLAs
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/EraSlaDTO'
                type: array
          description: Operation completed.
      summary: Get a list of SLAs
      tags:
      - SLAs
      x-codeSamples:
      - lang: cURL
        source: "curl --request GET \\\n    --url :///era/v0.9/slas \\\n    --header 'Authorization: Basic <basic_auth_token>'\
          \ \\\n     "
      - lang: Wget
        source: "wget --quiet \\\n    --method GET \\\n    --header 'Authorization: Basic <basic_auth_token>' \\\n      \\\
          \n    --output-document \\\n    - :///era/v0.9/slas"
      - lang: Python
        source: "import http.client\n\nconn = http.client.HTTPSConnection(\"\")\n\nheaders = {\n    \"Authorization\": \"\
          Basic <basic_auth_token>\"\n}\n \nconn.request(\"GET\",\"/era/v0.9/slas\", headers=headers)\n\nres = conn.getresponse()\n\
          data = res.read()\n\nprint(data.decode(\"utf-8\"))"
      - lang: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl\
          \ := \":///era/v0.9/slas\"\n\t \n\treq, err := http.NewRequest(\"GET\", url, nil)\n\tif err != nil {\n\t\tfmt.Println(\"\
          Error creating request:\", err)\n\t\treturn\n\t}\n\n        req.Header.Add(\"Authorization\", \"Basic <basic_auth_token>\"\
          )\n    \n\tres, err := http.DefaultClient.Do(req)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating request:\"\
          , err)\n\t\treturn\n\t}\n\n\tdefer res.Body.Close()\n\tbody, err := io.ReadAll(res.Body)\n\tif err != nil {\n\t\t\
          fmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n\tfmt.Println(res)\n\tfmt.Println(string(body))\n\
          \n}"
      - lang: Java
        source: "AsyncHttpClient client = new DefaultAsyncHttpClient();\nclient.prepare(\"GET\", \":///era/v0.9/slas\")\n\
          \  .setHeader(\"Authorization\", \"Basic <basic_auth_token>\")\n  .execute()\n  .toCompletableFuture()\n  .thenAccept(System.out::println)\n\
          \  .join();\n\nclient.close();"
      - lang: JavaScript
        source: "const url = ':///era/v0.9/slas';\nconst options = {\n  method: 'GET',\n  headers: {'Authorization': 'Basic\
          \ <basic_auth_token>'} \n};\n\ntry {\n  const response = await fetch(url, options);\n  const data = await response.json();\n\
          \  console.log(data);\n} catch (error) {\n  console.error(error);\n}"
    post:
      operationId: createSLA
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/EraSlaDTO'
        description: Payload required to create an SLA.
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EraSlaDTO'
          description: Operation completed.
      summary: Create SLA in NDB
      tags:
      - SLAs
      x-codeSamples:
      - lang: cURL
        source: "curl --request POST \\\n    --url :///era/v0.9/slas \\\n    --header 'Authorization: Basic <basic_auth_token>'\
          \ \\\n     "
      - lang: Wget
        source: "wget --quiet \\\n    --method POST \\\n    --header 'Authorization: Basic <basic_auth_token>' \\\n      \\\
          \n    --output-document \\\n    - :///era/v0.9/slas"
      - lang: Python
        source: "import http.client\n\nconn = http.client.HTTPSConnection(\"\")\n\nheaders = {\n    \"Authorization\": \"\
          Basic <basic_auth_token>\"\n}\n\npayload =  \"\"\"{}\"\"\"\n\nconn.request(\"POST\",\"/era/v0.9/slas\", payload,\
          \ headers)\n\nres = conn.getresponse()\ndata = res.read()\n\nprint(data.decode(\"utf-8\"))"
      - lang: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl\
          \ := \":///era/v0.9/slas\"\n\t \n\treq, err := http.NewRequest(\"POST\", url, nil)\n\tif err != nil {\n\t\tfmt.Println(\"\
          Error creating request:\", err)\n\t\treturn\n\t}\n\n        req.Header.Add(\"Authorization\", \"Basic <basic_auth_token>\"\
          )\n    \n\tres, err := http.DefaultClient.Do(req)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating request:\"\
          , err)\n\t\treturn\n\t}\n\n\tdefer res.Body.Close()\n\tbody, err := io.ReadAll(res.Body)\n\tif err != nil {\n\t\t\
          fmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n\tfmt.Println(res)\n\tfmt.Println(string(body))\n\
          \n}"
      - lang: Java
        source: "AsyncHttpClient client = new DefaultAsyncHttpClient();\nclient.prepare(\"POST\", \":///era/v0.9/slas\")\n\
          \  .setHeader(\"Authorization\", \"Basic <basic_auth_token>\")\n  .execute()\n  .toCompletableFuture()\n  .thenAccept(System.out::println)\n\
          \  .join();\n\nclient.close();"
      - lang: JavaScript
        source: "const url = ':///era/v0.9/slas';\nconst options = {\n  method: 'POST',\n  headers: {'Authorization': 'Basic\
          \ <basic_auth_token>'} \n};\n\ntry {\n  const response = await fetch(url, options);\n  const data = await response.json();\n\
          \  console.log(data);\n} catch (error) {\n  console.error(error);\n}"
  /slas/{sla_id}:
    delete:
      operationId: deleteSLATemplate
      parameters:
      - in: path
        name: sla_id
        required: true
        schema:
          format: uuid
          type: string
      responses: {}
      summary: Delete SLA
      tags:
      - SLAs
      x-codeSamples:
      - lang: cURL
        source: "curl --request DELETE \\\n    --url :///era/v0.9/slas/{sla_id} \\\n    --header 'Authorization: Basic <basic_auth_token>'\
          \ \\\n     "
      - lang: Wget
        source: "wget --quiet \\\n    --method DELETE \\\n    --header 'Authorization: Basic <basic_auth_token>' \\\n    \
          \  \\\n    --output-document \\\n    - :///era/v0.9/slas/{sla_id}"
      - lang: Python
        source: "import http.client\n\nconn = http.client.HTTPSConnection(\"\")\n\nheaders = {\n    \"Authorization\": \"\
          Basic <basic_auth_token>\"\n}\n \nconn.request(\"DELETE\",\"/era/v0.9/slas/{sla_id}\", headers=headers)\n\nres =\
          \ conn.getresponse()\ndata = res.read()\n\nprint(data.decode(\"utf-8\"))"
      - lang: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl\
          \ := \":///era/v0.9/slas/{sla_id}\"\n\t \n\treq, err := http.NewRequest(\"DELETE\", url, nil)\n\tif err != nil {\n\
          \t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n        req.Header.Add(\"Authorization\",\
          \ \"Basic <basic_auth_token>\")\n    \n\tres, err := http.DefaultClient.Do(req)\n\tif err != nil {\n\t\tfmt.Println(\"\
          Error creating request:\", err)\n\t\treturn\n\t}\n\n\tdefer res.Body.Close()\n\tbody, err := io.ReadAll(res.Body)\n\
          \tif err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n\tfmt.Println(res)\n\t\
          fmt.Println(string(body))\n\n}"
      - lang: Java
        source: "AsyncHttpClient client = new DefaultAsyncHttpClient();\nclient.prepare(\"DELETE\", \":///era/v0.9/slas/{sla_id}\"\
          )\n  .setHeader(\"Authorization\", \"Basic <basic_auth_token>\")\n  .execute()\n  .toCompletableFuture()\n  .thenAccept(System.out::println)\n\
          \  .join();\n\nclient.close();"
      - lang: JavaScript
        source: "const url = ':///era/v0.9/slas/{sla_id}';\nconst options = {\n  method: 'DELETE',\n  headers: {'Authorization':\
          \ 'Basic <basic_auth_token>'} \n};\n\ntry {\n  const response = await fetch(url, options);\n  const data = await\
          \ response.json();\n  console.log(data);\n} catch (error) {\n  console.error(error);\n}"
    get:
      operationId: getSLA
      parameters:
      - in: path
        name: sla_id
        required: true
        schema:
          format: uuid
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EraSlaDTO'
          description: Operation completed.
      summary: Get an SLA
      tags:
      - SLAs
      x-codeSamples:
      - lang: cURL
        source: "curl --request GET \\\n    --url :///era/v0.9/slas/{sla_id} \\\n    --header 'Authorization: Basic <basic_auth_token>'\
          \ \\\n     "
      - lang: Wget
        source: "wget --quiet \\\n    --method GET \\\n    --header 'Authorization: Basic <basic_auth_token>' \\\n      \\\
          \n    --output-document \\\n    - :///era/v0.9/slas/{sla_id}"
      - lang: Python
        source: "import http.client\n\nconn = http.client.HTTPSConnection(\"\")\n\nheaders = {\n    \"Authorization\": \"\
          Basic <basic_auth_token>\"\n}\n \nconn.request(\"GET\",\"/era/v0.9/slas/{sla_id}\", headers=headers)\n\nres = conn.getresponse()\n\
          data = res.read()\n\nprint(data.decode(\"utf-8\"))"
      - lang: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl\
          \ := \":///era/v0.9/slas/{sla_id}\"\n\t \n\treq, err := http.NewRequest(\"GET\", url, nil)\n\tif err != nil {\n\t\
          \tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n        req.Header.Add(\"Authorization\", \"\
          Basic <basic_auth_token>\")\n    \n\tres, err := http.DefaultClient.Do(req)\n\tif err != nil {\n\t\tfmt.Println(\"\
          Error creating request:\", err)\n\t\treturn\n\t}\n\n\tdefer res.Body.Close()\n\tbody, err := io.ReadAll(res.Body)\n\
          \tif err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n\tfmt.Println(res)\n\t\
          fmt.Println(string(body))\n\n}"
      - lang: Java
        source: "AsyncHttpClient client = new DefaultAsyncHttpClient();\nclient.prepare(\"GET\", \":///era/v0.9/slas/{sla_id}\"\
          )\n  .setHeader(\"Authorization\", \"Basic <basic_auth_token>\")\n  .execute()\n  .toCompletableFuture()\n  .thenAccept(System.out::println)\n\
          \  .join();\n\nclient.close();"
      - lang: JavaScript
        source: "const url = ':///era/v0.9/slas/{sla_id}';\nconst options = {\n  method: 'GET',\n  headers: {'Authorization':\
          \ 'Basic <basic_auth_token>'} \n};\n\ntry {\n  const response = await fetch(url, options);\n  const data = await\
          \ response.json();\n  console.log(data);\n} catch (error) {\n  console.error(error);\n}"
    put:
      operationId: updateSLA
      parameters:
      - in: path
        name: sla_id
        required: true
        schema:
          format: uuid
          type: string
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/EraSlaDTO'
        description: Payload required to update the given SLA.
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EraSlaDTO'
          description: Operation completed.
      summary: Update an SLA
      tags:
      - SLAs
      x-codeSamples:
      - lang: cURL
        source: "curl --request PUT \\\n    --url :///era/v0.9/slas/{sla_id} \\\n    --header 'Authorization: Basic <basic_auth_token>'\
          \ \\\n     "
      - lang: Wget
        source: "wget --quiet \\\n    --method PUT \\\n    --header 'Authorization: Basic <basic_auth_token>' \\\n      \\\
          \n    --output-document \\\n    - :///era/v0.9/slas/{sla_id}"
      - lang: Python
        source: "import http.client\n\nconn = http.client.HTTPSConnection(\"\")\n\nheaders = {\n    \"Authorization\": \"\
          Basic <basic_auth_token>\"\n}\n\npayload =  \"\"\"{}\"\"\"\n\nconn.request(\"PUT\",\"/era/v0.9/slas/{sla_id}\",\
          \ payload, headers)\n\nres = conn.getresponse()\ndata = res.read()\n\nprint(data.decode(\"utf-8\"))"
      - lang: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl\
          \ := \":///era/v0.9/slas/{sla_id}\"\n\t \n\treq, err := http.NewRequest(\"PUT\", url, nil)\n\tif err != nil {\n\t\
          \tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n        req.Header.Add(\"Authorization\", \"\
          Basic <basic_auth_token>\")\n    \n\tres, err := http.DefaultClient.Do(req)\n\tif err != nil {\n\t\tfmt.Println(\"\
          Error creating request:\", err)\n\t\treturn\n\t}\n\n\tdefer res.Body.Close()\n\tbody, err := io.ReadAll(res.Body)\n\
          \tif err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n\tfmt.Println(res)\n\t\
          fmt.Println(string(body))\n\n}"
      - lang: Java
        source: "AsyncHttpClient client = new DefaultAsyncHttpClient();\nclient.prepare(\"PUT\", \":///era/v0.9/slas/{sla_id}\"\
          )\n  .setHeader(\"Authorization\", \"Basic <basic_auth_token>\")\n  .execute()\n  .toCompletableFuture()\n  .thenAccept(System.out::println)\n\
          \  .join();\n\nclient.close();"
      - lang: JavaScript
        source: "const url = ':///era/v0.9/slas/{sla_id}';\nconst options = {\n  method: 'PUT',\n  headers: {'Authorization':\
          \ 'Basic <basic_auth_token>'} \n};\n\ntry {\n  const response = await fetch(url, options);\n  const data = await\
          \ response.json();\n  console.log(data);\n} catch (error) {\n  console.error(error);\n}"
components:
  schemas:
    EraSlaDTO:
      properties:
        continuousRetention:
          format: int32
          type: integer
        dailyRetention:
          format: int32
          type: integer
        dateCreated:
          type: string
        dateModified:
          type: string
        description:
          type: string
        id:
          format: uuid
          type: string
        monthlyRetention:
          format: int32
          type: integer
        name:
          type: string
        ownerId:
          type: string
        quarterlyRetention:
          format: int32
          type: integer
        referenceCount:
          format: int32
          type: integer
        systemSla:
          type: boolean
        uniqueName:
          type: string
        weeklyRetention:
          format: int32
          type: integer
        yearlyRetention:
          format: int32
          type: integer
      type: object
  securitySchemes:
    era_auth:
      description: NDB username and password.
      scheme: basic
      type: http
    era_token:
      description: NDB API token.
      in: header
      name: Authorization
      type: apiKey
