# GENERATED 1:1 from iam-v4.0.yaml — resource 'AuthorizationPolicy'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-iam-authorizationpolicy
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-iam-authorizationpolicy-oas/authorizationpolicy.yaml
  resourceGroup: iam.nutanix.krateo.io
  resource:
    kind: AuthorizationPolicy
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $expand
    - $filter
    - $limit
    - $orderby
    - $page
    - $select
    verbsDescription:
    - action: findby
      method: GET
      path: /iam/v4.0/authz/authorization-policies
    - action: create
      method: POST
      path: /iam/v4.0/authz/authorization-policies
    - action: get
      method: GET
      path: /iam/v4.0/authz/authorization-policies/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /iam/v4.0/authz/authorization-policies/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /iam/v4.0/authz/authorization-policies/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
