# GENERATED 1:1 from iam-v4.0.yaml — resource 'BucketsAccessKey'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-iam-bucketsaccesskey
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-iam-bucketsaccesskey-oas/bucketsaccesskey.yaml
  resourceGroup: iam.nutanix.krateo.io
  resource:
    kind: BucketsAccessKey
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $limit
    - $orderby
    - $page
    verbsDescription:
    - action: findby
      method: GET
      path: /iam/v4.0/authn/users/{userExtId}/buckets-access-keys
      requestFieldMapping:
      - inPath: userExtId
        inCustomResource: spec.userExtId
    - action: create
      method: POST
      path: /iam/v4.0/authn/users/{userExtId}/buckets-access-keys
      requestFieldMapping:
      - inPath: userExtId
        inCustomResource: spec.userExtId
    - action: get
      method: GET
      path: /iam/v4.0/authn/users/{userExtId}/buckets-access-keys/{extId}
      requestFieldMapping:
      - inPath: userExtId
        inCustomResource: spec.userExtId
      - inPath: extId
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /iam/v4.0/authn/users/{userExtId}/buckets-access-keys/{extId}
      requestFieldMapping:
      - inPath: userExtId
        inCustomResource: spec.userExtId
      - inPath: extId
        inCustomResource: status.extId
