# GENERATED 1:1 from iam-v4.0.yaml — resource 'UserGroup'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-iam-usergroup
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-iam-usergroup-oas/usergroup.yaml
  resourceGroup: iam.nutanix.krateo.io
  resource:
    kind: UserGroup
    identifiers:
    - name
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $limit
    - $orderby
    - $page
    - $select
    verbsDescription:
    - action: findby
      method: GET
      path: /iam/v4.0/authn/user-groups
    - action: create
      method: POST
      path: /iam/v4.0/authn/user-groups
    - action: get
      method: GET
      path: /iam/v4.0/authn/user-groups/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /iam/v4.0/authn/user-groups/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
