# GENERATED 1:1 from networking-v4.0.yaml — resource 'BgpRoute'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-networking-bgproute
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-networking-bgproute-oas/bgproute.yaml
  resourceGroup: networking.nutanix.krateo.io
  resource:
    kind: BgpRoute
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $limit
    - $orderby
    - $page
    verbsDescription:
    - action: findby
      method: GET
      path: /networking/v4.0/config/bgp-sessions/{bgpSessionExtId}/bgp-routes
      requestFieldMapping:
      - inPath: bgpSessionExtId
        inCustomResource: spec.bgpSessionExtId
    - action: get
      method: GET
      path: /networking/v4.0/config/bgp-sessions/{bgpSessionExtId}/bgp-routes/{extId}
      requestFieldMapping:
      - inPath: bgpSessionExtId
        inCustomResource: spec.bgpSessionExtId
      - inPath: extId
        inCustomResource: status.extId
