# GENERATED 1:1 from networking-v4.0.yaml — resource 'Layer2Stretch'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-networking-layer2stretch
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-networking-layer2stretch-oas/layer2stretch.yaml
  resourceGroup: networking.nutanix.krateo.io
  resource:
    kind: Layer2Stretch
    identifiers:
    - name
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $limit
    - $orderby
    - $page
    verbsDescription:
    - action: findby
      method: GET
      path: /networking/v4.0/config/layer2-stretches
    - action: create
      method: POST
      path: /networking/v4.0/config/layer2-stretches
    - action: get
      method: GET
      path: /networking/v4.0/config/layer2-stretches/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /networking/v4.0/config/layer2-stretches/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /networking/v4.0/config/layer2-stretches/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
