# GENERATED 1:1 from networking-v4.0.yaml — resource 'RemoteVpnConnection'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-networking-remotevpnconnection
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-networking-remotevpnconnection-oas/remotevpnconnection.yaml
  resourceGroup: networking.nutanix.krateo.io
  resource:
    kind: RemoteVpnConnection
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $limit
    - $orderby
    - $page
    verbsDescription:
    - action: findby
      method: GET
      path: /networking/v4.0/config/clusters/{clusterExtId}/remote-vpn-connections
      requestFieldMapping:
      - inPath: clusterExtId
        inCustomResource: spec.clusterExtId
    - action: get
      method: GET
      path: /networking/v4.0/config/clusters/{clusterExtId}/remote-vpn-connections/{extId}
      requestFieldMapping:
      - inPath: clusterExtId
        inCustomResource: spec.clusterExtId
      - inPath: extId
        inCustomResource: status.extId
