# GENERATED 1:1 from networking-v4.0.yaml — resource 'ReservedIp'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-networking-reservedip
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-networking-reservedip-oas/reservedip.yaml
  resourceGroup: networking.nutanix.krateo.io
  resource:
    kind: ReservedIp
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $limit
    - $orderby
    - $page
    - $select
    verbsDescription:
    - action: findby
      method: GET
      path: /networking/v4.0/config/subnets/{subnetExtId}/reserved-ips
      requestFieldMapping:
      - inPath: subnetExtId
        inCustomResource: spec.subnetExtId
