# GENERATED 1:1 from networking-v4.0.yaml — resource 'RouteTable'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-networking-routetable
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-networking-routetable-oas/routetable.yaml
  resourceGroup: networking.nutanix.krateo.io
  resource:
    kind: RouteTable
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $limit
    - $orderby
    - $page
    verbsDescription:
    - action: findby
      method: GET
      path: /networking/v4.0/config/route-tables
    - action: get
      method: GET
      path: /networking/v4.0/config/route-tables/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
