# GENERATED 1:1 from networking-v4.0.yaml — resource 'UplinkBond'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-networking-uplinkbond
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-networking-uplinkbond-oas/uplinkbond.yaml
  resourceGroup: networking.nutanix.krateo.io
  resource:
    kind: UplinkBond
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $limit
    - $orderby
    - $page
    verbsDescription:
    - action: findby
      method: GET
      path: /networking/v4.0/config/uplink-bonds
    - action: get
      method: GET
      path: /networking/v4.0/config/uplink-bonds/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
