# GENERATED 1:1 from prismv2-v1.yaml — resource 'Acknowledge3'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-acknowledge3
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-acknowledge3-oas/acknowledge3.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: Acknowledge3
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - count
    - end_time_in_usecs
    - entity_type
    - entity_type_ids
    - severity
    - start_time_in_usecs
    verbsDescription:
    - action: create
      method: POST
      path: /events/acknowledge
