# GENERATED 1:1 from prismv2-v1.yaml — resource 'AddAuthType'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-addauthtype
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-addauthtype-oas/addauthtype.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: AddAuthType
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /authconfig/add_auth_types
