# GENERATED 1:1 from prismv2-v1.yaml — resource 'AddRemoteIp'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-addremoteip
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-addremoteip-oas/addremoteip.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: AddRemoteIp
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /remote_sites/{name}/add_remote_ip
      requestFieldMapping:
      - inPath: name
        inCustomResource: spec.name
