# GENERATED 1:1 from prismv2-v1.yaml — resource 'Alert13'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-alert13
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-alert13-oas/alert13.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: Alert13
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - acknowledged
    - alert_type_uuid
    - count
    - end_time_in_usecs
    - page
    - resolved
    - severity
    - start_time_in_usecs
    verbsDescription:
    - action: findby
      method: GET
      path: /storage_containers/{uuid}/alerts
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
