# GENERATED 1:1 from prismv2-v1.yaml — resource 'AttachedDisk'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-attacheddisk
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-attacheddisk-oas/attacheddisk.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: AttachedDisk
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - snapshot_id
    verbsDescription:
    - action: findby
      method: GET
      path: /flr/{vm_uuid}/attached_disks
      requestFieldMapping:
      - inPath: vm_uuid
        inCustomResource: spec.vm_uuid
    - action: get
      method: GET
      path: /flr/{vm_uuid}/attached_disks/{snapshot_id}
      requestFieldMapping:
      - inPath: vm_uuid
        inCustomResource: spec.vm_uuid
      - inPath: snapshot_id
        inCustomResource: status.extId
