# GENERATED 1:1 from prismv2-v1.yaml — resource 'BlacklistIpAddress'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-blacklistipaddress
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-blacklistipaddress-oas/blacklistipaddress.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: BlacklistIpAddress
    identifiers:
    - value
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /networks/{uuid}/blacklist_ip_addresses
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
