# GENERATED 1:1 from prismv2-v1.yaml — resource 'Clone3'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-clone3
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-clone3-oas/clone3.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: Clone3
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /vms/{uuid}/clone
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
