# GENERATED 1:1 from prismv2-v1.yaml — resource 'ConflictingPolicy'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-conflictingpolicy
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-conflictingpolicy-oas/conflictingpolicy.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: ConflictingPolicy
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /alerts/policies/conflicting_policies
