# GENERATED 1:1 from prismv2-v1.yaml — resource 'ConsistencyGroup'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-consistencygroup
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-consistencygroup-oas/consistencygroup.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: ConsistencyGroup
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - consistency_groups
    - include_deleted
    - protection_domains
    verbsDescription:
    - action: findby
      method: GET
      path: /protection_domains/consistency_groups
