# GENERATED 1:1 from prismv2-v1.yaml — resource 'ConsistencyGroup3'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-consistencygroup3
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-consistencygroup3-oas/consistencygroup3.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: ConsistencyGroup3
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - cg_name
    verbsDescription:
    - action: update
      method: PUT
      path: /protection_domains/{pd_name}/consistency_groups/{cg_name}
      requestFieldMapping:
      - inPath: pd_name
        inCustomResource: spec.pd_name
      - inPath: cg_name
        inCustomResource: status.extId
