# GENERATED 1:1 from prismv2-v1.yaml — resource 'DeleteFile'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-deletefile
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-deletefile-oas/deletefile.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: DeleteFile
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /file_groups/{uuid}/delete_files
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
