# GENERATED 1:1 from prismv2-v1.yaml — resource 'Detach'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-detach
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-detach-oas/detach.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: Detach
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /vms/{uuid}/disks/detach
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
