# GENERATED 1:1 from prismv2-v1.yaml — resource 'DetachNodeFromMetadataStore'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-detachnodefrommetadatastore
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-detachnodefrommetadatastore-oas/detachnodefrommetadatastore.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: DetachNodeFromMetadataStore
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /hosts/{uuid}/detach_node_from_metadata_store
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
