# GENERATED 1:1 from prismv2-v1.yaml — resource 'Directory'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-directory
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-directory-oas/directory.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: Directory
    identifiers:
    - name
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - name
    verbsDescription:
    - action: findby
      method: GET
      path: /authconfig/directories
    - action: create
      method: POST
      path: /authconfig/directories
    - action: get
      method: GET
      path: /authconfig/directories/{name}
      requestFieldMapping:
      - inPath: name
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /authconfig/directories/{name}
      requestFieldMapping:
      - inPath: name
        inCustomResource: status.extId
