# GENERATED 1:1 from prismv2-v1.yaml — resource 'DownloadSnapshot'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-downloadsnapshot
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-downloadsnapshot-oas/downloadsnapshot.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: DownloadSnapshot
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /remote_sites/{name}/dr_snapshots/download_snapshot
      requestFieldMapping:
      - inPath: name
        inCustomResource: spec.name
