# GENERATED 1:1 from prismv2-v1.yaml — resource 'DrSnapshot3'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-drsnapshot3
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-drsnapshot3-oas/drsnapshot3.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: DrSnapshot3
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - snapshot_id
    verbsDescription:
    - action: delete
      method: DELETE
      path: /protection_domains/{protection_domain_name}/dr_snapshots/{snapshot_id}
      requestFieldMapping:
      - inPath: protection_domain_name
        inCustomResource: spec.protection_domain_name
      - inPath: snapshot_id
        inCustomResource: status.extId
