# GENERATED 1:1 from prismv2-v1.yaml — resource 'DrSnapshot2'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-drsnapshot2
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-drsnapshot2-oas/drsnapshot2.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: DrSnapshot2
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - count
    - filter_criteria
    - full_details
    - oob_schedule_ids
    - sort_criteria
    verbsDescription:
    - action: findby
      method: GET
      path: /protection_domains/{name}/dr_snapshots
      requestFieldMapping:
      - inPath: name
        inCustomResource: spec.name
