# GENERATED 1:1 from prismv2-v1.yaml — resource 'DrSnapshot'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-drsnapshot
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-drsnapshot-oas/drsnapshot.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: DrSnapshot
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - count
    - filter_criteria
    - full_details
    - sort_criteria
    verbsDescription:
    - action: findby
      method: GET
      path: /protection_domains/dr_snapshots
