# GENERATED 1:1 from prismv2-v1.yaml — resource 'EnableMonitoring'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-enablemonitoring
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-enablemonitoring-oas/enablemonitoring.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: EnableMonitoring
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /hosts/{uuid}/enable_monitoring
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
