# GENERATED 1:1 from prismv2-v1.yaml — resource 'ExitMaintenanceMode'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-exitmaintenancemode
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-exitmaintenancemode-oas/exitmaintenancemode.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: ExitMaintenanceMode
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /hosts/{uuid}/exit_maintenance_mode
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
