# GENERATED 1:1 from prismv2-v1.yaml — resource 'HealthCheck'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-healthcheck
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-healthcheck-oas/healthcheck.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: HealthCheck
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - category_types
    - check_ids
    - global_config
    - id
    - include_internal_checks
    verbsDescription:
    - action: findby
      method: GET
      path: /health_checks
    - action: get
      method: GET
      path: /health_checks/{id}
      requestFieldMapping:
      - inPath: id
        inCustomResource: status.extId
