# GENERATED 1:1 from prismv2-v1.yaml — resource 'HostGpu'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-hostgpu
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-hostgpu-oas/hostgpu.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: HostGpu
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - count
    - filter_criteria
    - search_string
    - sort_criteria
    verbsDescription:
    - action: findby
      method: GET
      path: /hosts/host_gpus
