# GENERATED 1:1 from prismv2-v1.yaml — resource 'HostNic'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-hostnic
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-hostnic-oas/hostnic.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: HostNic
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - pnic_id
    verbsDescription:
    - action: findby
      method: GET
      path: /hosts/{uuid}/host_nics
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
    - action: get
      method: GET
      path: /hosts/{uuid}/host_nics/{pnic_id}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
      - inPath: pnic_id
        inCustomResource: status.extId
