# GENERATED 1:1 from prismv2-v1.yaml — resource 'HostNicsStat'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-hostnicsstat
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-hostnicsstat-oas/hostnicsstat.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: HostNicsStat
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - end_time_in_usecs
    - interval_in_secs
    - metrics
    - start_time_in_usecs
    verbsDescription:
    - action: findby
      method: GET
      path: /hosts/{uuid}/host_nics/{pnic_id}/stats
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
      - inPath: pnic_id
        inCustomResource: spec.pnic_id
