# GENERATED 1:1 from prismv2-v1.yaml — resource 'HttpProxy'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-httpproxy
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-httpproxy-oas/httpproxy.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: HttpProxy
    identifiers:
    - name
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - name
    verbsDescription:
    - action: findby
      method: GET
      path: /http_proxies
    - action: create
      method: POST
      path: /http_proxies
    - action: get
      method: GET
      path: /http_proxies/{name}
      requestFieldMapping:
      - inPath: name
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /http_proxies/{name}
      requestFieldMapping:
      - inPath: name
        inCustomResource: status.extId
