# GENERATED 1:1 from prismv2-v1.yaml — resource 'JoinDomain'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-joindomain
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-joindomain-oas/joindomain.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: JoinDomain
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /hosts/join_domain
