# GENERATED 1:1 from prismv2-v1.yaml — resource 'MetroAvailDisable'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-metroavaildisable
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-metroavaildisable-oas/metroavaildisable.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: MetroAvailDisable
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - skip_remote_check
    verbsDescription:
    - action: create
      method: POST
      path: /protection_domains/{pd_name}/metro_avail_disable
      requestFieldMapping:
      - inPath: pd_name
        inCustomResource: spec.pd_name
