# GENERATED 1:1 from prismv2-v1.yaml — resource 'NameServer'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-nameserver
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-nameserver-oas/nameserver.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: NameServer
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - nameServer
    verbsDescription:
    - action: findby
      method: GET
      path: /cluster/name_servers
    - action: create
      method: POST
      path: /cluster/name_servers
    - action: delete
      method: DELETE
      path: /cluster/name_servers/{nameServer}
      requestFieldMapping:
      - inPath: nameServer
        inCustomResource: status.extId
