# GENERATED 1:1 from prismv2-v1.yaml — resource 'Nic'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-nic
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-nic-oas/nic.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: Nic
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - include_address_assignments
    - nic_id
    verbsDescription:
    - action: findby
      method: GET
      path: /vms/{uuid}/nics
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
    - action: create
      method: POST
      path: /vms/{uuid}/nics
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
    - action: update
      method: PUT
      path: /vms/{uuid}/nics/{nic_id}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
      - inPath: nic_id
        inCustomResource: status.extId
