# GENERATED 1:1 from prismv2-v1.yaml — resource 'Nic2'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-nic2
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-nic2-oas/nic2.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: Nic2
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - include_address_assignments
    - nic_id
    - vm_logical_timestamp
    verbsDescription:
    - action: get
      method: GET
      path: /vms/{vm_uuid}/nics/{nic_id}
      requestFieldMapping:
      - inPath: vm_uuid
        inCustomResource: spec.vm_uuid
      - inPath: nic_id
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /vms/{vm_uuid}/nics/{nic_id}
      requestFieldMapping:
      - inPath: vm_uuid
        inCustomResource: spec.vm_uuid
      - inPath: nic_id
        inCustomResource: status.extId
