# GENERATED 1:1 from prismv2-v1.yaml — resource 'OobSchedule'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-oobschedule
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-oobschedule-oas/oobschedule.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: OobSchedule
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - protection_domain_names
    verbsDescription:
    - action: findby
      method: GET
      path: /protection_domains/oob_schedules
