# GENERATED 1:1 from prismv2-v1.yaml — resource 'Policy2'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-policy2
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-policy2-oas/policy2.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: Policy2
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - policy_uuid
    verbsDescription:
    - action: delete
      method: DELETE
      path: /remote_sites/policies/{policy_uuid}
      requestFieldMapping:
      - inPath: policy_uuid
        inCustomResource: status.extId
