# GENERATED 1:1 from prismv2-v1.yaml — resource 'ProtectionDomain'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-protectiondomain
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-protectiondomain-oas/protectiondomain.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: ProtectionDomain
    identifiers:
    - value
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - include_deleted
    - metro_avail
    - name
    - names
    - projection
    - remote_site_name
    - remote_site_to_forward
    - skip_remote_check
    - vstore_name
    verbsDescription:
    - action: findby
      method: GET
      path: /protection_domains
    - action: create
      method: POST
      path: /protection_domains
    - action: get
      method: GET
      path: /protection_domains/{name}
      requestFieldMapping:
      - inPath: name
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /protection_domains/{name}
      requestFieldMapping:
      - inPath: name
        inCustomResource: status.extId
