# GENERATED 1:1 from prismv2-v1.yaml — resource 'Proxy'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-proxy
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-proxy-oas/proxy.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: Proxy
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /remote_sites/{name}/proxy
      requestFieldMapping:
      - inPath: name
        inCustomResource: spec.name
