# GENERATED 1:1 from prismv2-v1.yaml — resource 'RackableUnit'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-rackableunit
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-rackableunit-oas/rackableunit.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: RackableUnit
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - uuid
    verbsDescription:
    - action: findby
      method: GET
      path: /cluster/rackable_units
    - action: get
      method: GET
      path: /cluster/rackable_units/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /cluster/rackable_units/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
