# GENERATED 1:1 from prismv2-v1.yaml — resource 'RecentCertificateTestResult'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-recentcertificatetestresult
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-recentcertificatetestresult-oas/recentcertificatetestresult.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: RecentCertificateTestResult
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - host_uuids
    - kms_server_names
    verbsDescription:
    - action: findby
      method: GET
      path: /data_at_rest_encryption/recent_certificate_test_results
