# GENERATED 1:1 from prismv2-v1.yaml — resource 'Rekey2'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-rekey2
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-rekey2-oas/rekey2.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: Rekey2
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /data_at_rest_encryption/software/rekey
