# GENERATED 1:1 from prismv2-v1.yaml — resource 'RemoteSupport'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-remotesupport
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-remotesupport-oas/remotesupport.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: RemoteSupport
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /cluster/remote_support
