# GENERATED 1:1 from prismv2-v1.yaml — resource 'Replication3'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-replication3
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-replication3-oas/replication3.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: Replication3
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - id
    verbsDescription:
    - action: update
      method: PUT
      path: /protection_domains/{protection_domain_name}/replications/{id}
      requestFieldMapping:
      - inPath: protection_domain_name
        inCustomResource: spec.protection_domain_name
      - inPath: id
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /protection_domains/{protection_domain_name}/replications/{id}
      requestFieldMapping:
      - inPath: protection_domain_name
        inCustomResource: spec.protection_domain_name
      - inPath: id
        inCustomResource: status.extId
