# GENERATED 1:1 from prismv2-v1.yaml — resource 'Resolve'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-resolve
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-resolve-oas/resolve.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: Resolve
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - classifications
    - count
    - end_time_in_usecs
    - entity_type
    - entity_type_ids
    - impact_types
    - severity
    - start_time_in_usecs
    verbsDescription:
    - action: create
      method: POST
      path: /alerts/resolve
