# GENERATED 1:1 from prismv2-v1.yaml — resource 'Resolve2'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-resolve2
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-resolve2-oas/resolve2.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: Resolve2
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /alerts/{id}/resolve
      requestFieldMapping:
      - inPath: id
        inCustomResource: spec.id
