# GENERATED 1:1 from prismv2-v1.yaml — resource 'RestoreEntity'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-restoreentity
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-restoreentity-oas/restoreentity.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: RestoreEntity
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /protection_domains/{name}/restore_entities
      requestFieldMapping:
      - inPath: name
        inCustomResource: spec.name
