# GENERATED 1:1 from prismv2-v1.yaml — resource 'Retain'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-retain
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-retain-oas/retain.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: Retain
    identifiers:
    - value
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /protection_domains/{protection_domain_name}/dr_snapshots/{snapshot_id}/retain
      requestFieldMapping:
      - inPath: protection_domain_name
        inCustomResource: spec.protection_domain_name
      - inPath: snapshot_id
        inCustomResource: spec.snapshot_id
