# GENERATED 1:1 from prismv2-v1.yaml — resource 'SchedulesRemoveList'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-schedulesremovelist
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-schedulesremovelist-oas/schedulesremovelist.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: SchedulesRemoveList
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /protection_domains/{name}/schedules/remove_list
      requestFieldMapping:
      - inPath: name
        inCustomResource: spec.name
