# GENERATED 1:1 from prismv2-v1.yaml — resource 'Smtp'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-smtp
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-smtp-oas/smtp.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: Smtp
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /cluster/smtp
