# GENERATED 1:1 from prismv2-v1.yaml — resource 'Snapshot'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-snapshot
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-snapshot-oas/snapshot.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: Snapshot
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - snapshot_count
    verbsDescription:
    - action: findby
      method: GET
      path: /flr/{vm_uuid}/snapshots
      requestFieldMapping:
      - inPath: vm_uuid
        inCustomResource: spec.vm_uuid
