# GENERATED 1:1 from prismv2-v1.yaml — resource 'Snapshot2'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-snapshot2
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-snapshot2-oas/snapshot2.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: Snapshot2
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - logical_timestamp
    - uuid
    - vm_uuid
    verbsDescription:
    - action: findby
      method: GET
      path: /snapshots
    - action: create
      method: POST
      path: /snapshots
    - action: get
      method: GET
      path: /snapshots/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /snapshots/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
