# GENERATED 1:1 from prismv2-v1.yaml — resource 'SoftwaresDownload'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-softwaresdownload
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-softwaresdownload-oas/softwaresdownload.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: SoftwaresDownload
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /upgrade/{type}/softwares/{name}/download
      requestFieldMapping:
      - inPath: type
        inCustomResource: spec.type
      - inPath: name
        inCustomResource: spec.name
