# GENERATED 1:1 from prismv2-v1.yaml — resource 'Stat9'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-stat9
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-stat9-oas/stat9.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: Stat9
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - end_time_usecs
    - interval_in_secs
    - metrics
    - start_time_usecs
    verbsDescription:
    - action: findby
      method: GET
      path: /volume_groups/{uuid}/stats
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
