# GENERATED 1:1 from prismv2-v1.yaml — resource 'Statu2'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-statu2
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-statu2-oas/statu2.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: Statu2
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /snmp/status
