# GENERATED 1:1 from prismv2-v1.yaml — resource 'Stat'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-stat
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-stat-oas/stat.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: Stat
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - end_time_in_usecs
    - interval_in_secs
    - metrics
    - start_time_in_usecs
    verbsDescription:
    - action: findby
      method: GET
      path: /cluster/stats
