# GENERATED 1:1 from prismv2-v1.yaml — resource 'TrackOobSchedule'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-trackoobschedule
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-trackoobschedule-oas/trackoobschedule.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: TrackOobSchedule
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - id
    verbsDescription:
    - action: get
      method: GET
      path: /protection_domains/{name}/track_oob_schedule/{id}
      requestFieldMapping:
      - inPath: name
        inCustomResource: spec.name
      - inPath: id
        inCustomResource: status.extId
