# GENERATED 1:1 from prismv2-v1.yaml — resource 'Unprotect'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-unprotect
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-unprotect-oas/unprotect.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: Unprotect
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /vstores/{uuid}/unprotect
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
