# GENERATED 1:1 from prismv2-v1.yaml — resource 'Upload'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-upload
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-upload-oas/upload.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: Upload
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - file_size
    - hypervisor_type
    - md5sum
    - offset
    - overwrite
    - software_metadata
    - version
    verbsDescription:
    - action: create
      method: POST
      path: /upgrade/{type}/softwares/{name}/upload
      requestFieldMapping:
      - inPath: type
        inCustomResource: spec.type
      - inPath: name
        inCustomResource: spec.name
