# GENERATED 1:1 from prismv2-v1.yaml — resource 'ValidateUpload'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-validateupload
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-validateupload-oas/validateupload.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: ValidateUpload
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /upgrade/{type}/softwares/validate_upload
      requestFieldMapping:
      - inPath: type
        inCustomResource: spec.type
