# GENERATED 1:1 from prismv2-v1.yaml — resource 'Vdisk2'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-vdisk2
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-vdisk2-oas/vdisk2.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: Vdisk2
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - path
    verbsDescription:
    - action: findby
      method: GET
      path: /vdisks
