# GENERATED 1:1 from prismv2-v1.yaml — resource 'VirtualNicsStat'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-virtualnicsstat
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-virtualnicsstat-oas/virtualnicsstat.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: VirtualNicsStat
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - end_time_in_usecs
    - interval_in_secs
    - metrics
    - start_time_in_usecs
    verbsDescription:
    - action: findby
      method: GET
      path: /hosts/{uuid}/virtual_nics/{vnic_id}/stats
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
      - inPath: vnic_id
        inCustomResource: spec.vnic_id
