# GENERATED 1:1 from prismv2-v1.yaml — resource 'VirtualNic'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-virtualnic
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-virtualnic-oas/virtualnic.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: VirtualNic
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - vnic_id
    verbsDescription:
    - action: findby
      method: GET
      path: /hosts/{uuid}/virtual_nics
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
    - action: get
      method: GET
      path: /hosts/{uuid}/virtual_nics/{vnic_id}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
      - inPath: vnic_id
        inCustomResource: status.extId
