# GENERATED 1:1 from prismv2-v1.yaml — resource 'VirtualDisk'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-virtualdisk
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-virtualdisk-oas/virtualdisk.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: VirtualDisk
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - count
    - filter_criteria
    - page
    - projection
    - search_attribute_list
    - search_string
    - sort_criteria
    - uuid
    verbsDescription:
    - action: findby
      method: GET
      path: /virtual_disks
    - action: get
      method: GET
      path: /virtual_disks/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
