# GENERATED 1:1 from prismv2-v1.yaml — resource 'VolumeGroup'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-volumegroup
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-volumegroup-oas/volumegroup.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: VolumeGroup
    identifiers:
    - name
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - include_disk_path
    - include_disk_size
    - logical_timestamp
    - uuid
    verbsDescription:
    - action: findby
      method: GET
      path: /volume_groups
    - action: create
      method: POST
      path: /volume_groups
    - action: get
      method: GET
      path: /volume_groups/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /volume_groups/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /volume_groups/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
