# GENERATED 1:1 from prismv2-v1.yaml — resource 'Vstore'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv2-vstore
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv2-vstore-oas/vstore.yaml
  resourceGroup: prismv2.nutanix.krateo.io
  resource:
    kind: Vstore
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - include_deleted
    - names
    - uuid
    - uuids
    verbsDescription:
    - action: findby
      method: GET
      path: /vstores
    - action: get
      method: GET
      path: /vstores/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
