# GENERATED 1:1 from dataprotection-v4.0.yaml — resource 'ProtectedResource'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-dataprotection-protectedresource
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-dataprotection-protectedresource-oas/protectedresource.yaml
  resourceGroup: dataprotection.nutanix.krateo.io
  resource:
    kind: ProtectedResource
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: get
      method: GET
      path: /dataprotection/v4.0/config/protected-resources/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
