# GENERATED 1:1 from dataprotection-v4.0.yaml — resource 'VmRecoveryPoint'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-dataprotection-vmrecoverypoint
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-dataprotection-vmrecoverypoint-oas/vmrecoverypoint.yaml
  resourceGroup: dataprotection.nutanix.krateo.io
  resource:
    kind: VmRecoveryPoint
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: get
      method: GET
      path: /dataprotection/v4.0/config/recovery-points/{recoveryPointExtId}/vm-recovery-points/{extId}
      requestFieldMapping:
      - inPath: recoveryPointExtId
        inCustomResource: spec.recoveryPointExtId
      - inPath: extId
        inCustomResource: status.extId
