# GENERATED 1:1 from security-v4.0.yaml — resource 'ApprovalPolicy'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-security-approvalpolicy
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-security-approvalpolicy-oas/approvalpolicy.yaml
  resourceGroup: security.nutanix.krateo.io
  resource:
    kind: ApprovalPolicy
    identifiers:
    - name
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $orderby
    - $select
    verbsDescription:
    - action: findby
      method: GET
      path: /security/v4.0/management/approval-policies
    - action: create
      method: POST
      path: /security/v4.0/management/approval-policies
    - action: get
      method: GET
      path: /security/v4.0/management/approval-policies/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /security/v4.0/management/approval-policies/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
