# GENERATED 1:1 from security-v4.0.yaml — resource 'StigSummary'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-security-stigsummary
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-security-stigsummary-oas/stigsummary.yaml
  resourceGroup: security.nutanix.krateo.io
  resource:
    kind: StigSummary
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $expand
    - $filter
    - $limit
    - $orderby
    - $page
    - $select
    verbsDescription:
    - action: findby
      method: GET
      path: /security/v4.0/report/stig-summaries
