# GENERATED 1:1 from vmm-v4.0.yaml — resource 'AhvVmComplianceState'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-vmm-ahvvmcompliancestate
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-vmm-ahvvmcompliancestate-oas/ahvvmcompliancestate.yaml
  resourceGroup: vmm.nutanix.krateo.io
  resource:
    kind: AhvVmComplianceState
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $limit
    - $page
    verbsDescription:
    - action: findby
      method: GET
      path: /vmm/v4.0/ahv/policies/vm-host-affinity-policies/{vmHostAffinityPolicyExtId}/vm-compliance-states
      requestFieldMapping:
      - inPath: vmHostAffinityPolicyExtId
        inCustomResource: spec.vmHostAffinityPolicyExtId
