# GENERATED 1:1 from vmm-v4.0.yaml — resource 'GuestTool'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-vmm-guesttool
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-vmm-guesttool-oas/guesttool.yaml
  resourceGroup: vmm.nutanix.krateo.io
  resource:
    kind: GuestTool
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /vmm/v4.0/ahv/config/vms/{extId}/guest-tools
      requestFieldMapping:
      - inPath: extId
        inCustomResource: spec.extId
