# GENERATED 1:1 from vmm-v4.0.yaml — resource 'LegacyVmAntiAffinityPolicy'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-vmm-legacyvmantiaffinitypolicy
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-vmm-legacyvmantiaffinitypolicy-oas/legacyvmantiaffinitypolicy.yaml
  resourceGroup: vmm.nutanix.krateo.io
  resource:
    kind: LegacyVmAntiAffinityPolicy
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $limit
    - $page
    verbsDescription:
    - action: findby
      method: GET
      path: /vmm/v4.0/ahv/policies/legacy-vm-anti-affinity-policies
    - action: delete
      method: DELETE
      path: /vmm/v4.0/ahv/policies/legacy-vm-anti-affinity-policies/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
