# GENERATED 1:1 from vmm-v4.0.yaml — resource 'Nic'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-vmm-nic
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-vmm-nic-oas/nic.yaml
  resourceGroup: vmm.nutanix.krateo.io
  resource:
    kind: Nic
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $limit
    - $page
    verbsDescription:
    - action: findby
      method: GET
      path: /vmm/v4.0/ahv/config/vms/{vmExtId}/nics
      requestFieldMapping:
      - inPath: vmExtId
        inCustomResource: spec.vmExtId
    - action: create
      method: POST
      path: /vmm/v4.0/ahv/config/vms/{vmExtId}/nics
      requestFieldMapping:
      - inPath: vmExtId
        inCustomResource: spec.vmExtId
    - action: get
      method: GET
      path: /vmm/v4.0/ahv/config/vms/{vmExtId}/nics/{extId}
      requestFieldMapping:
      - inPath: vmExtId
        inCustomResource: spec.vmExtId
      - inPath: extId
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /vmm/v4.0/ahv/config/vms/{vmExtId}/nics/{extId}
      requestFieldMapping:
      - inPath: vmExtId
        inCustomResource: spec.vmExtId
      - inPath: extId
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /vmm/v4.0/ahv/config/vms/{vmExtId}/nics/{extId}
      requestFieldMapping:
      - inPath: vmExtId
        inCustomResource: spec.vmExtId
      - inPath: extId
        inCustomResource: status.extId
