# GENERATED 1:1 from vmm-v4.0.yaml — resource 'SerialPort'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-vmm-serialport
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-vmm-serialport-oas/serialport.yaml
  resourceGroup: vmm.nutanix.krateo.io
  resource:
    kind: SerialPort
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $limit
    - $page
    verbsDescription:
    - action: findby
      method: GET
      path: /vmm/v4.0/ahv/config/vms/{vmExtId}/serial-ports
      requestFieldMapping:
      - inPath: vmExtId
        inCustomResource: spec.vmExtId
    - action: create
      method: POST
      path: /vmm/v4.0/ahv/config/vms/{vmExtId}/serial-ports
      requestFieldMapping:
      - inPath: vmExtId
        inCustomResource: spec.vmExtId
    - action: get
      method: GET
      path: /vmm/v4.0/ahv/config/vms/{vmExtId}/serial-ports/{extId}
      requestFieldMapping:
      - inPath: vmExtId
        inCustomResource: spec.vmExtId
      - inPath: extId
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /vmm/v4.0/ahv/config/vms/{vmExtId}/serial-ports/{extId}
      requestFieldMapping:
      - inPath: vmExtId
        inCustomResource: spec.vmExtId
      - inPath: extId
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /vmm/v4.0/ahv/config/vms/{vmExtId}/serial-ports/{extId}
      requestFieldMapping:
      - inPath: vmExtId
        inCustomResource: spec.vmExtId
      - inPath: extId
        inCustomResource: status.extId
