# GENERATED 1:1 from vmm-v4.0.yaml — resource 'Template'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-vmm-template
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-vmm-template-oas/template.yaml
  resourceGroup: vmm.nutanix.krateo.io
  resource:
    kind: Template
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $limit
    - $orderby
    - $page
    - $select
    verbsDescription:
    - action: findby
      method: GET
      path: /vmm/v4.0/content/templates
    - action: create
      method: POST
      path: /vmm/v4.0/content/templates
    - action: get
      method: GET
      path: /vmm/v4.0/content/templates/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /vmm/v4.0/content/templates/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /vmm/v4.0/content/templates/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
