# GENERATED 1:1 from vmm-v4.0.yaml — resource 'VmComplianceState'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-vmm-vmcompliancestate
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-vmm-vmcompliancestate-oas/vmcompliancestate.yaml
  resourceGroup: vmm.nutanix.krateo.io
  resource:
    kind: VmComplianceState
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $limit
    - $page
    verbsDescription:
    - action: findby
      method: GET
      path: /vmm/v4.0/ahv/policies/vm-anti-affinity-policies/{vmAntiAffinityPolicyExtId}/vm-compliance-states
      requestFieldMapping:
      - inPath: vmAntiAffinityPolicyExtId
        inCustomResource: spec.vmAntiAffinityPolicyExtId
