# GENERATED 1:1 from vmm-v4.0.yaml — resource 'VmHostAffinityPolicy'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-vmm-vmhostaffinitypolicy
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-vmm-vmhostaffinitypolicy-oas/vmhostaffinitypolicy.yaml
  resourceGroup: vmm.nutanix.krateo.io
  resource:
    kind: VmHostAffinityPolicy
    identifiers:
    - name
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $limit
    - $orderby
    - $page
    verbsDescription:
    - action: findby
      method: GET
      path: /vmm/v4.0/ahv/policies/vm-host-affinity-policies
    - action: create
      method: POST
      path: /vmm/v4.0/ahv/policies/vm-host-affinity-policies
    - action: get
      method: GET
      path: /vmm/v4.0/ahv/policies/vm-host-affinity-policies/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /vmm/v4.0/ahv/policies/vm-host-affinity-policies/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /vmm/v4.0/ahv/policies/vm-host-affinity-policies/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
