# GENERATED 1:1 from storage-v4.0.a3.yaml — resource 'CategoryAssociation'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-storage-categoryassociation
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-storage-categoryassociation-oas/categoryassociation.yaml
  resourceGroup: storage.nutanix.krateo.io
  resource:
    kind: CategoryAssociation
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $limit
    - $page
    verbsDescription:
    - action: findby
      method: GET
      path: /storage/v4.0.a3/config/volume-groups/{volumeGroupExtId}/category-associations
      requestFieldMapping:
      - inPath: volumeGroupExtId
        inCustomResource: spec.volumeGroupExtId
