# GENERATED 1:1 from storage-v4.0.a3.yaml — resource 'Datastore'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-storage-datastore
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-storage-datastore-oas/datastore.yaml
  resourceGroup: storage.nutanix.krateo.io
  resource:
    kind: Datastore
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    verbsDescription:
    - action: findby
      method: GET
      path: /storage/v4.0.a3/config/storage-containers/datastores
