# GENERATED 1:1 from storage-v4.0.a3.yaml — resource 'IscsiClient'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-storage-iscsiclient
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-storage-iscsiclient-oas/iscsiclient.yaml
  resourceGroup: storage.nutanix.krateo.io
  resource:
    kind: IscsiClient
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $limit
    - $orderby
    - $page
    verbsDescription:
    - action: findby
      method: GET
      path: /storage/v4.0.a3/config/iscsi-clients
    - action: get
      method: GET
      path: /storage/v4.0.a3/config/iscsi-clients/{clientId}
      requestFieldMapping:
      - inPath: clientId
        inCustomResource: status.extId
