# GENERATED 1:1 from storage-v4.0.a3.yaml — resource 'IscsiClientAttachment'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-storage-iscsiclientattachment
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-storage-iscsiclientattachment-oas/iscsiclientattachment.yaml
  resourceGroup: storage.nutanix.krateo.io
  resource:
    kind: IscsiClientAttachment
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $limit
    - $orderby
    - $page
    verbsDescription:
    - action: findby
      method: GET
      path: /storage/v4.0.a3/config/volume-groups/{volumeGroupExtId}/iscsi-client-attachments
      requestFieldMapping:
      - inPath: volumeGroupExtId
        inCustomResource: spec.volumeGroupExtId
