# GENERATED 1:1 from storage-v4.0.a3.yaml — resource 'MetadataInfo'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-storage-metadatainfo
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-storage-metadatainfo-oas/metadatainfo.yaml
  resourceGroup: storage.nutanix.krateo.io
  resource:
    kind: MetadataInfo
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /storage/v4.0.a3/config/volume-groups/{volumeGroupExtId}/metadata-info
      requestFieldMapping:
      - inPath: volumeGroupExtId
        inCustomResource: spec.volumeGroupExtId
