# GENERATED 1:1 from storage-v4.0.a3.yaml — resource 'StorageContainer'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-storage-storagecontainer
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-storage-storagecontainer-oas/storagecontainer.yaml
  resourceGroup: storage.nutanix.krateo.io
  resource:
    kind: StorageContainer
    identifiers:
    - name
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $limit
    - $orderby
    - $page
    - $select
    - ignoreSmallFiles
    verbsDescription:
    - action: findby
      method: GET
      path: /storage/v4.0.a3/config/storage-containers
    - action: create
      method: POST
      path: /storage/v4.0.a3/config/storage-containers
    - action: get
      method: GET
      path: /storage/v4.0.a3/config/storage-containers/{containerExtId}
      requestFieldMapping:
      - inPath: containerExtId
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /storage/v4.0.a3/config/storage-containers/{containerExtId}
      requestFieldMapping:
      - inPath: containerExtId
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /storage/v4.0.a3/config/storage-containers/{containerExtId}
      requestFieldMapping:
      - inPath: containerExtId
        inCustomResource: status.extId
