openapi: 3.0.1
info:
  title: Nutanix Storage APIs
  description: Manage storage configuration and operations.
  version: 4.0.1-alpha-3
  x-repo-name: storage
  x-logo:
    altText: Storage Logo
    url: https://developers.nutanix.com/api/v1/namespaces/storage/images/storage-logo-img.svg
  x-minimum-negotiation-version: v4.2
servers:
- url: https://{pc-ip}:9440/api
security:
- basicAuthScheme: []
paths:
  /storage/v4.0.a3/config/storage-containers/datastores:
    get:
      tags:
      - StorageContainer
      summary: Get the Data Stores.
      description: Query the list of Data Stores.
      operationId: getDataStores
      parameters:
      - name: $filter
        in: query
        description: 'A URL query parameter that allows clients to filter a collection of resources. The expression specified
          with $filter is evaluated for each resource in the collection, and only items where the expression evaluates to
          true are included in the response. Expression specified with the $filter must conform to the OData V4.01 URL conventions.

          The filter can be applied on the following fields:

          - containerExtId

          '
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        '200':
          description: Successfully retrieved the list of Data Stores.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/storage.v4.r0.a3.config.DataStoreResponse'
        4XX:
          description: Client error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/storage.v4.r0.a3.config.DataStoreResponse'
        5XX:
          description: Server error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/storage.v4.r0.a3.config.DataStoreResponse'
      x-code-samples:
      - lang: Java
        source: "\npackage sample;\n\nimport com.nutanix.sto.java.client.ApiClient;\nimport com.nutanix.sto.java.client.api.StorageContainerApi;\n\
          import com.nutanix.dp1.sto.storage.v4.config.DataStoreResponse;\n\npublic class JavaSdkSample {\n\tpublic static\
          \ void main(String[] args) {\n\t\tApiClient client = new ApiClient();\n\t\tclient.setHost(\"localhost\");\n\t\t\
          client.setPort(9440);\n\t\tclient.setRetryInterval(100);\n\t\tclient.setMaxRetryAttempts(2);\n\t\tclient.setUsername(\"\
          username\");\n\t\tclient.setPassword(\"password\");\n\n\t\tStorageContainerApi storageContainerApi = new StorageContainerApi(client);\n\
          \n\t\tString $filter = \"string_sample_data\";\n\t\tDataStoreResponse dataStoreResponse = storageContainerApi.getDataStores($filter);\n\
          \t}\n}\n"
      - lang: JavaScript
        source: "\nimport ApiClient from \"@nutanix/prism-apis-js-client/src/ApiClient\";\nimport StorageContainerApi from\
          \ \"@nutanix/prism-apis-js-client/src/apis/StorageContainer-endpoints\";\nimport DataStoreResponse from \"@nutanix/prism-apis-js-client/src/models/storage/v4/config/DataStoreResponse\"\
          ;\n\nlet apiClientInstance = new ApiClient();\napiClientInstance.maxRetryAttempts = 2;\napiClientInstance.retryInterval\
          \ = 500;\napiClientInstance.host = 'localhost'\napiClientInstance.port = '9440';\napiClientInstance.username = 'username';\n\
          apiClientInstance.password = 'password';\nlet storageContainerApi = new StorageContainerApi(apiClientInstance);\n\
          \nfunction sample() {\n    let $filter = \"string_sample_data\";\n\n    storageContainerApi.getDataStores($filter).then(({data,\
          \ response}) =>\n        console.log(response.status);\n        console.log(data.getData());\n        done();\n\
          \    }).catch((error) => {\n        console.log(error);\n        done(error);\n    });\n}\n"
      - lang: Python
        source: "\nimport ntnx_prism-apis_py_client\n\nif __name__ == \"__main__\":\n    config = ntnx_prism-apis_py_client.configuration.Configuration()\n\
          \    config.host = \"localhost\"\n    config.port = 9440\n    config.max_retry_attempts = 1\n    config.backoff_factor\
          \ = 3\n    config.username = \"username\"\n    config.password = \"password\"\n    client = ntnx_prism-apis_py_client.ApiClient(configuration=config)\n\
          \    storageContainerApi = ntnx_prism-apis_py_client.StorageContainerApi(api_client=client)\n    $filter = \"string_sample_data\"\
          \n    api_response = storageContainerApi.get_data_stores($filter)\n"
      - lang: Go
        source: "\npackage main\n\nimport {\n    \"fmt\"\n    \"nutanix/prism-apis-go-client/v4/api\"\n    \"nutanix/prism-apis-go-client/v4/client\"\
          \n}\n\nvar (\n    ApiClientInstance *client.ApiClient\n    StorageContainerApiInstance *api.StorageContainerApi\n\
          )\n\nfunc main() {\n    ApiClientInstance = client.NewApiClient()\n    ApiClientInstance.Host = \"localhost\"\n\
          \    ApiClientInstance.Port = 9440\n    ApiClientInstance.RetryInterval = 100\n    ApiClientInstance.MaxRetryAttempts\
          \ = 2\n    ApiClientInstance.AllowVersionNegotiation = true\n    ApiClientInstance.Username = \"username\"\n   \
          \ ApiClientInstance.Password = \"password\"\n\n    StorageContainerApiInstance = api.StorageContainerApi(ApiClientInstance)\n\
          \n    $filter := \"string_sample_data\"\n\n    response, _ := StorageContainerApiInstance.GetDataStores($filter)\n\
          \    fmt.Println(response)\n}\n\n"
      - lang: cURL
        source: "\ncurl --request GET \\\n     --url \"https://{pc-ip}:9440/api/storage/v4.0.a3/config/storage-containers/datastores?$filter=string_sample_data\"\
          \ \\\n     --header 'Accept: application/json' \\\n"
      - lang: Wget
        source: "\nwget --verbose \\\n     --method GET \\\n     --header 'Accept: application/json' \\\n     - \"https://{pc-ip}:9440/api/storage/v4.0.a3/config/storage-containers/datastores?$filter=string_sample_data\"\
          \n"
components:
  schemas:
    common.v1.r0.a3.response.ApiLink:
      type: object
      properties:
        href:
          type: string
          description: 'The URL at which the entity described by this link can be accessed.

            '
        rel:
          type: string
          description: 'A name that identifies the relationship of this link to the object that is returned by the URL.  The
            special value of "self" identifies the URL for the object.

            '
      additionalProperties: false
      description: 'A HATEOAS style link for the response.  Each link contains a user friendly name identifying the link and
        an address for retrieving the particular resource.

        '
    common.v1.r0.a3.response.ExternalizableAbstractModel:
      description: 'A model that represents an object instance that is accessible through an API endpoint.  Instances of this
        type get an extId field that contains the globally unique identifier for that instance.  Externally accessible instances
        are always tenant aware and therefore extend the TenantAwareModel

        '
      allOf:
      - $ref: '#/components/schemas/common.v1.r0.a3.config.TenantAwareModel'
      - type: object
        properties:
          extId:
            pattern: ^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$
            type: string
            description: 'A globally unique identifier of an instance that is suitable for external consumption.

              '
            nullable: true
          links:
            type: array
            description: 'A HATEOAS style link for the response.  Each link contains a user friendly name identifying the
              link and an address for retrieving the particular resource.

              '
            items:
              $ref: '#/components/schemas/common.v1.r0.a3.response.ApiLink'
        additionalProperties: false
    common.v1.r0.a3.config.Flag:
      type: object
      properties:
        name:
          type: string
        value:
          type: boolean
      additionalProperties: false
      description: 'Many entities in the Nutanix APIs carry flags.  This object captures all the flags associated with that
        entity through this object.  The field that hosts this type of an object must have an attribute called x-bounded-map-keys
        that tells which flags are actually present for that entity.

        '
    common.v1.r0.a3.config.MessageSeverity:
      type: string
      description: 'The message severity.

        '
      enum:
      - INFO
      - WARNING
      - ERROR
      - $UNKNOWN
      - $REDACTED
    storage.v4.r0.a3.error.SchemaValidationErrorMessage:
      type: object
      properties:
        location:
          type: string
        message:
          type: string
        attributePath:
          type: string
      additionalProperties: false
      description: This schema is generated from SchemaValidationErrorMessage.java
    common.v1.r0.a3.config.Message:
      type: object
      properties:
        code:
          type: string
          description: 'A code that uniquely identifies a message.

            '
        message:
          type: string
        locale:
          type: string
          description: 'The locale for the message description.

            '
        severity:
          $ref: '#/components/schemas/common.v1.r0.a3.config.MessageSeverity'
      additionalProperties: false
    common.v1.r0.a3.config.TenantAwareModel:
      type: object
      properties:
        tenantId:
          pattern: ^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$
          type: string
          description: 'A globally unique identifier that represents the tenant that owns this entity.  It is automatically
            assigned by the system and is immutable from an API consumer perspective (some use cases may cause this Id to
            change - for instance a use case may require the transfer of ownership of the entity, but these cases are handled
            automatically on the server).

            '
          readOnly: true
      additionalProperties: false
      description: 'A model base class whose instances are bound to a specific tenant.  This model adds a tenantId to the
        base model class that it extends and is automatically set by the server.

        '
    storage.v4.r0.a3.error.SchemaValidationError:
      type: object
      properties:
        timestamp:
          type: string
        statusCode:
          type: integer
        error:
          type: string
        path:
          type: string
        validationErrorMessages:
          type: array
          items:
            $ref: '#/components/schemas/storage.v4.r0.a3.error.SchemaValidationErrorMessage'
      additionalProperties: false
      description: This schema is generated from SchemaValidationError.java
    storage.v4.r0.a3.error.AppMessage:
      type: object
      properties:
        message:
          type: string
        severity:
          $ref: '#/components/schemas/common.v1.r0.a3.config.MessageSeverity'
        code:
          type: string
        locale:
          type: string
          description: The locale for the message description.
        errorGroup:
          type: string
        argumentsMap:
          type: object
          additionalProperties:
            type: string
      additionalProperties: false
      description: This schema is generated from AppMessage.java
    storage.v4.r0.a3.error.ErrorResponse:
      type: object
      properties:
        error:
          oneOf:
          - type: array
            items:
              $ref: '#/components/schemas/storage.v4.r0.a3.error.AppMessage'
          - $ref: '#/components/schemas/storage.v4.r0.a3.error.SchemaValidationError'
      additionalProperties: false
      description: This schema is auto-generated by the Open API Dev Platform as REST response for 4xx and 5xx error responses.
    storage.v4.r0.a3.config.DataStoreResponse:
      type: object
      properties:
        metadata:
          $ref: '#/components/schemas/common.v1.r0.a3.response.ApiResponseMetadata'
        data:
          oneOf:
          - type: array
            items:
              $ref: '#/components/schemas/storage.v4.r0.a3.config.DataStore'
          - type: array
            items:
              $ref: '#/components/schemas/common.v1.r0.a3.config.Message'
          - $ref: '#/components/schemas/storage.v4.r0.a3.error.ErrorResponse'
      additionalProperties: false
      description: REST response for all response codes in api path /storage/v4.0.a3/config/storage-containers/datastores
        Get operation
    storage.v4.r0.a3.config.DataStore:
      allOf:
      - $ref: '#/components/schemas/common.v1.r0.a3.response.ExternalizableAbstractModel'
      - title: Data Store entity.
        type: object
        properties:
          datastoreName:
            maxLength: 255
            type: string
            description: Name of the Data Store.
          containerId:
            type: string
            description: Storage container instance Id.
          containerExtId:
            pattern: ^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$
            type: string
            description: Uuid of the Storage container.
          containerName:
            maxLength: 255
            type: string
            description: Name of the Storage container.
          hostId:
            type: string
            description: Uuid of the host for Data Store.
          hostExtId:
            pattern: ^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$
            type: string
            description: ExtId of the host for Data Store.
          hostIpAddress:
            pattern: '#/components/schemas/common.v1.r0.a3.config.IPAddressOrFQDN'
            type: string
            description: Host IP for Data Store.
          capacity:
            type: integer
            description: Maximum capacity of the Storage container.
            format: int64
          freeSpace:
            type: integer
            description: The free space in the Data Store.
            format: int64
          vmNames:
            type: array
            description: List of VMs name in the Data Store.
            items:
              type: string
        additionalProperties: false
        description: Entity describing all the attributes related to a Data Store instance.
    common.v1.r0.a3.response.ApiResponseMetadata:
      type: object
      properties:
        flags:
          type: array
          items:
            $ref: '#/components/schemas/common.v1.r0.a3.config.Flag'
        links:
          type: array
          items:
            $ref: '#/components/schemas/common.v1.r0.a3.response.ApiLink'
        totalAvailableResults:
          type: integer
          format: int32
        messages:
          type: array
          items:
            $ref: '#/components/schemas/common.v1.r0.a3.config.Message'
        extraInfo:
          type: array
          description: An array of entity specific metadata
          items:
            $ref: '#/components/schemas/common.v1.r0.a3.config.KVPair'
      additionalProperties: false
      description: 'The metadata associated with an API response. Always present and minimally contains the self link for
        the API request that produced this response.  Also contains pagination data for paginated requests.

        '
    common.v1.r0.a3.config.KVPair:
      type: object
      properties:
        name:
          type: string
          description: The key of this key value pair
        value:
          description: The value associated with the key for this key-value pair
          oneOf:
          - type: string
          - type: integer
      additionalProperties: false
      description: 'A map describing a set of keys and their corresponding values.

        '
  securitySchemes:
    basicAuthScheme:
      type: http
      scheme: basic
    apiKeyAuthScheme:
      type: apiKey
      name: X-ntnx-api-key
      in: header
