# GENERATED 1:1 from lifecycle-v4.0.yaml — resource 'Bundle'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-lifecycle-bundle
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-lifecycle-bundle-oas/bundle.yaml
  resourceGroup: lifecycle.nutanix.krateo.io
  resource:
    kind: Bundle
    identifiers:
    - name
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $limit
    - $orderby
    - $page
    - $select
    verbsDescription:
    - action: findby
      method: GET
      path: /lifecycle/v4.0/resources/bundles
    - action: create
      method: POST
      path: /lifecycle/v4.0/resources/bundles
    - action: get
      method: GET
      path: /lifecycle/v4.0/resources/bundles/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /lifecycle/v4.0/resources/bundles/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
