# GENERATED 1:1 from lifecycle-v4.0.yaml — resource 'Entity'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-lifecycle-entity
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-lifecycle-entity-oas/entity.yaml
  resourceGroup: lifecycle.nutanix.krateo.io
  resource:
    kind: Entity
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $limit
    - $orderby
    - $page
    - $select
    verbsDescription:
    - action: findby
      method: GET
      path: /lifecycle/v4.0/resources/entities
    - action: get
      method: GET
      path: /lifecycle/v4.0/resources/entities/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
