# GENERATED 1:1 from lifecycle-v4.0.yaml — resource 'Recommendation'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-lifecycle-recommendation
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-lifecycle-recommendation-oas/recommendation.yaml
  resourceGroup: lifecycle.nutanix.krateo.io
  resource:
    kind: Recommendation
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: get
      method: GET
      path: /lifecycle/v4.0/resources/recommendations/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
