# GENERATED 1:1 from prism-v4.0.yaml — resource 'BackupTarget'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prism-backuptarget
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prism-backuptarget-oas/backuptarget.yaml
  resourceGroup: prism.nutanix.krateo.io
  resource:
    kind: BackupTarget
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /prism/v4.0/management/domain-managers/{domainManagerExtId}/backup-targets
      requestFieldMapping:
      - inPath: domainManagerExtId
        inCustomResource: spec.domainManagerExtId
    - action: create
      method: POST
      path: /prism/v4.0/management/domain-managers/{domainManagerExtId}/backup-targets
      requestFieldMapping:
      - inPath: domainManagerExtId
        inCustomResource: spec.domainManagerExtId
    - action: get
      method: GET
      path: /prism/v4.0/management/domain-managers/{domainManagerExtId}/backup-targets/{extId}
      requestFieldMapping:
      - inPath: domainManagerExtId
        inCustomResource: spec.domainManagerExtId
      - inPath: extId
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /prism/v4.0/management/domain-managers/{domainManagerExtId}/backup-targets/{extId}
      requestFieldMapping:
      - inPath: domainManagerExtId
        inCustomResource: spec.domainManagerExtId
      - inPath: extId
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /prism/v4.0/management/domain-managers/{domainManagerExtId}/backup-targets/{extId}
      requestFieldMapping:
      - inPath: domainManagerExtId
        inCustomResource: spec.domainManagerExtId
      - inPath: extId
        inCustomResource: status.extId
