# GENERATED 1:1 from prism-v4.0.yaml — resource 'Batch'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prism-batch
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prism-batch-oas/batch.yaml
  resourceGroup: prism.nutanix.krateo.io
  resource:
    kind: Batch
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $limit
    - $orderby
    - $page
    - $select
    verbsDescription:
    - action: findby
      method: GET
      path: /prism/v4.0/operations/batches
    - action: get
      method: GET
      path: /prism/v4.0/operations/batches/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
