# GENERATED 1:1 from prism-v4.0.yaml — resource 'Category'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prism-category
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prism-category-oas/category.yaml
  resourceGroup: prism.nutanix.krateo.io
  resource:
    kind: Category
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $expand
    - $filter
    - $limit
    - $orderby
    - $page
    - $select
    verbsDescription:
    - action: findby
      method: GET
      path: /prism/v4.0/config/categories
    - action: create
      method: POST
      path: /prism/v4.0/config/categories
    - action: get
      method: GET
      path: /prism/v4.0/config/categories/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /prism/v4.0/config/categories/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /prism/v4.0/config/categories/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
