# GENERATED 1:1 from prism-v4.0.yaml — resource 'DomainManager'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prism-domainmanager
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prism-domainmanager-oas/domainmanager.yaml
  resourceGroup: prism.nutanix.krateo.io
  resource:
    kind: DomainManager
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $select
    verbsDescription:
    - action: findby
      method: GET
      path: /prism/v4.0/config/domain-managers
    - action: create
      method: POST
      path: /prism/v4.0/config/domain-managers
    - action: get
      method: GET
      path: /prism/v4.0/config/domain-managers/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
