# GENERATED 1:1 from prism-v4.0.yaml — resource 'RestoreSource'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prism-restoresource
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prism-restoresource-oas/restoresource.yaml
  resourceGroup: prism.nutanix.krateo.io
  resource:
    kind: RestoreSource
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /prism/v4.0/management/restore-sources
    - action: get
      method: GET
      path: /prism/v4.0/management/restore-sources/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /prism/v4.0/management/restore-sources/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
