# GENERATED 1:1 from move-v1.yaml — resource 'Action'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-move-action
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-move-action-oas/action.yaml
  resourceGroup: move.nutanix.krateo.io
  resource:
    kind: Action
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /move/v2/plans/workloads/action
