# GENERATED 1:1 from move-v1.yaml — resource 'Addentity'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-move-addentity
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-move-addentity-oas/addentity.yaml
  resourceGroup: move.nutanix.krateo.io
  resource:
    kind: Addentity
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /move/v2/providers/{id}/addentity
      requestFieldMapping:
      - inPath: id
        inCustomResource: spec.id
