# GENERATED 1:1 from move-v1.yaml — resource 'Appliance'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-move-appliance
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-move-appliance-oas/appliance.yaml
  resourceGroup: move.nutanix.krateo.io
  resource:
    kind: Appliance
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /move/v2/configurations/appliance
