# GENERATED 1:1 from move-v1.yaml — resource 'Automatic'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-move-automatic
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-move-automatic-oas/automatic.yaml
  resourceGroup: move.nutanix.krateo.io
  resource:
    kind: Automatic
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /move/v2/upgrade/migrateOs/automatic
