# GENERATED 1:1 from move-v1.yaml — resource 'CheckUpgrade'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-move-checkupgrade
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-move-checkupgrade-oas/checkupgrade.yaml
  resourceGroup: move.nutanix.krateo.io
  resource:
    kind: CheckUpgrade
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - ReCache
    verbsDescription:
    - action: findby
      method: GET
      path: /move/v2/checkUpgrade
