# GENERATED 1:1 from move-v1.yaml — resource 'DownloadFile'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-move-downloadfile
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-move-downloadfile-oas/downloadfile.yaml
  resourceGroup: move.nutanix.krateo.io
  resource:
    kind: DownloadFile
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /move/v2/plans/{id}/workloads/{wid}/iterations/{iterationid}/downloadFiles
      requestFieldMapping:
      - inPath: id
        inCustomResource: spec.id
      - inPath: wid
        inCustomResource: spec.wid
      - inPath: iterationid
        inCustomResource: spec.iterationid
