# GENERATED 1:1 from move-v1.yaml — resource 'Download'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-move-download
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-move-download-oas/download.yaml
  resourceGroup: move.nutanix.krateo.io
  resource:
    kind: Download
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /move/v2/events/download
    - action: create
      method: POST
      path: /move/v2/events/download
