# GENERATED 1:1 from move-v1.yaml — resource 'Getdetail'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-move-getdetail
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-move-getdetail-oas/getdetail.yaml
  resourceGroup: move.nutanix.krateo.io
  resource:
    kind: Getdetail
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - HypervisorType
    verbsDescription:
    - action: findby
      method: GET
      path: /move/v2/plans/{id}/iso/getdetails
      requestFieldMapping:
      - inPath: id
        inCustomResource: spec.id
