# GENERATED 1:1 from move-v1.yaml — resource 'GetUpgradeInfo'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-move-getupgradeinfo
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-move-getupgradeinfo-oas/getupgradeinfo.yaml
  resourceGroup: move.nutanix.krateo.io
  resource:
    kind: GetUpgradeInfo
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /move/v2/upgrade/GetUpgradeInfo
