# GENERATED 1:1 from move-v1.yaml — resource 'Hostname'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-move-hostname
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-move-hostname-oas/hostname.yaml
  resourceGroup: move.nutanix.krateo.io
  resource:
    kind: Hostname
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /move/v2/configurations/appliance/hostname
