# GENERATED 1:1 from move-v1.yaml — resource 'Iamprovider'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-move-iamprovider
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-move-iamprovider-oas/iamprovider.yaml
  resourceGroup: move.nutanix.krateo.io
  resource:
    kind: Iamprovider
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - id
    verbsDescription:
    - action: findby
      method: GET
      path: /move/v2/iamproviders
    - action: create
      method: POST
      path: /move/v2/iamproviders
    - action: get
      method: GET
      path: /move/v2/iamproviders/{id}
      requestFieldMapping:
      - inPath: id
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /move/v2/iamproviders/{id}
      requestFieldMapping:
      - inPath: id
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /move/v2/iamproviders/{id}
      requestFieldMapping:
      - inPath: id
        inCustomResource: status.extId
