# GENERATED 1:1 from move-v1.yaml — resource 'Nodevmorder'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-move-nodevmorder
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-move-nodevmorder-oas/nodevmorder.yaml
  resourceGroup: move.nutanix.krateo.io
  resource:
    kind: Nodevmorder
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /move/v2/plans/{id}/nodevmorder
      requestFieldMapping:
      - inPath: id
        inCustomResource: spec.id
