# GENERATED 1:1 from move-v1.yaml — resource 'PlansList'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-move-planslist
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-move-planslist-oas/planslist.yaml
  resourceGroup: move.nutanix.krateo.io
  resource:
    kind: PlansList
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - IncludeEntityDetails
    - IncludeVMDetails
    verbsDescription:
    - action: create
      method: POST
      path: /move/v2/plans/list
