# GENERATED 1:1 from move-v1.yaml — resource 'Plan'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-move-plan
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-move-plan-oas/plan.yaml
  resourceGroup: move.nutanix.krateo.io
  resource:
    kind: Plan
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - IncludeEntityDetails
    - IncludeVMDetails
    - id
    verbsDescription:
    - action: create
      method: POST
      path: /move/v2/plans
    - action: get
      method: GET
      path: /move/v2/plans/{id}
      requestFieldMapping:
      - inPath: id
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /move/v2/plans/{id}
      requestFieldMapping:
      - inPath: id
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /move/v2/plans/{id}
      requestFieldMapping:
      - inPath: id
        inCustomResource: status.extId
