# GENERATED 1:1 from move-v1.yaml — resource 'PlansList2'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-move-planslist2
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-move-planslist2-oas/planslist2.yaml
  resourceGroup: move.nutanix.krateo.io
  resource:
    kind: PlansList2
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - NumIterations
    verbsDescription:
    - action: create
      method: POST
      path: /move/v2/plans/workloads/list
