# GENERATED 1:1 from move-v1.yaml — resource 'Policy'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-move-policy
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-move-policy-oas/policy.yaml
  resourceGroup: move.nutanix.krateo.io
  resource:
    kind: Policy
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - policyuuid
    verbsDescription:
    - action: create
      method: POST
      path: /move/v2/plans/bwcap/policies
    - action: get
      method: GET
      path: /move/v2/plans/bwcap/policies/{policyuuid}
      requestFieldMapping:
      - inPath: policyuuid
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /move/v2/plans/bwcap/policies/{policyuuid}
      requestFieldMapping:
      - inPath: policyuuid
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /move/v2/plans/bwcap/policies/{policyuuid}
      requestFieldMapping:
      - inPath: policyuuid
        inCustomResource: status.extId
