# GENERATED 1:1 from move-v1.yaml — resource 'Prepare'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-move-prepare
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-move-prepare-oas/prepare.yaml
  resourceGroup: move.nutanix.krateo.io
  resource:
    kind: Prepare
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - InstallNGT
    - SkipIPRetention
    - UninstallGuestTools
    verbsDescription:
    - action: findby
      method: GET
      path: /move/v2/plans/{id}/prepare
      requestFieldMapping:
      - inPath: id
        inCustomResource: spec.id
    - action: create
      method: POST
      path: /move/v2/plans/{id}/prepare
      requestFieldMapping:
      - inPath: id
        inCustomResource: spec.id
