# GENERATED 1:1 from move-v1.yaml — resource 'ProvidersList2'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-move-providerslist2
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-move-providerslist2-oas/providerslist2.yaml
  resourceGroup: move.nutanix.krateo.io
  resource:
    kind: ProvidersList2
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - targetSpProvider
    verbsDescription:
    - action: create
      method: POST
      path: /move/v2/providers/{id}/workloads/list
      requestFieldMapping:
      - inPath: id
        inCustomResource: spec.id
