# GENERATED 1:1 from move-v1.yaml — resource 'Refresh'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-move-refresh
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-move-refresh-oas/refresh.yaml
  resourceGroup: move.nutanix.krateo.io
  resource:
    kind: Refresh
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /move/v2/plans/{id}/workloads/{wid}/refresh
      requestFieldMapping:
      - inPath: id
        inCustomResource: spec.id
      - inPath: wid
        inCustomResource: spec.wid
