# GENERATED 1:1 from move-v1.yaml — resource 'Report'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-move-report
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-move-report-oas/report.yaml
  resourceGroup: move.nutanix.krateo.io
  resource:
    kind: Report
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /move/v2/plans/reports
