# GENERATED 1:1 from move-v1.yaml — resource 'Resume'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-move-resume
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-move-resume-oas/resume.yaml
  resourceGroup: move.nutanix.krateo.io
  resource:
    kind: Resume
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /move/v2/plans/{id}/resume
      requestFieldMapping:
      - inPath: id
        inCustomResource: spec.id
