# GENERATED 1:1 from move-v1.yaml — resource 'Runbook'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-move-runbook
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-move-runbook-oas/runbook.yaml
  resourceGroup: move.nutanix.krateo.io
  resource:
    kind: Runbook
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - runbookid
    verbsDescription:
    - action: get
      method: GET
      path: /move/v2/providers/{id}/runbooks/{runbookid}
      requestFieldMapping:
      - inPath: id
        inCustomResource: spec.id
      - inPath: runbookid
        inCustomResource: status.extId
