# GENERATED 1:1 from move-v1.yaml — resource 'Service'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-move-service
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-move-service-oas/service.yaml
  resourceGroup: move.nutanix.krateo.io
  resource:
    kind: Service
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - svc
    - svcgrp
    verbsDescription:
    - action: findby
      method: GET
      path: /move/v2/configurations/appliance/services
