# GENERATED 1:1 from move-v1.yaml — resource 'Start'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-move-start
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-move-start-oas/start.yaml
  resourceGroup: move.nutanix.krateo.io
  resource:
    kind: Start
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /move/v2/plans/{id}/start
      requestFieldMapping:
      - inPath: id
        inCustomResource: spec.id
