# GENERATED 1:1 from move-v1.yaml — resource 'Statu'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-move-statu
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-move-statu-oas/statu.yaml
  resourceGroup: move.nutanix.krateo.io
  resource:
    kind: Statu
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /move/v2/events/download/status
