# GENERATED 1:1 from move-v1.yaml — resource 'SupportbundleStatu'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-move-supportbundlestatu
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-move-supportbundlestatu-oas/supportbundlestatu.yaml
  resourceGroup: move.nutanix.krateo.io
  resource:
    kind: SupportbundleStatu
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /move/v2/supportbundle/status
