# GENERATED 1:1 from move-v1.yaml — resource 'Task'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-move-task
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-move-task-oas/task.yaml
  resourceGroup: move.nutanix.krateo.io
  resource:
    kind: Task
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - IncludeChildTasks
    - id
    verbsDescription:
    - action: get
      method: GET
      path: /move/v2/tasks/{id}
      requestFieldMapping:
      - inPath: id
        inCustomResource: status.extId
