# GENERATED 1:1 from move-v1.yaml — resource 'Token2'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-move-token2
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-move-token2-oas/token2.yaml
  resourceGroup: move.nutanix.krateo.io
  resource:
    kind: Token2
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /move/v2/token
