# GENERATED 1:1 from move-v1.yaml — resource 'TranslatedsecuritypolicyRemove2'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-move-translatedsecuritypolicyremove2
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-move-translatedsecuritypolicyremove2-oas/translatedsecuritypolicyremove2.yaml
  resourceGroup: move.nutanix.krateo.io
  resource:
    kind: TranslatedsecuritypolicyRemove2
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /move/v2/translatedsecuritypolicy/inventory/remove
