# GENERATED 1:1 from move-v1.yaml — resource 'Upgrade'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-move-upgrade
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-move-upgrade-oas/upgrade.yaml
  resourceGroup: move.nutanix.krateo.io
  resource:
    kind: Upgrade
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /move/v2/upgrade
    - action: create
      method: POST
      path: /move/v2/upgrade
