# GENERATED 1:1 from move-v1.yaml — resource 'Upload'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-move-upload
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-move-upload-oas/upload.yaml
  resourceGroup: move.nutanix.krateo.io
  resource:
    kind: Upload
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /move/v2/plans/{id}/iso/upload
      requestFieldMapping:
      - inPath: id
        inCustomResource: spec.id
