# GENERATED 1:1 from move-v1.yaml — resource 'UploadUpgradeFile'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-move-uploadupgradefile
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-move-uploadupgradefile-oas/uploadupgradefile.yaml
  resourceGroup: move.nutanix.krateo.io
  resource:
    kind: UploadUpgradeFile
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /move/v2/uploadUpgradeFiles
    - action: create
      method: POST
      path: /move/v2/uploadUpgradeFiles
