# GENERATED 1:1 from move-v1.yaml — resource 'View'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-move-view
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-move-view-oas/view.yaml
  resourceGroup: move.nutanix.krateo.io
  resource:
    kind: View
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /move/v2/iamproviders/view
