# GENERATED 1:1 from files-v4.0.yaml — resource 'InfectedFile'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-files-infectedfile
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-files-infectedfile-oas/infectedfile.yaml
  resourceGroup: files.nutanix.krateo.io
  resource:
    kind: InfectedFile
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $limit
    - $orderby
    - $page
    - $select
    verbsDescription:
    - action: findby
      method: GET
      path: /files/v4.0/config/file-servers/{fileServerExtId}/infected-files
      requestFieldMapping:
      - inPath: fileServerExtId
        inCustomResource: spec.fileServerExtId
    - action: get
      method: GET
      path: /files/v4.0/config/file-servers/{fileServerExtId}/infected-files/{extId}
      requestFieldMapping:
      - inPath: fileServerExtId
        inCustomResource: spec.fileServerExtId
      - inPath: extId
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /files/v4.0/config/file-servers/{fileServerExtId}/infected-files/{extId}
      requestFieldMapping:
      - inPath: fileServerExtId
        inCustomResource: spec.fileServerExtId
      - inPath: extId
        inCustomResource: status.extId
