# GENERATED 1:1 from files-v4.0.yaml — resource 'RansomwareConfig'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-files-ransomwareconfig
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-files-ransomwareconfig-oas/ransomwareconfig.yaml
  resourceGroup: files.nutanix.krateo.io
  resource:
    kind: RansomwareConfig
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $limit
    - $page
    - $select
    verbsDescription:
    - action: findby
      method: GET
      path: /files/v4.0/config/file-servers/{fileServerExtId}/ransomware-configs
      requestFieldMapping:
      - inPath: fileServerExtId
        inCustomResource: spec.fileServerExtId
    - action: create
      method: POST
      path: /files/v4.0/config/file-servers/{fileServerExtId}/ransomware-configs
      requestFieldMapping:
      - inPath: fileServerExtId
        inCustomResource: spec.fileServerExtId
    - action: get
      method: GET
      path: /files/v4.0/config/file-servers/{fileServerExtId}/ransomware-configs/{extId}
      requestFieldMapping:
      - inPath: fileServerExtId
        inCustomResource: spec.fileServerExtId
      - inPath: extId
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /files/v4.0/config/file-servers/{fileServerExtId}/ransomware-configs/{extId}
      requestFieldMapping:
      - inPath: fileServerExtId
        inCustomResource: spec.fileServerExtId
      - inPath: extId
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /files/v4.0/config/file-servers/{fileServerExtId}/ransomware-configs/{extId}
      requestFieldMapping:
      - inPath: fileServerExtId
        inCustomResource: spec.fileServerExtId
      - inPath: extId
        inCustomResource: status.extId
