# GENERATED 1:1 from files-v4.0.yaml — resource 'ReplicationJob'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-files-replicationjob
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-files-replicationjob-oas/replicationjob.yaml
  resourceGroup: files.nutanix.krateo.io
  resource:
    kind: ReplicationJob
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $limit
    - $orderby
    - $page
    - $select
    verbsDescription:
    - action: findby
      method: GET
      path: /files/v4.0/operations/replication-jobs
    - action: get
      method: GET
      path: /files/v4.0/operations/replication-jobs/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
