# GENERATED 1:1 from files-v4.0.yaml — resource 'ReplicationPolicy'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-files-replicationpolicy
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-files-replicationpolicy-oas/replicationpolicy.yaml
  resourceGroup: files.nutanix.krateo.io
  resource:
    kind: ReplicationPolicy
    identifiers:
    - name
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $dryrun
    - $filter
    - $limit
    - $orderby
    - $page
    - $select
    verbsDescription:
    - action: findby
      method: GET
      path: /files/v4.0/config/replication-policies
    - action: create
      method: POST
      path: /files/v4.0/config/replication-policies
    - action: get
      method: GET
      path: /files/v4.0/config/replication-policies/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /files/v4.0/config/replication-policies/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /files/v4.0/config/replication-policies/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
