# GENERATED 1:1 from files-v4.0.yaml — resource 'Snapshot'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-files-snapshot
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-files-snapshot-oas/snapshot.yaml
  resourceGroup: files.nutanix.krateo.io
  resource:
    kind: Snapshot
    identifiers:
    - name
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $limit
    - $orderby
    - $page
    - $select
    verbsDescription:
    - action: findby
      method: GET
      path: /files/v4.0/config/file-servers/{fileServerExtId}/mount-targets/{mountTargetExtId}/snapshots
      requestFieldMapping:
      - inPath: fileServerExtId
        inCustomResource: spec.fileServerExtId
      - inPath: mountTargetExtId
        inCustomResource: spec.mountTargetExtId
    - action: create
      method: POST
      path: /files/v4.0/config/file-servers/{fileServerExtId}/mount-targets/{mountTargetExtId}/snapshots
      requestFieldMapping:
      - inPath: fileServerExtId
        inCustomResource: spec.fileServerExtId
      - inPath: mountTargetExtId
        inCustomResource: spec.mountTargetExtId
    - action: get
      method: GET
      path: /files/v4.0/config/file-servers/{fileServerExtId}/mount-targets/{mountTargetExtId}/snapshots/{extId}
      requestFieldMapping:
      - inPath: fileServerExtId
        inCustomResource: spec.fileServerExtId
      - inPath: mountTargetExtId
        inCustomResource: spec.mountTargetExtId
      - inPath: extId
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /files/v4.0/config/file-servers/{fileServerExtId}/mount-targets/{mountTargetExtId}/snapshots/{extId}
      requestFieldMapping:
      - inPath: fileServerExtId
        inCustomResource: spec.fileServerExtId
      - inPath: mountTargetExtId
        inCustomResource: spec.mountTargetExtId
      - inPath: extId
        inCustomResource: status.extId
