# GENERATED 1:1 from files-v4.0.yaml — resource 'SnapshotChangedContent'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-files-snapshotchangedcontent
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-files-snapshotchangedcontent-oas/snapshotchangedcontent.yaml
  resourceGroup: files.nutanix.krateo.io
  resource:
    kind: SnapshotChangedContent
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $limit
    - $orderby
    - $page
    - $select
    verbsDescription:
    - action: findby
      method: GET
      path: /files/v4.0/config/file-servers/{fileServerExtId}/mount-targets/{mountTargetExtId}/snapshot-changed-contents
      requestFieldMapping:
      - inPath: fileServerExtId
        inCustomResource: spec.fileServerExtId
      - inPath: mountTargetExtId
        inCustomResource: spec.mountTargetExtId
    - action: get
      method: GET
      path: /files/v4.0/config/file-servers/{fileServerExtId}/mount-targets/{mountTargetExtId}/snapshot-changed-contents/{extId}
      requestFieldMapping:
      - inPath: fileServerExtId
        inCustomResource: spec.fileServerExtId
      - inPath: mountTargetExtId
        inCustomResource: spec.mountTargetExtId
      - inPath: extId
        inCustomResource: status.extId
