# GENERATED 1:1 from files-v4.0.yaml — resource 'UserMapping'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-files-usermapping
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-files-usermapping-oas/usermapping.yaml
  resourceGroup: files.nutanix.krateo.io
  resource:
    kind: UserMapping
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /files/v4.0/config/file-servers/{fileServerExtId}/user-mappings
      requestFieldMapping:
      - inPath: fileServerExtId
        inCustomResource: spec.fileServerExtId
