openapi: 3.0.0
info:
  title: NCM Self-Service
  description: "# Introduction \n**NCM Self-Service** allows you to seamlessly select, provision, and manage your business\
    \ applications across infrastructures for both, private and public clouds.\n\nSelf-Service provides application lifecycle,\
    \ monitoring, and remediation to manage heterogeneous infrastructure. For example, VMs or bare-metal servers. Self-Service\
    \ supports multiple platforms through its single self-service and automation interface to manage all your infrastructure.\n\
    \n# Authentication\n- **Basic Authentication** : The user provides user ID and password every time a request is sent as\
    \ the auth-header.\n\n- **Session Authentication** : The user credentials are stored in a cookie. \n\n"
  version: 3.1.0
servers:
- url: https://pc-host-ip:9440/api/nutanix/v3
security:
- basicAuth: []
paths:
  /gcp/v1/accounts/{account_uuid}/zone/{zone_name}/instances/{uuid}:
    get:
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                additionalProperties: true
        '404':
          description: Internal Error
          content:
            application/json:
              schema:
                additionalProperties: true
      parameters:
      - name: uuid
        required: true
        in: path
        description: uuid of gcp instance
        schema:
          type: string
          format: UUID
          pattern: ^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$
      - name: account_uuid
        required: true
        in: path
        description: uuid of account
        schema:
          type: string
          format: UUID
          pattern: ^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$
      - required: true
        description: zone name for gcp account
        in: path
        name: zone_name
        schema:
          type: string
      tags:
      - gcp/instances
      x-private: true
      x-doc-hide: true
      summary: Get gcp vm
      x-ntnx-operations:
      - view
      x-ntnx-kind: gcp_instance
      description: Given a UUID, returns a gcp vm
      x-codeSamples:
      - lang: cURL
        source: "curl --request GET \\\n    --url https://pc-host-ip:9440/api/nutanix/v3/gcp/v1/accounts/{account_uuid}/zone/{zone_name}/instances/{uuid}\
          \ \\\n    --header 'Accept: application/json' \\\n    --header 'Authorization: Basic <basic_auth_token>' \\\n  \
          \   "
      - lang: Wget
        source: "wget --quiet \\\n    --method GET \\\n    --header 'Accept: application/json' \\\n    --header 'Authorization:\
          \ Basic <basic_auth_token>' \\\n      \\\n    --output-document \\\n    - https://pc-host-ip:9440/api/nutanix/v3/gcp/v1/accounts/{account_uuid}/zone/{zone_name}/instances/{uuid}"
      - lang: Python
        source: "import http.client\n\nconn = http.client.HTTPSConnection(\"pc-host-ip:9440\")\n\nheaders = {\n    \"Accept\"\
          : \"application/json\",\n    \"Authorization\": \"Basic <basic_auth_token>\"\n}\n \nconn.request(\"GET\",\"/api/nutanix/v3/gcp/v1/accounts/{account_uuid}/zone/{zone_name}/instances/{uuid}\"\
          , headers=headers)\n\nres = conn.getresponse()\ndata = res.read()\n\nprint(data.decode(\"utf-8\"))"
      - lang: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl\
          \ := \"https://pc-host-ip:9440/api/nutanix/v3/gcp/v1/accounts/{account_uuid}/zone/{zone_name}/instances/{uuid}\"\
          \n\t \n\treq, err := http.NewRequest(\"GET\", url, nil)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating request:\"\
          , err)\n\t\treturn\n\t}\n\n        req.Header.Add(\"Accept\", \"application/json\")\n        req.Header.Add(\"Authorization\"\
          , \"Basic <basic_auth_token>\")\n    \n\tres, err := http.DefaultClient.Do(req)\n\tif err != nil {\n\t\tfmt.Println(\"\
          Error creating request:\", err)\n\t\treturn\n\t}\n\n\tdefer res.Body.Close()\n\tbody, err := io.ReadAll(res.Body)\n\
          \tif err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n\tfmt.Println(res)\n\t\
          fmt.Println(string(body))\n\n}"
      - lang: Java
        source: "AsyncHttpClient client = new DefaultAsyncHttpClient();\nclient.prepare(\"GET\", \"https://pc-host-ip:9440/api/nutanix/v3/gcp/v1/accounts/{account_uuid}/zone/{zone_name}/instances/{uuid}\"\
          )\n  .setHeader(\"Accept\", \"application/json\")\n  .setHeader(\"Authorization\", \"Basic <basic_auth_token>\"\
          )\n  .execute()\n  .toCompletableFuture()\n  .thenAccept(System.out::println)\n  .join();\n\nclient.close();"
      - lang: JavaScript
        source: "const url = 'https://pc-host-ip:9440/api/nutanix/v3/gcp/v1/accounts/{account_uuid}/zone/{zone_name}/instances/{uuid}';\n\
          const options = {\n  method: 'GET',\n  headers: {'Accept': 'application/json', 'Authorization': 'Basic <basic_auth_token>'}\
          \ \n};\n\ntry {\n  const response = await fetch(url, options);\n  const data = await response.json();\n  console.log(data);\n\
          } catch (error) {\n  console.error(error);\n}"
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
