openapi: 3.0.0
info:
  title: NCM Self-Service
  description: "# Introduction \n**NCM Self-Service** allows you to seamlessly select, provision, and manage your business\
    \ applications across infrastructures for both, private and public clouds.\n\nSelf-Service provides application lifecycle,\
    \ monitoring, and remediation to manage heterogeneous infrastructure. For example, VMs or bare-metal servers. Self-Service\
    \ supports multiple platforms through its single self-service and automation interface to manage all your infrastructure.\n\
    \n# Authentication\n- **Basic Authentication** : The user provides user ID and password every time a request is sent as\
    \ the auth-header.\n\n- **Session Authentication** : The user credentials are stored in a cookie. \n\n"
  version: 3.1.0
servers:
- url: https://pc-host-ip:9440/api/nutanix/v3
security:
- basicAuth: []
paths:
  /azure_rm/v1/storage_accounts/list:
    post:
      description: 'Retrieves the list of all storage_accounts available. Supported filters are:

        - account_uuid

        - location

        '
      requestBody:
        $ref: '#/components/requestBodies/arm_list_metadata'
      tags:
      - azure_rm/storage_accounts
      x-private: true
      x-doc-hide: true
      summary: List Azure storage_accounts
      x-ntnx-operations:
      - view
      x-ntnx-kind: azure_rm_storage_account
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                additionalProperties: true
        '404':
          description: Entity not found
          content:
            application/json:
              schema:
                additionalProperties: true
      x-codeSamples:
      - lang: cURL
        source: "curl --request POST \\\n    --url https://pc-host-ip:9440/api/nutanix/v3/azure_rm/v1/storage_accounts/list\
          \ \\\n    --header 'Accept: application/json' \\\n    --header 'Authorization: Basic <basic_auth_token>' \\\n  \
          \  --header 'Content-Type: application/json' \\\n    --data '{\n    \"filter\": \"string\",\n    \"length\": 1,\n\
          \    \"offset\": 0\n}'"
      - lang: Wget
        source: "wget --quiet \\\n    --method POST \\\n    --header 'Accept: application/json' \\\n    --header 'Authorization:\
          \ Basic <basic_auth_token>' \\\n    --header 'Content-Type: application/json' \\\n    --body-data '{\n    \"filter\"\
          : \"string\",\n    \"length\": 1,\n    \"offset\": 0\n}' \\\n    --output-document \\\n    - https://pc-host-ip:9440/api/nutanix/v3/azure_rm/v1/storage_accounts/list"
      - lang: Python
        source: "import http.client\n\nconn = http.client.HTTPSConnection(\"pc-host-ip:9440\")\n\nheaders = {\n    \"Accept\"\
          : \"application/json\",\n    \"Authorization\": \"Basic <basic_auth_token>\",\n    \"Content-Type\": \"application/json\"\
          \n}\n\npayload =  \"\"\"{\n    \"filter\": \"string\",\n    \"length\": 1,\n    \"offset\": 0\n}\"\"\"\n\nconn.request(\"\
          POST\",\"/api/nutanix/v3/azure_rm/v1/storage_accounts/list\", payload, headers)\n\nres = conn.getresponse()\ndata\
          \ = res.read()\n\nprint(data.decode(\"utf-8\"))"
      - lang: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl\
          \ := \"https://pc-host-ip:9440/api/nutanix/v3/azure_rm/v1/storage_accounts/list\"\n\t\n\tpayload :=  strings.NewReader(`{\"\
          filter\": \"string\", \"length\": 1, \"offset\": 0}`)\n\treq, err := http.NewRequest(\"POST\", url, payload)\n\t\
          if err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n        req.Header.Add(\"\
          Accept\", \"application/json\")\n        req.Header.Add(\"Authorization\", \"Basic <basic_auth_token>\")\n     \
          \   req.Header.Add(\"Content-Type\", \"application/json\")\n    \n\tres, err := http.DefaultClient.Do(req)\n\tif\
          \ err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n\tdefer res.Body.Close()\n\
          \tbody, err := io.ReadAll(res.Body)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\t\
          return\n\t}\n\n\tfmt.Println(res)\n\tfmt.Println(string(body))\n\n}"
      - lang: Java
        source: "AsyncHttpClient client = new DefaultAsyncHttpClient();\nclient.prepare(\"POST\", \"https://pc-host-ip:9440/api/nutanix/v3/azure_rm/v1/storage_accounts/list\"\
          )\n  .setHeader(\"Accept\", \"application/json\")\n  .setHeader(\"Authorization\", \"Basic <basic_auth_token>\"\
          )\n  .setHeader(\"Content-Type\", \"application/json\")\n  .setBody(\"{\\\"filter\\\": \\\"string\\\", \\\"length\\\
          \": 1, \\\"offset\\\": 0}\")\n  .execute()\n  .toCompletableFuture()\n  .thenAccept(System.out::println)\n  .join();\n\
          \nclient.close();"
      - lang: JavaScript
        source: "const url = 'https://pc-host-ip:9440/api/nutanix/v3/azure_rm/v1/storage_accounts/list';\nconst options =\
          \ {\n  method: 'POST',\n  headers: {'Accept': 'application/json', 'Authorization': 'Basic <basic_auth_token>', 'Content-Type':\
          \ 'application/json'},\n  body:  `{\"filter\": \"string\", \"length\": 1, \"offset\": 0}`\n};\n\ntry {\n  const\
          \ response = await fetch(url, options);\n  const data = await response.json();\n  console.log(data);\n} catch (error)\
          \ {\n  console.error(error);\n}"
components:
  requestBodies:
    arm_list_metadata:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/arm_list_metadata'
      description: Request body
      required: true
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    arm_list_metadata:
      description: All arm list calls will have this metadata block as input
      type: object
      properties:
        filter:
          type: string
          description: The filter in FIQL syntax used for the results.
        length:
          minimum: 1
          type: integer
          description: The number of records to retrieve relative to the offset
          format: int32
        offset:
          minimum: 0
          type: integer
          description: Offset from the start of the entity list
          format: int32
      title: Metadata for arm list calls
