# GENERATED 1:1 from foundation-v1.yaml — resource 'AbortSession'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-foundation-abortsession
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-foundation-abortsession-oas/abortsession.yaml
  resourceGroup: foundation.nutanix.krateo.io
  resource:
    kind: AbortSession
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - session_id
    verbsDescription:
    - action: findby
      method: GET
      path: /abort_session
