# GENERATED 1:1 from foundation-v1.yaml — resource 'AosPackage'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-foundation-aospackage
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-foundation-aospackage-oas/aospackage.yaml
  resourceGroup: foundation.nutanix.krateo.io
  resource:
    kind: AosPackage
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - aos_package_name
    verbsDescription:
    - action: findby
      method: GET
      path: /aos_packages
