# GENERATED 1:1 from foundation-v1.yaml — resource 'AvailableUpdate'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-foundation-availableupdate
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-foundation-availableupdate-oas/availableupdate.yaml
  resourceGroup: foundation.nutanix.krateo.io
  resource:
    kind: AvailableUpdate
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - components
    verbsDescription:
    - action: findby
      method: GET
      path: /components/available_updates
