# GENERATED 1:1 from foundation-v1.yaml — resource 'Delete'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-foundation-delete
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-foundation-delete-oas/delete.yaml
  resourceGroup: foundation.nutanix.krateo.io
  resource:
    kind: Delete
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /delete
