# GENERATED 1:1 from foundation-v1.yaml — resource 'FoundationNetworking'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-foundation-foundationnetworking
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-foundation-foundationnetworking-oas/foundationnetworking.yaml
  resourceGroup: foundation.nutanix.krateo.io
  resource:
    kind: FoundationNetworking
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /foundation_networking
    - action: create
      method: POST
      path: /foundation_networking
