# GENERATED 1:1 from foundation-v1.yaml — resource 'GetUpdateLog'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-foundation-getupdatelog
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-foundation-getupdatelog-oas/getupdatelog.yaml
  resourceGroup: foundation.nutanix.krateo.io
  resource:
    kind: GetUpdateLog
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /get_update_log
