# GENERATED 1:1 from foundation-v1.yaml — resource 'Hcl'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-foundation-hcl
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-foundation-hcl-oas/hcl.yaml
  resourceGroup: foundation.nutanix.krateo.io
  resource:
    kind: Hcl
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /hcl
    - action: create
      method: POST
      path: /hcl
