# GENERATED 1:1 from foundation-v1.yaml — resource 'InstallProgress'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-foundation-installprogress
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-foundation-installprogress-oas/installprogress.yaml
  resourceGroup: foundation.nutanix.krateo.io
  resource:
    kind: InstallProgress
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /components/install_progress
