# GENERATED 1:1 from foundation-v1.yaml — resource 'IsIsoSupported'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-foundation-isisosupported
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-foundation-isisosupported-oas/isisosupported.yaml
  resourceGroup: foundation.nutanix.krateo.io
  resource:
    kind: IsIsoSupported
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /is_iso_supported
