# GENERATED 1:1 from foundation-v1.yaml — resource 'LogArchiveTar'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-foundation-logarchivetar
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-foundation-logarchivetar-oas/logarchivetar.yaml
  resourceGroup: foundation.nutanix.krateo.io
  resource:
    kind: LogArchiveTar
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - session_id
    verbsDescription:
    - action: findby
      method: GET
      path: /log_archive_tar
