# GENERATED 1:1 from foundation-v1.yaml — resource 'PrimaryNic'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-foundation-primarynic
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-foundation-primarynic-oas/primarynic.yaml
  resourceGroup: foundation.nutanix.krateo.io
  resource:
    kind: PrimaryNic
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /primary_nic
    - action: create
      method: POST
      path: /primary_nic
