# GENERATED 1:1 from foundation-v1.yaml — resource 'ProvisionNetwork'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-foundation-provisionnetwork
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-foundation-provisionnetwork-oas/provisionnetwork.yaml
  resourceGroup: foundation.nutanix.krateo.io
  resource:
    kind: ProvisionNetwork
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /provision_network
