# GENERATED 1:1 from foundation-v1.yaml — resource 'ServiceLog'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-foundation-servicelog
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-foundation-servicelog-oas/servicelog.yaml
  resourceGroup: foundation.nutanix.krateo.io
  resource:
    kind: ServiceLog
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /service_log
