openapi: 3.0.1
info:
  title: Nutanix Virtual Machine Management APIs
  description: Manage the life-cycle of virtual machines hosted on Nutanix
  version: '4.0'
  x-logo:
    altText: Vmm Logo
    url: https://developers.nutanix.com/api/v1/namespaces/vmm/images/vmm-logo-img.svg
  x-repo-name: vmm
servers:
- url: https://{pc-ip}:9440/api
security:
- basicAuthScheme: []
- apiKeyAuthScheme: []
paths:
  /vmm/v4.0/content/images/{imageExtId}/file:
    get:
      tags:
      - Images
      summary: Download an image
      description: Downloads the image with the given external identifier.
      operationId: getFileByImageId
      parameters:
      - name: imageExtId
        in: path
        description: The external identifier of an image.
        required: true
        style: simple
        explode: false
        schema:
          pattern: ^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$
          type: string
          example: c8ce8c92-fe88-401f-a6ae-fa25e106b11e
      responses:
        '302':
          description: Returns the requested image file.
          headers:
            Location:
              description: The redirect download URL for the image.
              style: simple
              explode: false
              schema:
                pattern: ^((http[s]?|nfs):\/)?\/?([^:\/\s]*)((\/\w+)*(:[0-9]+)*?\/)([\w\-\.]+[^#?\s]+)(.*)?(#[\w\-]+)?$
                type: string
            X-Redirect-Token:
              description: The cookie to be used along with the redirect download URL for downloading the image.
              style: simple
              explode: false
              schema:
                type: string
              example: NTNX_IGW_SESSION=eyJmb28iOiJiYXIifQ
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        4XX:
          description: Client error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  metadata:
                    $ref: '#/components/schemas/common.v1.0.response.ApiResponseMetadata'
                  data:
                    $ref: '#/components/schemas/vmm.v4.0.error.ErrorResponse'
                additionalProperties: false
                description: REST response for all response codes in API path /vmm/v4.0/content/images/{imageExtId}/file Get
                  operation
        5XX:
          description: Server error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  metadata:
                    $ref: '#/components/schemas/common.v1.0.response.ApiResponseMetadata'
                  data:
                    $ref: '#/components/schemas/vmm.v4.0.error.ErrorResponse'
                additionalProperties: false
                description: REST response for all response codes in API path /vmm/v4.0/content/images/{imageExtId}/file Get
                  operation
      x-permissions:
        deploymentList:
        - ON_PREM
        - CLOUD
        operationName: Download Image
        roleList:
        - Super Admin
        - Prism Admin
        - Prism Viewer
      x-rate-limit:
      - type: xsmall
        count: 3
        timeUnit: seconds
      - type: Small
        count: 3
        timeUnit: seconds
      - type: Large
        count: 3
        timeUnit: seconds
      - type: XLarge
        count: 3
        timeUnit: seconds
      x-supported-versions:
      - product: PC
        version: '2024.3'
      - product: PE
        version: '7.0'
components:
  schemas:
    common.v1.0.config.MapOfStringWrapper:
      type: object
      properties:
        map:
          type: object
          additionalProperties:
            type: string
          description: 'A map with string keys and values.

            '
      additionalProperties: false
      description: 'A wrapper schema containing a map with string keys and values.

        '
    common.v1.0.config.MessageSeverity:
      type: string
      description: 'The message severity.

        '
      enum:
      - INFO
      - WARNING
      - ERROR
      - $UNKNOWN
      - $REDACTED
      x-enumDescriptions:
        ERROR: 'Error indicating failed completion.

          '
        INFO: 'Information about successful completion.

          '
        $UNKNOWN: 'Unknown value.

          '
        WARNING: 'Warning indicating future error.

          '
        $REDACTED: 'Redacted value.

          '
    vmm.v4.0.error.SchemaValidationErrorMessage:
      type: object
      properties:
        location:
          type: string
          description: The part of the request that failed validation. Validation can fail for path, query parameters, and
            request body.
        message:
          type: string
          description: The detailed message for the validation error.
        attributePath:
          type: string
          description: The path of the attribute that failed validation in the schema.
      additionalProperties: false
      description: This schema is generated from SchemaValidationErrorMessage.java
      x-platform-generated: true
    common.v1.0.config.Message:
      type: object
      properties:
        code:
          type: string
          description: 'A code that uniquely identifies a message.

            '
        message:
          type: string
          description: 'The description of the message.

            '
        locale:
          type: string
          description: 'The locale for the message description.

            '
          default: en_US
        severity:
          $ref: '#/components/schemas/common.v1.0.config.MessageSeverity'
      additionalProperties: false
    vmm.v4.0.error.AppMessage:
      type: object
      properties:
        message:
          type: string
          description: The message string.
        severity:
          $ref: '#/components/schemas/common.v1.0.config.MessageSeverity'
        code:
          type: string
          description: 'The code associated with this message.This string is typically prefixed by the namespace the endpoint
            belongs to. For example: VMM-40000'
        locale:
          type: string
          description: Locale for this message. The default locale would be 'en-US'.
          default: en_US
        errorGroup:
          type: string
          description: The error group associated with this message of severity ERROR.
        argumentsMap:
          type: object
          additionalProperties:
            type: string
          description: The map of argument name to value.
      additionalProperties: false
      description: Message with associated severity describing status of the current operation.
      x-platform-generated: true
    common.v1.0.config.Flag:
      type: object
      properties:
        name:
          maxLength: 128
          minLength: 3
          type: string
          description: 'Name of the flag.

            '
        value:
          type: boolean
          description: 'Value of the flag.

            '
          default: false
      additionalProperties: false
      description: 'Many entities in the Nutanix APIs carry flags.  This object captures all the flags associated with that
        entity through this object.  The field that hosts this type of object must have an attribute called x-bounded-map-keys
        that tells which flags are actually present for that entity.

        '
    vmm.v4.0.error.SchemaValidationError:
      type: object
      properties:
        timestamp:
          type: string
          description: Timestamp of the response.
          format: date-time
          example: 2009-09-23 14:30:00-07:00
        statusCode:
          type: integer
          description: The HTTP status code of the response.
          example: 24
        error:
          type: string
          description: The generic error message for the response.
        path:
          type: string
          description: API path on which the request was made.
        validationErrorMessages:
          type: array
          description: List of validation error messages
          items:
            $ref: '#/components/schemas/vmm.v4.0.error.SchemaValidationErrorMessage'
      additionalProperties: false
      description: This schema is generated from SchemaValidationError.java
      x-platform-generated: true
    common.v1.0.response.ApiLink:
      type: object
      properties:
        href:
          type: string
          description: 'The URL at which the entity described by the link can be accessed.

            '
        rel:
          type: string
          description: 'A name that identifies the relationship of the link to the object that is returned by the URL.  The
            unique value of "self" identifies the URL for the object.

            '
      additionalProperties: false
      description: 'A HATEOAS style link for the response.  Each link contains a user-friendly name identifying the link and
        an address for retrieving the particular resource.

        '
    common.v1.0.config.KVPair:
      type: object
      properties:
        name:
          maxLength: 128
          minLength: 3
          type: string
          description: 'The key of the key-value pair.

            '
        value:
          description: The value associated with the key for this key-value pair
          oneOf:
          - type: string
            description: 'A string value in a key-value pair.

              '
          - type: integer
            description: 'An integer value in a key-value pair.

              '
            example: 31
          - type: boolean
            description: 'An boolean value in a key-value pair.

              '
            example: false
          - maxItems: 100
            minItems: 0
            type: array
            description: 'A value in a key-value pair that represents a list of strings.

              '
            items:
              type: string
          - type: object
            additionalProperties:
              type: string
            description: 'A value in a key-value pair that represents a map of string keys and values.

              '
          - maxItems: 20
            minItems: 0
            type: array
            description: 'A value in a key-value pair that represents an array of maps of string keys and values.

              '
            items:
              $ref: '#/components/schemas/common.v1.0.config.MapOfStringWrapper'
          - maxItems: 100
            minItems: 0
            type: array
            description: 'A value in a key-value pair that represents a list of integers.

              '
            items:
              type: integer
              example: 99
      additionalProperties: false
      description: 'A map describing a set of keys and their corresponding values.

        '
    vmm.v4.0.error.ErrorResponse:
      type: object
      properties:
        error:
          oneOf:
          - type: array
            items:
              $ref: '#/components/schemas/vmm.v4.0.error.AppMessage'
          - $ref: '#/components/schemas/vmm.v4.0.error.SchemaValidationError'
      additionalProperties: false
      description: An error response indicates that the operation has failed either due to a client error(4XX) or server error(5XX).
        Please look at the HTTP status code and namespace specific error code and error message for further details.
      x-platform-generated: true
    common.v1.0.response.ApiResponseMetadata:
      type: object
      properties:
        flags:
          maxItems: 20
          minItems: 0
          type: array
          description: 'An array of flags that may indicate the status of the response. For example, a flag with the name
            ''isPaginated'' and value ''false'', indicates that the response is not paginated.

            '
          items:
            $ref: '#/components/schemas/common.v1.0.config.Flag'
        links:
          maxItems: 20
          minItems: 0
          type: array
          description: 'An array of HATEOAS style links for the response that may also include pagination links for list operations.

            '
          items:
            $ref: '#/components/schemas/common.v1.0.response.ApiLink'
        totalAvailableResults:
          type: integer
          description: 'The total number of entities that are available on the server for this type.

            '
          format: int32
          example: 25
        messages:
          maxItems: 20
          minItems: 0
          type: array
          description: 'Information, Warning or Error messages that might provide additional contextual information related
            to the operation.

            '
          items:
            $ref: '#/components/schemas/common.v1.0.config.Message'
        extraInfo:
          maxItems: 20
          minItems: 0
          type: array
          description: 'An array of entity-specific metadata

            '
          items:
            $ref: '#/components/schemas/common.v1.0.config.KVPair'
      additionalProperties: false
      description: 'The metadata associated with an API response. This value is always present and minimally contains the
        self-link for the API request that produced this response. It also contains pagination data for the paginated requests.

        '
  securitySchemes:
    basicAuthScheme:
      type: http
      scheme: basic
    apiKeyAuthScheme:
      type: apiKey
      name: X-ntnx-api-key
      in: header
