# GENERATED 1:1 from licensing-v4.0.yaml — resource 'License'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-licensing-license
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-licensing-license-oas/license.yaml
  resourceGroup: licensing.nutanix.krateo.io
  resource:
    kind: License
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $expand
    - $filter
    - $limit
    - $orderby
    - $page
    - $select
    verbsDescription:
    - action: findby
      method: GET
      path: /licensing/v4.0/config/licenses
