# GENERATED 1:1 from licensing-v4.0.yaml — resource 'Violation'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-licensing-violation
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-licensing-violation-oas/violation.yaml
  resourceGroup: licensing.nutanix.krateo.io
  resource:
    kind: Violation
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $limit
    - $page
    verbsDescription:
    - action: findby
      method: GET
      path: /licensing/v4.0/config/violations
