openapi: 3.0.0
info:
  contact:
    email: foundation@nutanix.com
    name: Foundation Developers
  description: '# Foundation


    Foundation is a Nutanix provided tool used for bootstrapping, imaging, and deployment of Nutanix clusters. The imaging
    process will install the desired version of the AOS software and the hypervisor of your choice. One of the ways to use
    Foundation services is to make use of the APIs provided by Foundation.


    Foundation provides seven categories of APIs, namely, General APIs, File Management APIs, Networking APIs, Imaging and
    Cluster Creation APIs, UCS Managed Mode APIs, Foundation Upgrade APIs and Factory APIs.


    However, most of these APIs find their use in internal scenarios. Some APIs that find most relevance in the customer scenario
    are image_nodes, pre_check, reboot_to_phoenix, reboot_from_phoenix, progress, phoenix_network_status, abort_session, get_progress_sessions
    among others.



    - Foundation Version: 5.10



    ## Terminology


    Some of the acronyms frequently used in the API descriptions are listed below:


    - **FVM** - Foundation Virtual Machine, A VM that has Foundation service running on it.

    - **BMC** - Baseboard management controller.

    - **IPMI** - Intelligent Platform Management Interface.


    **[Contact Us by Email](mailto:foundation@nutanix.com)**


    **License: Copyright Nutanix Inc. All rights reserved**


    '
  license:
    name: 'Copyright Nutanix Inc. All rights reserved

      '
  title: Foundation REST API
  version: '5.10'
servers:
- url: /foundation
security: []
paths:
  /get_phoenix_iso:
    post:
      description: Generates and downloads Phoenix ISO.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/phoenix_params'
        required: true
      responses:
        '200':
          description: Operation completed.
      summary: Get phoenix ISO
      tags:
      - General APIs
      x-codeSamples:
      - lang: cURL
        source: "curl --request POST \\\n    --url https://www.nutanix.dev/foundation/get_phoenix_iso \\\n    --data '{\n\
          \    \"arch\": \"string\",\n    \"bond_lacp_rate\": \"string\",\n    \"bond_mode\": \"string\",\n    \"bond_uplinks\"\
          : [\n        \"string\"\n    ],\n    \"gateway\": \"192.168.0.1\",\n    \"ip\": \"192.168.0.1\",\n    \"mode\":\
          \ \"string\",\n    \"nameservers\": [\n        \"192.168.0.1\"\n    ],\n    \"netmask\": \"192.168.0.1\",\n    \"\
          node_uuid\": \"b4d15375-1097-4c96-a4c4-4cb5809b05bb\",\n    \"ntp_servers\": [\n        \"string\"\n    ],\n   \
          \ \"test_ip\": \"192.168.0.1\"\n}'"
      - lang: Wget
        source: "wget --quiet \\\n    --method POST \\\n    --body-data '{\n    \"arch\": \"string\",\n    \"bond_lacp_rate\"\
          : \"string\",\n    \"bond_mode\": \"string\",\n    \"bond_uplinks\": [\n        \"string\"\n    ],\n    \"gateway\"\
          : \"192.168.0.1\",\n    \"ip\": \"192.168.0.1\",\n    \"mode\": \"string\",\n    \"nameservers\": [\n        \"\
          192.168.0.1\"\n    ],\n    \"netmask\": \"192.168.0.1\",\n    \"node_uuid\": \"b4d15375-1097-4c96-a4c4-4cb5809b05bb\"\
          ,\n    \"ntp_servers\": [\n        \"string\"\n    ],\n    \"test_ip\": \"192.168.0.1\"\n}' \\\n    --output-document\
          \ \\\n    - https://www.nutanix.dev/foundation/get_phoenix_iso"
      - lang: Python
        source: "import http.client\n\nconn = http.client.HTTPSConnection(\"www.nutanix.dev\")\n\nheaders = {}\n\npayload\
          \ =  \"\"\"{\n    \"arch\": \"string\",\n    \"bond_lacp_rate\": \"string\",\n    \"bond_mode\": \"string\",\n \
          \   \"bond_uplinks\": [\n        \"string\"\n    ],\n    \"gateway\": \"192.168.0.1\",\n    \"ip\": \"192.168.0.1\"\
          ,\n    \"mode\": \"string\",\n    \"nameservers\": [\n        \"192.168.0.1\"\n    ],\n    \"netmask\": \"192.168.0.1\"\
          ,\n    \"node_uuid\": \"b4d15375-1097-4c96-a4c4-4cb5809b05bb\",\n    \"ntp_servers\": [\n        \"string\"\n  \
          \  ],\n    \"test_ip\": \"192.168.0.1\"\n}\"\"\"\n\nconn.request(\"POST\",\"/foundation/get_phoenix_iso\", payload,\
          \ headers)\n\nres = conn.getresponse()\ndata = res.read()\n\nprint(data.decode(\"utf-8\"))"
      - lang: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl\
          \ := \"https://www.nutanix.dev/foundation/get_phoenix_iso\"\n\t\n\tpayload :=  strings.NewReader(`{\"arch\": \"\
          string\", \"bond_lacp_rate\": \"string\", \"bond_mode\": \"string\", \"bond_uplinks\": [\"string\"], \"gateway\"\
          : \"192.168.0.1\", \"ip\": \"192.168.0.1\", \"mode\": \"string\", \"nameservers\": [\"192.168.0.1\"], \"netmask\"\
          : \"192.168.0.1\", \"node_uuid\": \"b4d15375-1097-4c96-a4c4-4cb5809b05bb\", \"ntp_servers\": [\"string\"], \"test_ip\"\
          : \"192.168.0.1\"}`)\n\treq, err := http.NewRequest(\"POST\", url, payload)\n\tif err != nil {\n\t\tfmt.Println(\"\
          Error creating request:\", err)\n\t\treturn\n\t}\n\n    \n\tres, err := http.DefaultClient.Do(req)\n\tif err !=\
          \ nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n\tdefer res.Body.Close()\n\tbody,\
          \ err := io.ReadAll(res.Body)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\
          \t}\n\n\tfmt.Println(res)\n\tfmt.Println(string(body))\n\n}"
      - lang: Java
        source: "AsyncHttpClient client = new DefaultAsyncHttpClient();\nclient.prepare(\"POST\", \"https://www.nutanix.dev/foundation/get_phoenix_iso\"\
          )\n  .setBody(\"{\\\"arch\\\": \\\"string\\\", \\\"bond_lacp_rate\\\": \\\"string\\\", \\\"bond_mode\\\": \\\"string\\\
          \", \\\"bond_uplinks\\\": [\\\"string\\\"], \\\"gateway\\\": \\\"192.168.0.1\\\", \\\"ip\\\": \\\"192.168.0.1\\\"\
          , \\\"mode\\\": \\\"string\\\", \\\"nameservers\\\": [\\\"192.168.0.1\\\"], \\\"netmask\\\": \\\"192.168.0.1\\\"\
          , \\\"node_uuid\\\": \\\"b4d15375-1097-4c96-a4c4-4cb5809b05bb\\\", \\\"ntp_servers\\\": [\\\"string\\\"], \\\"test_ip\\\
          \": \\\"192.168.0.1\\\"}\")\n  .execute()\n  .toCompletableFuture()\n  .thenAccept(System.out::println)\n  .join();\n\
          \nclient.close();"
      - lang: JavaScript
        source: "const url = 'https://www.nutanix.dev/foundation/get_phoenix_iso';\nconst options = {\n  method: 'POST',\n\
          \  headers: {},\n  body:  `{\"arch\": \"string\", \"bond_lacp_rate\": \"string\", \"bond_mode\": \"string\", \"\
          bond_uplinks\": [\"string\"], \"gateway\": \"192.168.0.1\", \"ip\": \"192.168.0.1\", \"mode\": \"string\", \"nameservers\"\
          : [\"192.168.0.1\"], \"netmask\": \"192.168.0.1\", \"node_uuid\": \"b4d15375-1097-4c96-a4c4-4cb5809b05bb\", \"ntp_servers\"\
          : [\"string\"], \"test_ip\": \"192.168.0.1\"}`\n};\n\ntry {\n  const response = await fetch(url, options);\n  const\
          \ data = await response.json();\n  console.log(data);\n} catch (error) {\n  console.error(error);\n}"
components:
  schemas:
    phoenix_params:
      description: get_phoenix_iso parameters
      properties:
        arch:
          description: Must be one of x86_64 or ppc64le.
          type: string
        bond_lacp_rate:
          description: Slow or fast if lacp if being used at the switch.
          type: string
        bond_mode:
          description: Dynamic if LACP, static if using LAG.
          type: string
        bond_uplinks:
          description: MAC Addresses of NICs in a teambond.
          items:
            description: Mac Address of NIC in a teambond.
            type: string
          type: array
        gateway:
          description: Phoenix Netmask
          format: ipv4
          type: string
        ip:
          description: Phoenix Ipv4 address.
          format: ipv4
          type: string
        mode:
          description: Must be one of Installer, RescueShell or NDPRescueShell.
          type: string
        nameservers:
          description: List of DNS servers.
          items:
            description: IPv4 address.
            format: ipv4
            type: string
          type: array
        netmask:
          description: Phoenix Netmask.
          format: ipv4
          type: string
        node_uuid:
          description: Node UUID used in the hypervisor boot disk break-fix procedure in NDPRescueShell mode. Required for
            a LUKS- enabled node.
          format: uuid
          type: string
        ntp_servers:
          description: List of NTP servers.
          items:
            description: NTP server address.
            type: string
          type: array
        test_ip:
          description: IP to test phoenix connectivity with.
          format: ipv4
          type: string
      type: object
