openapi: 3.0.0
info:
  contact:
    email: foundation@nutanix.com
    name: Foundation Developers
  description: '# Foundation


    Foundation is a Nutanix provided tool used for bootstrapping, imaging, and deployment of Nutanix clusters. The imaging
    process will install the desired version of the AOS software and the hypervisor of your choice. One of the ways to use
    Foundation services is to make use of the APIs provided by Foundation.


    Foundation provides seven categories of APIs, namely, General APIs, File Management APIs, Networking APIs, Imaging and
    Cluster Creation APIs, UCS Managed Mode APIs, Foundation Upgrade APIs and Factory APIs.


    However, most of these APIs find their use in internal scenarios. Some APIs that find most relevance in the customer scenario
    are image_nodes, pre_check, reboot_to_phoenix, reboot_from_phoenix, progress, phoenix_network_status, abort_session, get_progress_sessions
    among others.



    - Foundation Version: 5.10



    ## Terminology


    Some of the acronyms frequently used in the API descriptions are listed below:


    - **FVM** - Foundation Virtual Machine, A VM that has Foundation service running on it.

    - **BMC** - Baseboard management controller.

    - **IPMI** - Intelligent Platform Management Interface.


    **[Contact Us by Email](mailto:foundation@nutanix.com)**


    **License: Copyright Nutanix Inc. All rights reserved**


    '
  license:
    name: 'Copyright Nutanix Inc. All rights reserved

      '
  title: Foundation REST API
  version: '5.10'
servers:
- url: /foundation
security: []
paths:
  /reboot_to_phoenix:
    post:
      description: Reboot CVM into Phoenix image.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/reboot_to_phoenix'
        required: true
      responses:
        '200':
          description: Success
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/http_code_200_with_session_id'
        '500':
          description: Raised in case of any errors or if cvm_ip is missing.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/http_error_500'
      summary: Reboot a node into phoenix
      tags:
      - General APIs
      x-codeSamples:
      - lang: cURL
        source: "curl --request POST \\\n    --url https://www.nutanix.dev/foundation/reboot_to_phoenix \\\n    --data '{\n\
          \    \"bond_lacp_rate\": \"string\",\n    \"bond_mode\": \"string\",\n    \"bond_uplinks\": [\n        \"string\"\
          \n    ],\n    \"compute_only\": true,\n    \"cvm_gateway\": \"192.168.0.1\",\n    \"cvm_ip\": \"192.168.0.1\",\n\
          \    \"cvm_netmask\": \"192.168.0.1\",\n    \"cvm_vlan_id\": 0,\n    \"hypervisor_gateway\": \"192.168.0.1\",\n\
          \    \"hypervisor_ip\": \"192.168.0.1\",\n    \"hypervisor_netmask\": \"192.168.0.1\",\n    \"mitigate_low_boot_space\"\
          : true,\n    \"nameservers\": [\n        \"192.168.0.1\"\n    ],\n    \"ntp_servers\": [\n        \"string\"\n \
          \   ],\n    \"precheck_only\": true,\n    \"reboot_timeout_mins\": 25\n}'"
      - lang: Wget
        source: "wget --quiet \\\n    --method POST \\\n    --body-data '{\n    \"bond_lacp_rate\": \"string\",\n    \"bond_mode\"\
          : \"string\",\n    \"bond_uplinks\": [\n        \"string\"\n    ],\n    \"compute_only\": true,\n    \"cvm_gateway\"\
          : \"192.168.0.1\",\n    \"cvm_ip\": \"192.168.0.1\",\n    \"cvm_netmask\": \"192.168.0.1\",\n    \"cvm_vlan_id\"\
          : 0,\n    \"hypervisor_gateway\": \"192.168.0.1\",\n    \"hypervisor_ip\": \"192.168.0.1\",\n    \"hypervisor_netmask\"\
          : \"192.168.0.1\",\n    \"mitigate_low_boot_space\": true,\n    \"nameservers\": [\n        \"192.168.0.1\"\n  \
          \  ],\n    \"ntp_servers\": [\n        \"string\"\n    ],\n    \"precheck_only\": true,\n    \"reboot_timeout_mins\"\
          : 25\n}' \\\n    --output-document \\\n    - https://www.nutanix.dev/foundation/reboot_to_phoenix"
      - lang: Python
        source: "import http.client\n\nconn = http.client.HTTPSConnection(\"www.nutanix.dev\")\n\nheaders = {}\n\npayload\
          \ =  \"\"\"{\n    \"bond_lacp_rate\": \"string\",\n    \"bond_mode\": \"string\",\n    \"bond_uplinks\": [\n   \
          \     \"string\"\n    ],\n    \"compute_only\": true,\n    \"cvm_gateway\": \"192.168.0.1\",\n    \"cvm_ip\": \"\
          192.168.0.1\",\n    \"cvm_netmask\": \"192.168.0.1\",\n    \"cvm_vlan_id\": 0,\n    \"hypervisor_gateway\": \"192.168.0.1\"\
          ,\n    \"hypervisor_ip\": \"192.168.0.1\",\n    \"hypervisor_netmask\": \"192.168.0.1\",\n    \"mitigate_low_boot_space\"\
          : true,\n    \"nameservers\": [\n        \"192.168.0.1\"\n    ],\n    \"ntp_servers\": [\n        \"string\"\n \
          \   ],\n    \"precheck_only\": true,\n    \"reboot_timeout_mins\": 25\n}\"\"\"\n\nconn.request(\"POST\",\"/foundation/reboot_to_phoenix\"\
          , payload, headers)\n\nres = conn.getresponse()\ndata = res.read()\n\nprint(data.decode(\"utf-8\"))"
      - lang: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl\
          \ := \"https://www.nutanix.dev/foundation/reboot_to_phoenix\"\n\t\n\tpayload :=  strings.NewReader(`{\"bond_lacp_rate\"\
          : \"string\", \"bond_mode\": \"string\", \"bond_uplinks\": [\"string\"], \"compute_only\": true, \"cvm_gateway\"\
          : \"192.168.0.1\", \"cvm_ip\": \"192.168.0.1\", \"cvm_netmask\": \"192.168.0.1\", \"cvm_vlan_id\": 0, \"hypervisor_gateway\"\
          : \"192.168.0.1\", \"hypervisor_ip\": \"192.168.0.1\", \"hypervisor_netmask\": \"192.168.0.1\", \"mitigate_low_boot_space\"\
          : true, \"nameservers\": [\"192.168.0.1\"], \"ntp_servers\": [\"string\"], \"precheck_only\": true, \"reboot_timeout_mins\"\
          : 25}`)\n\treq, err := http.NewRequest(\"POST\", url, payload)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating\
          \ request:\", err)\n\t\treturn\n\t}\n\n    \n\tres, err := http.DefaultClient.Do(req)\n\tif err != nil {\n\t\tfmt.Println(\"\
          Error creating request:\", err)\n\t\treturn\n\t}\n\n\tdefer res.Body.Close()\n\tbody, err := io.ReadAll(res.Body)\n\
          \tif err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n\tfmt.Println(res)\n\t\
          fmt.Println(string(body))\n\n}"
      - lang: Java
        source: "AsyncHttpClient client = new DefaultAsyncHttpClient();\nclient.prepare(\"POST\", \"https://www.nutanix.dev/foundation/reboot_to_phoenix\"\
          )\n  .setBody(\"{\\\"bond_lacp_rate\\\": \\\"string\\\", \\\"bond_mode\\\": \\\"string\\\", \\\"bond_uplinks\\\"\
          : [\\\"string\\\"], \\\"compute_only\\\": true, \\\"cvm_gateway\\\": \\\"192.168.0.1\\\", \\\"cvm_ip\\\": \\\"192.168.0.1\\\
          \", \\\"cvm_netmask\\\": \\\"192.168.0.1\\\", \\\"cvm_vlan_id\\\": 0, \\\"hypervisor_gateway\\\": \\\"192.168.0.1\\\
          \", \\\"hypervisor_ip\\\": \\\"192.168.0.1\\\", \\\"hypervisor_netmask\\\": \\\"192.168.0.1\\\", \\\"mitigate_low_boot_space\\\
          \": true, \\\"nameservers\\\": [\\\"192.168.0.1\\\"], \\\"ntp_servers\\\": [\\\"string\\\"], \\\"precheck_only\\\
          \": true, \\\"reboot_timeout_mins\\\": 25}\")\n  .execute()\n  .toCompletableFuture()\n  .thenAccept(System.out::println)\n\
          \  .join();\n\nclient.close();"
      - lang: JavaScript
        source: "const url = 'https://www.nutanix.dev/foundation/reboot_to_phoenix';\nconst options = {\n  method: 'POST',\n\
          \  headers: {},\n  body:  `{\"bond_lacp_rate\": \"string\", \"bond_mode\": \"string\", \"bond_uplinks\": [\"string\"\
          ], \"compute_only\": true, \"cvm_gateway\": \"192.168.0.1\", \"cvm_ip\": \"192.168.0.1\", \"cvm_netmask\": \"192.168.0.1\"\
          , \"cvm_vlan_id\": 0, \"hypervisor_gateway\": \"192.168.0.1\", \"hypervisor_ip\": \"192.168.0.1\", \"hypervisor_netmask\"\
          : \"192.168.0.1\", \"mitigate_low_boot_space\": true, \"nameservers\": [\"192.168.0.1\"], \"ntp_servers\": [\"string\"\
          ], \"precheck_only\": true, \"reboot_timeout_mins\": 25}`\n};\n\ntry {\n  const response = await fetch(url, options);\n\
          \  const data = await response.json();\n  console.log(data);\n} catch (error) {\n  console.error(error);\n}"
components:
  schemas:
    http_code_200_with_session_id:
      properties:
        session_id:
          description: Imaging session ID.
          type: string
      type: object
    reboot_to_phoenix:
      description: Reboot to phoenix parameters .
      properties:
        bond_lacp_rate:
          description: Slow or fast if lacp if being used at the switch.
          type: string
        bond_mode:
          description: Dynamic if using LACP, static for LAG.
          type: string
        bond_uplinks:
          description: MAC Addresses of NICs in a team/bond.
          items:
            description: Mac Address of NIC in a team/bond.
            type: string
          type: array
        compute_only:
          description: Indicate this is a compute-only node.
          type: boolean
        cvm_gateway:
          description: Gateway of CVM.
          format: ipv4
          type: string
        cvm_ip:
          description: IP address of CVM.
          format: ipv4
          type: string
        cvm_netmask:
          description: Netmask of CVM.
          format: ipv4
          type: string
        cvm_vlan_id:
          description: Vlan ID of CVM.
          type: integer
        hypervisor_gateway:
          description: Gateway of the hypervisor.
          format: ipv4
          type: string
        hypervisor_ip:
          description: IP address of the hypervisor.
          format: ipv4
          type: string
        hypervisor_netmask:
          description: Netmask of the hypervisor.
          format: ipv4
          type: string
        mitigate_low_boot_space:
          description: Relocate bootbank files to make space for phoenix files.
          type: boolean
          x-doc-hide: true
          x-internal: true
        nameservers:
          description: List of DNS servers.
          items:
            description: IPv4 address.
            format: ipv4
            type: string
          type: array
        ntp_servers:
          description: List of NTP servers.
          items:
            description: NTP server address.
            type: string
          type: array
        precheck_only:
          description: Check if the node can be booted into phoenix.
          type: boolean
        reboot_timeout_mins:
          description: Time period (in minutes) foundation waits for the node to boot into phoenix.
          format: int64
          minimum: 25
          type: integer
      type: object
    http_error_500:
      description: HTTP error 500 description.
      properties:
        error:
          properties:
            details:
              description: Error details.
              type: object
            message:
              description: Error message.
              type: string
            session_id:
              description: Imaging session ID.
              type: string
          type: object
      type: object
