openapi: 3.0.0
info:
  contact:
    email: foundation@nutanix.com
    name: Foundation Developers
  description: '# Foundation


    Foundation is a Nutanix provided tool used for bootstrapping, imaging, and deployment of Nutanix clusters. The imaging
    process will install the desired version of the AOS software and the hypervisor of your choice. One of the ways to use
    Foundation services is to make use of the APIs provided by Foundation.


    Foundation provides seven categories of APIs, namely, General APIs, File Management APIs, Networking APIs, Imaging and
    Cluster Creation APIs, UCS Managed Mode APIs, Foundation Upgrade APIs and Factory APIs.


    However, most of these APIs find their use in internal scenarios. Some APIs that find most relevance in the customer scenario
    are image_nodes, pre_check, reboot_to_phoenix, reboot_from_phoenix, progress, phoenix_network_status, abort_session, get_progress_sessions
    among others.



    - Foundation Version: 5.10



    ## Terminology


    Some of the acronyms frequently used in the API descriptions are listed below:


    - **FVM** - Foundation Virtual Machine, A VM that has Foundation service running on it.

    - **BMC** - Baseboard management controller.

    - **IPMI** - Intelligent Platform Management Interface.


    **[Contact Us by Email](mailto:foundation@nutanix.com)**


    **License: Copyright Nutanix Inc. All rights reserved**


    '
  license:
    name: 'Copyright Nutanix Inc. All rights reserved

      '
  title: Foundation REST API
  version: '5.10'
servers:
- url: /foundation
security: []
paths:
  /update_whitelist:
    post:
      description: Updates the hypervisor whitelist.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/iso_whitelist_properties'
        required: true
      responses:
        '200':
          description: Operation completed.
      summary: Update the hypervisor whitelist
      tags:
      - File Management APIs
      x-codeSamples:
      - lang: cURL
        source: "curl --request POST \\\n    --url https://www.nutanix.dev/foundation/update_whitelist \\\n    --header 'Content-Type:\
          \ application/json' \\\n    --data '{\n    \"iso_whitelist\": {\n        \"additionalProperties\": {\n         \
          \   \"compatible_versions\": {\n                \"esx\": [\n                    \"string\"\n                ],\n\
          \                \"hyperv\": [\n                    \"string\"\n                ],\n                \"kvm\": [\n\
          \                    \"string\"\n                ],\n                \"xen\": [\n                    \"string\"\n\
          \                ]\n            },\n            \"deprecated\": \"string\",\n            \"filesize\": \"string\"\
          ,\n            \"friendly_name\": \"string\",\n            \"hypervisor\": \"string\",\n            \"min_foundation\"\
          : \"string\",\n            \"min_nos\": \"string\",\n            \"skus\": [\n                \"string\"\n     \
          \       ],\n            \"unsupported_hardware\": [\n                \"string\"\n            ],\n            \"\
          version\": \"string\"\n        }\n    },\n    \"last_modified\": 0\n}'"
      - lang: Wget
        source: "wget --quiet \\\n    --method POST \\\n    --header 'Content-Type: application/json' \\\n    --body-data\
          \ '{\n    \"iso_whitelist\": {\n        \"additionalProperties\": {\n            \"compatible_versions\": {\n  \
          \              \"esx\": [\n                    \"string\"\n                ],\n                \"hyperv\": [\n \
          \                   \"string\"\n                ],\n                \"kvm\": [\n                    \"string\"\n\
          \                ],\n                \"xen\": [\n                    \"string\"\n                ]\n           \
          \ },\n            \"deprecated\": \"string\",\n            \"filesize\": \"string\",\n            \"friendly_name\"\
          : \"string\",\n            \"hypervisor\": \"string\",\n            \"min_foundation\": \"string\",\n          \
          \  \"min_nos\": \"string\",\n            \"skus\": [\n                \"string\"\n            ],\n            \"\
          unsupported_hardware\": [\n                \"string\"\n            ],\n            \"version\": \"string\"\n   \
          \     }\n    },\n    \"last_modified\": 0\n}' \\\n    --output-document \\\n    - https://www.nutanix.dev/foundation/update_whitelist"
      - lang: Python
        source: "import http.client\n\nconn = http.client.HTTPSConnection(\"www.nutanix.dev\")\n\nheaders = {\n    \"Content-Type\"\
          : \"application/json\"\n}\n\npayload =  \"\"\"{\n    \"iso_whitelist\": {\n        \"additionalProperties\": {\n\
          \            \"compatible_versions\": {\n                \"esx\": [\n                    \"string\"\n          \
          \      ],\n                \"hyperv\": [\n                    \"string\"\n                ],\n                \"\
          kvm\": [\n                    \"string\"\n                ],\n                \"xen\": [\n                    \"\
          string\"\n                ]\n            },\n            \"deprecated\": \"string\",\n            \"filesize\":\
          \ \"string\",\n            \"friendly_name\": \"string\",\n            \"hypervisor\": \"string\",\n           \
          \ \"min_foundation\": \"string\",\n            \"min_nos\": \"string\",\n            \"skus\": [\n             \
          \   \"string\"\n            ],\n            \"unsupported_hardware\": [\n                \"string\"\n          \
          \  ],\n            \"version\": \"string\"\n        }\n    },\n    \"last_modified\": 0\n}\"\"\"\n\nconn.request(\"\
          POST\",\"/foundation/update_whitelist\", payload, headers)\n\nres = conn.getresponse()\ndata = res.read()\n\nprint(data.decode(\"\
          utf-8\"))"
      - lang: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl\
          \ := \"https://www.nutanix.dev/foundation/update_whitelist\"\n\t\n\tpayload :=  strings.NewReader(`{\"iso_whitelist\"\
          : {\"additionalProperties\": {\"compatible_versions\": {\"esx\": [\"string\"], \"hyperv\": [\"string\"], \"kvm\"\
          : [\"string\"], \"xen\": [\"string\"]}, \"deprecated\": \"string\", \"filesize\": \"string\", \"friendly_name\"\
          : \"string\", \"hypervisor\": \"string\", \"min_foundation\": \"string\", \"min_nos\": \"string\", \"skus\": [\"\
          string\"], \"unsupported_hardware\": [\"string\"], \"version\": \"string\"}}, \"last_modified\": 0}`)\n\treq, err\
          \ := http.NewRequest(\"POST\", url, payload)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\
          \t\treturn\n\t}\n\n        req.Header.Add(\"Content-Type\", \"application/json\")\n    \n\tres, err := http.DefaultClient.Do(req)\n\
          \tif err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n\tdefer res.Body.Close()\n\
          \tbody, err := io.ReadAll(res.Body)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\t\
          return\n\t}\n\n\tfmt.Println(res)\n\tfmt.Println(string(body))\n\n}"
      - lang: Java
        source: "AsyncHttpClient client = new DefaultAsyncHttpClient();\nclient.prepare(\"POST\", \"https://www.nutanix.dev/foundation/update_whitelist\"\
          )\n  .setHeader(\"Content-Type\", \"application/json\")\n  .setBody(\"{\\\"iso_whitelist\\\": {\\\"additionalProperties\\\
          \": {\\\"compatible_versions\\\": {\\\"esx\\\": [\\\"string\\\"], \\\"hyperv\\\": [\\\"string\\\"], \\\"kvm\\\"\
          : [\\\"string\\\"], \\\"xen\\\": [\\\"string\\\"]}, \\\"deprecated\\\": \\\"string\\\", \\\"filesize\\\": \\\"string\\\
          \", \\\"friendly_name\\\": \\\"string\\\", \\\"hypervisor\\\": \\\"string\\\", \\\"min_foundation\\\": \\\"string\\\
          \", \\\"min_nos\\\": \\\"string\\\", \\\"skus\\\": [\\\"string\\\"], \\\"unsupported_hardware\\\": [\\\"string\\\
          \"], \\\"version\\\": \\\"string\\\"}}, \\\"last_modified\\\": 0}\")\n  .execute()\n  .toCompletableFuture()\n \
          \ .thenAccept(System.out::println)\n  .join();\n\nclient.close();"
      - lang: JavaScript
        source: "const url = 'https://www.nutanix.dev/foundation/update_whitelist';\nconst options = {\n  method: 'POST',\n\
          \  headers: {'Content-Type': 'application/json'},\n  body:  `{\"iso_whitelist\": {\"additionalProperties\": {\"\
          compatible_versions\": {\"esx\": [\"string\"], \"hyperv\": [\"string\"], \"kvm\": [\"string\"], \"xen\": [\"string\"\
          ]}, \"deprecated\": \"string\", \"filesize\": \"string\", \"friendly_name\": \"string\", \"hypervisor\": \"string\"\
          , \"min_foundation\": \"string\", \"min_nos\": \"string\", \"skus\": [\"string\"], \"unsupported_hardware\": [\"\
          string\"], \"version\": \"string\"}}, \"last_modified\": 0}`\n};\n\ntry {\n  const response = await fetch(url, options);\n\
          \  const data = await response.json();\n  console.log(data);\n} catch (error) {\n  console.error(error);\n}"
components:
  schemas:
    iso_whitelist_properties:
      description: Properties of the ISO.
      properties:
        iso_whitelist:
          description: Details of ISO.
          properties:
            additionalProperties:
              $ref: '#/components/schemas/iso_properties'
          type: object
        last_modified:
          description: Last modified time.
          format: int64
          type: integer
      type: object
    iso_properties:
      description: Details of the ISO.
      properties:
        compatible_versions:
          $ref: '#/components/schemas/compatible_version'
        deprecated:
          description: Foundation version from which the ISO is deprecated.
          type: string
        filesize:
          description: File size.
          type: string
        friendly_name:
          description: Friendly name of hypervisor.
          type: string
        hypervisor:
          description: Hypervisor type, i.e, kvm, esx, etc.
          type: string
        min_foundation:
          description: Minimum foundation version, the ISO is compatible with.
          type: string
        min_nos:
          description: Minimum nos version, the ISO is compatible with.
          type: string
        skus:
          description: List of supported skus.
          items:
            description: Skus.
            type: string
          type: array
        unsupported_hardware:
          description: List of regex of hardwares on which the ISO is not compatible.
          items:
            description: RegEx strings for unsupported hardware.
            type: string
          type: array
        version:
          description: Hypervisor version.
          type: string
      type: object
    compatible_version:
      description: Hypervisor with compatible version.
      maxProperties: 1
      minProperties: 1
      properties:
        esx:
          description: Esx compatible versions.
          items:
            type: string
          type: array
        hyperv:
          description: Hyperv compatible versions.
          items:
            type: string
          type: array
        kvm:
          description: Kvm compatible versions.
          items:
            type: string
          type: array
        xen:
          description: Xen compatible versions.
          items:
            type: string
          type: array
      type: object
