# GENERATED 1:1 from clustermgmt-v4.0.yaml — resource 'BmcInfo'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-clustermgmt-bmcinfo
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-clustermgmt-bmcinfo-oas/bmcinfo.yaml
  resourceGroup: clustermgmt.nutanix.krateo.io
  resource:
    kind: BmcInfo
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /clustermgmt/v4.0/config/clusters/{clusterExtId}/hosts/{extId}/bmc-info
      requestFieldMapping:
      - inPath: clusterExtId
        inCustomResource: spec.clusterExtId
      - inPath: extId
        inCustomResource: spec.extId
