# GENERATED 1:1 from clustermgmt-v4.0.yaml — resource 'Cluster'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-clustermgmt-cluster
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-clustermgmt-cluster-oas/cluster.yaml
  resourceGroup: clustermgmt.nutanix.krateo.io
  resource:
    kind: Cluster
    identifiers:
    - name
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $apply
    - $dryrun
    - $expand
    - $filter
    - $limit
    - $orderby
    - $page
    - $select
    verbsDescription:
    - action: findby
      method: GET
      path: /clustermgmt/v4.0/config/clusters
    - action: create
      method: POST
      path: /clustermgmt/v4.0/config/clusters
    - action: get
      method: GET
      path: /clustermgmt/v4.0/config/clusters/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /clustermgmt/v4.0/config/clusters/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /clustermgmt/v4.0/config/clusters/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
