# GENERATED 1:1 from clustermgmt-v4.0.yaml — resource 'Host2'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-clustermgmt-host2
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-clustermgmt-host2-oas/host2.yaml
  resourceGroup: clustermgmt.nutanix.krateo.io
  resource:
    kind: Host2
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $apply
    - $filter
    - $limit
    - $orderby
    - $page
    - $select
    verbsDescription:
    - action: findby
      method: GET
      path: /clustermgmt/v4.0/config/hosts
