# GENERATED 1:1 from clustermgmt-v4.0.yaml — resource 'PcieDevice'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-clustermgmt-pciedevice
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-clustermgmt-pciedevice-oas/pciedevice.yaml
  resourceGroup: clustermgmt.nutanix.krateo.io
  resource:
    kind: PcieDevice
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $limit
    - $page
    - $select
    verbsDescription:
    - action: findby
      method: GET
      path: /clustermgmt/v4.0/ahv/config/pcie-devices
