# GENERATED 1:1 from clustermgmt-v4.0.yaml — resource 'RackableUnit'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-clustermgmt-rackableunit
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-clustermgmt-rackableunit-oas/rackableunit.yaml
  resourceGroup: clustermgmt.nutanix.krateo.io
  resource:
    kind: RackableUnit
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /clustermgmt/v4.0/config/clusters/{clusterExtId}/rackable-units
      requestFieldMapping:
      - inPath: clusterExtId
        inCustomResource: spec.clusterExtId
    - action: get
      method: GET
      path: /clustermgmt/v4.0/config/clusters/{clusterExtId}/rackable-units/{extId}
      requestFieldMapping:
      - inPath: clusterExtId
        inCustomResource: spec.clusterExtId
      - inPath: extId
        inCustomResource: status.extId
