# GENERATED 1:1 from clustermgmt-v4.0.yaml — resource 'RsyslogServer'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-clustermgmt-rsyslogserver
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-clustermgmt-rsyslogserver-oas/rsyslogserver.yaml
  resourceGroup: clustermgmt.nutanix.krateo.io
  resource:
    kind: RsyslogServer
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /clustermgmt/v4.0/config/clusters/{clusterExtId}/rsyslog-servers
      requestFieldMapping:
      - inPath: clusterExtId
        inCustomResource: spec.clusterExtId
    - action: create
      method: POST
      path: /clustermgmt/v4.0/config/clusters/{clusterExtId}/rsyslog-servers
      requestFieldMapping:
      - inPath: clusterExtId
        inCustomResource: spec.clusterExtId
    - action: get
      method: GET
      path: /clustermgmt/v4.0/config/clusters/{clusterExtId}/rsyslog-servers/{extId}
      requestFieldMapping:
      - inPath: clusterExtId
        inCustomResource: spec.clusterExtId
      - inPath: extId
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /clustermgmt/v4.0/config/clusters/{clusterExtId}/rsyslog-servers/{extId}
      requestFieldMapping:
      - inPath: clusterExtId
        inCustomResource: spec.clusterExtId
      - inPath: extId
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /clustermgmt/v4.0/config/clusters/{clusterExtId}/rsyslog-servers/{extId}
      requestFieldMapping:
      - inPath: clusterExtId
        inCustomResource: spec.clusterExtId
      - inPath: extId
        inCustomResource: status.extId
