# GENERATED 1:1 from clustermgmt-v4.0.yaml — resource 'TaskResponse'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-clustermgmt-taskresponse
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-clustermgmt-taskresponse-oas/taskresponse.yaml
  resourceGroup: clustermgmt.nutanix.krateo.io
  resource:
    kind: TaskResponse
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - taskResponseType
    verbsDescription:
    - action: get
      method: GET
      path: /clustermgmt/v4.0/config/task-response/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
