# GENERATED 1:1 from clustermgmt-v4.0.yaml — resource 'VirtualGpuProfile'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-clustermgmt-virtualgpuprofile
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-clustermgmt-virtualgpuprofile-oas/virtualgpuprofile.yaml
  resourceGroup: clustermgmt.nutanix.krateo.io
  resource:
    kind: VirtualGpuProfile
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $limit
    - $orderby
    - $page
    verbsDescription:
    - action: findby
      method: GET
      path: /clustermgmt/v4.0/config/clusters/{clusterExtId}/virtual-gpu-profiles
      requestFieldMapping:
      - inPath: clusterExtId
        inCustomResource: spec.clusterExtId
