# GENERATED 1:1 from aiops-v4.0.yaml — resource 'EntityDescriptor'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-aiops-entitydescriptor
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-aiops-entitydescriptor-oas/entitydescriptor.yaml
  resourceGroup: aiops.nutanix.krateo.io
  resource:
    kind: EntityDescriptor
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $limit
    - $page
    verbsDescription:
    - action: findby
      method: GET
      path: /aiops/v4.0/config/sources/{sourceExtId}/entity-descriptors
      requestFieldMapping:
      - inPath: sourceExtId
        inCustomResource: spec.sourceExtId
