# GENERATED 1:1 from aiops-v4.0.yaml — resource 'Report'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-aiops-report
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-aiops-report-oas/report.yaml
  resourceGroup: aiops.nutanix.krateo.io
  resource:
    kind: Report
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /aiops/v4.0/config/scenarios/{scenarioExtId}/reports
      requestFieldMapping:
      - inPath: scenarioExtId
        inCustomResource: spec.scenarioExtId
