# GENERATED 1:1 from aiops-v4.0.yaml — resource 'Simulation'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-aiops-simulation
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-aiops-simulation-oas/simulation.yaml
  resourceGroup: aiops.nutanix.krateo.io
  resource:
    kind: Simulation
    identifiers:
    - name
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $limit
    - $orderby
    - $page
    - $select
    verbsDescription:
    - action: findby
      method: GET
      path: /aiops/v4.0/config/simulations
    - action: create
      method: POST
      path: /aiops/v4.0/config/simulations
    - action: get
      method: GET
      path: /aiops/v4.0/config/simulations/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /aiops/v4.0/config/simulations/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /aiops/v4.0/config/simulations/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
