# GENERATED 1:1 from aiops-v4.0.yaml — resource 'Source'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-aiops-source
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-aiops-source-oas/source.yaml
  resourceGroup: aiops.nutanix.krateo.io
  resource:
    kind: Source
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /aiops/v4.0/config/sources
