openapi: 3.0.0
info:
  version: v2.0
  title: Nutanix Prism API Reference
  description: "# Introduction\n\nThe Nutanix REST APIs allow you to create scripts that run system administration commands\
    \ against the Nutanix cluster. The API enables the use of HTTP requests to get information about the cluster as well as\
    \ make changes to the configuration. Output from the API calls are returned in JSON format.\n\nAll API users should have\
    \ valid Prism login credentials to send API calls to the Prism server. APIs on nutanix.dev portal are publicly available\
    \ to all valid users without special permissions for viewing purposes.\n\nThe v2 API is an update of the v1 API. Users\
    \ of the v1 API are encouraged to migrate to v2. \n\n[Nutanix API versions \u2013 What are they and what does each one\
    \ do?](https://www.nutanix.dev/api-versions/)"
  contact:
    name: Nutanix, Inc.
    url: http://www.nutanix.com
  license:
    name: EULA
    url: http://www.nutanix.com/eula
servers:
- url: https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0
security: []
paths:
  /storage_containers/datastores/add_datastore:
    post:
      summary: Add an NFS Datastore.
      description: Add an NFS Datastore.
      tags:
      - /storage_containers
      operationId: post/storage_containers/datastores/add_datastore/createNfsDatastores
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create.dto.esx.CreateNfsDatastoreRequestDTO'
        description: Add request
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/create.dto.esx.CreateNfsDatastoreStatusDTO'
      x-codeSamples:
      - lang: cURL
        source: "curl --request POST \\\n    --url https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/storage_containers/datastores/add_datastore\
          \ \\\n    --header 'Accept: application/json' \\\n    --header 'Content-Type: application/json' \\\n    --data '{\n\
          \    \"container_name\": \"string\",\n    \"datastore_name\": \"string\",\n    \"node_ids\": [\n        \"string\"\
          \n    ],\n    \"node_uuids\": [\n        \"string\"\n    ],\n    \"read_only\": true,\n    \"storage_container_name\"\
          : \"string\",\n    \"target_path\": \"string\"\n}'"
      - lang: Wget
        source: "wget --quiet \\\n    --method POST \\\n    --header 'Accept: application/json' \\\n    --header 'Content-Type:\
          \ application/json' \\\n    --body-data '{\n    \"container_name\": \"string\",\n    \"datastore_name\": \"string\"\
          ,\n    \"node_ids\": [\n        \"string\"\n    ],\n    \"node_uuids\": [\n        \"string\"\n    ],\n    \"read_only\"\
          : true,\n    \"storage_container_name\": \"string\",\n    \"target_path\": \"string\"\n}' \\\n    --output-document\
          \ \\\n    - https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/storage_containers/datastores/add_datastore"
      - lang: Python
        source: "import http.client\n\nconn = http.client.HTTPSConnection(\"any_cvm_ip:9440\")\n\nheaders = {\n    \"Accept\"\
          : \"application/json\",\n    \"Content-Type\": \"application/json\"\n}\n\npayload =  \"\"\"{\n    \"container_name\"\
          : \"string\",\n    \"datastore_name\": \"string\",\n    \"node_ids\": [\n        \"string\"\n    ],\n    \"node_uuids\"\
          : [\n        \"string\"\n    ],\n    \"read_only\": true,\n    \"storage_container_name\": \"string\",\n    \"target_path\"\
          : \"string\"\n}\"\"\"\n\nconn.request(\"POST\",\"/PrismGateway/services/rest/v2.0/storage_containers/datastores/add_datastore\"\
          , payload, headers)\n\nres = conn.getresponse()\ndata = res.read()\n\nprint(data.decode(\"utf-8\"))"
      - lang: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl\
          \ := \"https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/storage_containers/datastores/add_datastore\"\n\t\
          \n\tpayload :=  strings.NewReader(`{\"container_name\": \"string\", \"datastore_name\": \"string\", \"node_ids\"\
          : [\"string\"], \"node_uuids\": [\"string\"], \"read_only\": true, \"storage_container_name\": \"string\", \"target_path\"\
          : \"string\"}`)\n\treq, err := http.NewRequest(\"POST\", url, payload)\n\tif err != nil {\n\t\tfmt.Println(\"Error\
          \ creating request:\", err)\n\t\treturn\n\t}\n\n        req.Header.Add(\"Accept\", \"application/json\")\n     \
          \   req.Header.Add(\"Content-Type\", \"application/json\")\n    \n\tres, err := http.DefaultClient.Do(req)\n\tif\
          \ err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n\tdefer res.Body.Close()\n\
          \tbody, err := io.ReadAll(res.Body)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\t\
          return\n\t}\n\n\tfmt.Println(res)\n\tfmt.Println(string(body))\n\n}"
      - lang: Java
        source: "AsyncHttpClient client = new DefaultAsyncHttpClient();\nclient.prepare(\"POST\", \"https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/storage_containers/datastores/add_datastore\"\
          )\n  .setHeader(\"Accept\", \"application/json\")\n  .setHeader(\"Content-Type\", \"application/json\")\n  .setBody(\"\
          {\\\"container_name\\\": \\\"string\\\", \\\"datastore_name\\\": \\\"string\\\", \\\"node_ids\\\": [\\\"string\\\
          \"], \\\"node_uuids\\\": [\\\"string\\\"], \\\"read_only\\\": true, \\\"storage_container_name\\\": \\\"string\\\
          \", \\\"target_path\\\": \\\"string\\\"}\")\n  .execute()\n  .toCompletableFuture()\n  .thenAccept(System.out::println)\n\
          \  .join();\n\nclient.close();"
      - lang: JavaScript
        source: "const url = 'https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/storage_containers/datastores/add_datastore';\n\
          const options = {\n  method: 'POST',\n  headers: {'Accept': 'application/json', 'Content-Type': 'application/json'},\n\
          \  body:  `{\"container_name\": \"string\", \"datastore_name\": \"string\", \"node_ids\": [\"string\"], \"node_uuids\"\
          : [\"string\"], \"read_only\": true, \"storage_container_name\": \"string\", \"target_path\": \"string\"}`\n};\n\
          \ntry {\n  const response = await fetch(url, options);\n  const data = await response.json();\n  console.log(data);\n\
          } catch (error) {\n  console.error(error);\n}"
components:
  schemas:
    create.dto.esx.CreateNfsDatastoreStatusDTO_NodeSpecificCreateStatus:
      type: object
      properties:
        capacity:
          format: int64
          type: integer
        free_space:
          format: int64
          type: integer
        message:
          type: string
        node_id:
          type: string
        node_ip_address:
          type: string
        node_uuid:
          type: string
        successful:
          type: boolean
    create.dto.esx.CreateNfsDatastoreStatusDTO:
      type: object
      properties:
        node_specific_status:
          items:
            $ref: '#/components/schemas/create.dto.esx.CreateNfsDatastoreStatusDTO_NodeSpecificCreateStatus'
          type: array
    create.dto.esx.CreateNfsDatastoreRequestDTO:
      type: object
      properties:
        container_name:
          type: string
        datastore_name:
          type: string
        node_ids:
          items:
            type: string
          type: array
        node_uuids:
          items:
            type: string
          type: array
        read_only:
          type: boolean
        storage_container_name:
          type: string
        target_path:
          type: string
