openapi: 3.0.0
info:
  version: v2.0
  title: Nutanix Prism API Reference
  description: "# Introduction\n\nThe Nutanix REST APIs allow you to create scripts that run system administration commands\
    \ against the Nutanix cluster. The API enables the use of HTTP requests to get information about the cluster as well as\
    \ make changes to the configuration. Output from the API calls are returned in JSON format.\n\nAll API users should have\
    \ valid Prism login credentials to send API calls to the Prism server. APIs on nutanix.dev portal are publicly available\
    \ to all valid users without special permissions for viewing purposes.\n\nThe v2 API is an update of the v1 API. Users\
    \ of the v1 API are encouraged to migrate to v2. \n\n[Nutanix API versions \u2013 What are they and what does each one\
    \ do?](https://www.nutanix.dev/api-versions/)"
  contact:
    name: Nutanix, Inc.
    url: http://www.nutanix.com
  license:
    name: EULA
    url: http://www.nutanix.com/eula
servers:
- url: https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0
security: []
paths:
  /alerts/policies/conflicting_policies:
    post:
      tags:
      - /alerts
      operationId: post/alerts/policies/conflicting_policies/getConflictingPolicies
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create.dto.alerts.AlertPolicyDTO'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/create.base.EntityCollection_create.dto.alerts.AlertPolicyDTO_'
      x-codeSamples:
      - lang: cURL
        source: "curl --request POST \\\n    --url https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/alerts/policies/conflicting_policies\
          \ \\\n    --header 'Accept: application/json' \\\n    --header 'Content-Type: application/json' \\\n    --data '{\n\
          \    \"auto_resolve\": true,\n    \"created_by\": \"string\",\n    \"description\": \"string\",\n    \"enabled\"\
          : true,\n    \"error_on_conflict\": true,\n    \"filter\": \"string\",\n    \"id\": \"string\",\n    \"impact_types\"\
          : [\n        \"string\"\n    ],\n    \"last_updated_timestamp_in_usecs\": 0,\n    \"policies_to_override\": [\n\
          \        \"string\"\n    ],\n    \"related_policies\": [\n        {\n            \"entity_uuid\": \"string\",\n\
          \            \"policy_ids\": [\n                \"string\"\n            ]\n        }\n    ],\n    \"title\": \"\
          string\",\n    \"trigger_conditions\": [\n        {\n            \"condition\": \"string\",\n            \"condition_type\"\
          : \"STATIC_THRESHOLD\",\n            \"severity_level\": \"CRITICAL\"\n        }\n    ],\n    \"trigger_wait_period_in_secs\"\
          : 0\n}'"
      - lang: Wget
        source: "wget --quiet \\\n    --method POST \\\n    --header 'Accept: application/json' \\\n    --header 'Content-Type:\
          \ application/json' \\\n    --body-data '{\n    \"auto_resolve\": true,\n    \"created_by\": \"string\",\n    \"\
          description\": \"string\",\n    \"enabled\": true,\n    \"error_on_conflict\": true,\n    \"filter\": \"string\"\
          ,\n    \"id\": \"string\",\n    \"impact_types\": [\n        \"string\"\n    ],\n    \"last_updated_timestamp_in_usecs\"\
          : 0,\n    \"policies_to_override\": [\n        \"string\"\n    ],\n    \"related_policies\": [\n        {\n    \
          \        \"entity_uuid\": \"string\",\n            \"policy_ids\": [\n                \"string\"\n            ]\n\
          \        }\n    ],\n    \"title\": \"string\",\n    \"trigger_conditions\": [\n        {\n            \"condition\"\
          : \"string\",\n            \"condition_type\": \"STATIC_THRESHOLD\",\n            \"severity_level\": \"CRITICAL\"\
          \n        }\n    ],\n    \"trigger_wait_period_in_secs\": 0\n}' \\\n    --output-document \\\n    - https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/alerts/policies/conflicting_policies"
      - lang: Python
        source: "import http.client\n\nconn = http.client.HTTPSConnection(\"any_cvm_ip:9440\")\n\nheaders = {\n    \"Accept\"\
          : \"application/json\",\n    \"Content-Type\": \"application/json\"\n}\n\npayload =  \"\"\"{\n    \"auto_resolve\"\
          : true,\n    \"created_by\": \"string\",\n    \"description\": \"string\",\n    \"enabled\": true,\n    \"error_on_conflict\"\
          : true,\n    \"filter\": \"string\",\n    \"id\": \"string\",\n    \"impact_types\": [\n        \"string\"\n   \
          \ ],\n    \"last_updated_timestamp_in_usecs\": 0,\n    \"policies_to_override\": [\n        \"string\"\n    ],\n\
          \    \"related_policies\": [\n        {\n            \"entity_uuid\": \"string\",\n            \"policy_ids\": [\n\
          \                \"string\"\n            ]\n        }\n    ],\n    \"title\": \"string\",\n    \"trigger_conditions\"\
          : [\n        {\n            \"condition\": \"string\",\n            \"condition_type\": \"STATIC_THRESHOLD\",\n\
          \            \"severity_level\": \"CRITICAL\"\n        }\n    ],\n    \"trigger_wait_period_in_secs\": 0\n}\"\"\"\
          \n\nconn.request(\"POST\",\"/PrismGateway/services/rest/v2.0/alerts/policies/conflicting_policies\", payload, headers)\n\
          \nres = conn.getresponse()\ndata = res.read()\n\nprint(data.decode(\"utf-8\"))"
      - lang: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl\
          \ := \"https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/alerts/policies/conflicting_policies\"\n\t\n\tpayload\
          \ :=  strings.NewReader(`{\"auto_resolve\": true, \"created_by\": \"string\", \"description\": \"string\", \"enabled\"\
          : true, \"error_on_conflict\": true, \"filter\": \"string\", \"id\": \"string\", \"impact_types\": [\"string\"],\
          \ \"last_updated_timestamp_in_usecs\": 0, \"policies_to_override\": [\"string\"], \"related_policies\": [{\"entity_uuid\"\
          : \"string\", \"policy_ids\": [\"string\"]}], \"title\": \"string\", \"trigger_conditions\": [{\"condition\": \"\
          string\", \"condition_type\": \"STATIC_THRESHOLD\", \"severity_level\": \"CRITICAL\"}], \"trigger_wait_period_in_secs\"\
          : 0}`)\n\treq, err := http.NewRequest(\"POST\", url, payload)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating\
          \ request:\", err)\n\t\treturn\n\t}\n\n        req.Header.Add(\"Accept\", \"application/json\")\n        req.Header.Add(\"\
          Content-Type\", \"application/json\")\n    \n\tres, err := http.DefaultClient.Do(req)\n\tif err != nil {\n\t\tfmt.Println(\"\
          Error creating request:\", err)\n\t\treturn\n\t}\n\n\tdefer res.Body.Close()\n\tbody, err := io.ReadAll(res.Body)\n\
          \tif err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n\tfmt.Println(res)\n\t\
          fmt.Println(string(body))\n\n}"
      - lang: Java
        source: "AsyncHttpClient client = new DefaultAsyncHttpClient();\nclient.prepare(\"POST\", \"https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/alerts/policies/conflicting_policies\"\
          )\n  .setHeader(\"Accept\", \"application/json\")\n  .setHeader(\"Content-Type\", \"application/json\")\n  .setBody(\"\
          {\\\"auto_resolve\\\": true, \\\"created_by\\\": \\\"string\\\", \\\"description\\\": \\\"string\\\", \\\"enabled\\\
          \": true, \\\"error_on_conflict\\\": true, \\\"filter\\\": \\\"string\\\", \\\"id\\\": \\\"string\\\", \\\"impact_types\\\
          \": [\\\"string\\\"], \\\"last_updated_timestamp_in_usecs\\\": 0, \\\"policies_to_override\\\": [\\\"string\\\"\
          ], \\\"related_policies\\\": [{\\\"entity_uuid\\\": \\\"string\\\", \\\"policy_ids\\\": [\\\"string\\\"]}], \\\"\
          title\\\": \\\"string\\\", \\\"trigger_conditions\\\": [{\\\"condition\\\": \\\"string\\\", \\\"condition_type\\\
          \": \\\"STATIC_THRESHOLD\\\", \\\"severity_level\\\": \\\"CRITICAL\\\"}], \\\"trigger_wait_period_in_secs\\\": 0}\"\
          )\n  .execute()\n  .toCompletableFuture()\n  .thenAccept(System.out::println)\n  .join();\n\nclient.close();"
      - lang: JavaScript
        source: "const url = 'https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/alerts/policies/conflicting_policies';\n\
          const options = {\n  method: 'POST',\n  headers: {'Accept': 'application/json', 'Content-Type': 'application/json'},\n\
          \  body:  `{\"auto_resolve\": true, \"created_by\": \"string\", \"description\": \"string\", \"enabled\": true,\
          \ \"error_on_conflict\": true, \"filter\": \"string\", \"id\": \"string\", \"impact_types\": [\"string\"], \"last_updated_timestamp_in_usecs\"\
          : 0, \"policies_to_override\": [\"string\"], \"related_policies\": [{\"entity_uuid\": \"string\", \"policy_ids\"\
          : [\"string\"]}], \"title\": \"string\", \"trigger_conditions\": [{\"condition\": \"string\", \"condition_type\"\
          : \"STATIC_THRESHOLD\", \"severity_level\": \"CRITICAL\"}], \"trigger_wait_period_in_secs\": 0}`\n};\n\ntry {\n\
          \  const response = await fetch(url, options);\n  const data = await response.json();\n  console.log(data);\n} catch\
          \ (error) {\n  console.error(error);\n}"
components:
  schemas:
    create.base.EntityCollection_create.dto.alerts.AlertPolicyDTO_:
      type: object
      properties:
        entities:
          items:
            $ref: '#/components/schemas/create.dto.alerts.AlertPolicyDTO'
          type: array
        error_info:
          $ref: '#/components/schemas/create.base.ErrorInfo'
        metadata:
          $ref: '#/components/schemas/create.base.Metadata'
    create.base.Metadata:
      type: object
      properties:
        count:
          format: int32
          type: integer
        end_index:
          format: int32
          type: integer
        filter_criteria:
          type: string
        grand_total_entities:
          format: int32
          type: integer
        next_cursor:
          type: string
        page:
          format: int32
          type: integer
        previous_cursor:
          type: string
        search_string:
          type: string
        sort_criteria:
          type: string
        start_index:
          format: int32
          type: integer
        total_entities:
          format: int32
          type: integer
    create.base.ErrorInfo:
      type: object
      properties:
        count:
          format: int64
          type: integer
        entity_list:
          items:
            type: string
          type: array
        message:
          type: string
    create.dto.alerts.AlertPolicyDTO:
      type: object
      properties:
        auto_resolve:
          type: boolean
        created_by:
          type: string
        description:
          type: string
        enabled:
          type: boolean
        error_on_conflict:
          type: boolean
        filter:
          type: string
        id:
          type: string
        impact_types:
          items:
            type: string
          type: array
        last_updated_timestamp_in_usecs:
          format: int64
          type: integer
        policies_to_override:
          items:
            type: string
          type: array
        related_policies:
          items:
            $ref: '#/components/schemas/create.dto.alerts.AlertPolicyDTO_RelatedPolicies'
          type: array
        title:
          type: string
        trigger_conditions:
          items:
            $ref: '#/components/schemas/create.dto.alerts.AlertPolicyDTO_TriggerCondition'
          type: array
        trigger_wait_period_in_secs:
          format: int64
          type: integer
    create.dto.alerts.AlertPolicyDTO_TriggerCondition:
      type: object
      properties:
        condition:
          type: string
        condition_type:
          enum:
          - STATIC_THRESHOLD
          - ANOMALY
          - SAFETY_ZONE
          type: string
        severity_level:
          enum:
          - CRITICAL
          - WARNING
          - INFO
          - AUDIT
          type: string
    create.dto.alerts.AlertPolicyDTO_RelatedPolicies:
      type: object
      properties:
        entity_uuid:
          type: string
        policy_ids:
          items:
            type: string
          type: array
