openapi: 3.0.0
info:
  version: v2.0
  title: Nutanix Prism API Reference
  description: "# Introduction\n\nThe Nutanix REST APIs allow you to create scripts that run system administration commands\
    \ against the Nutanix cluster. The API enables the use of HTTP requests to get information about the cluster as well as\
    \ make changes to the configuration. Output from the API calls are returned in JSON format.\n\nAll API users should have\
    \ valid Prism login credentials to send API calls to the Prism server. APIs on nutanix.dev portal are publicly available\
    \ to all valid users without special permissions for viewing purposes.\n\nThe v2 API is an update of the v1 API. Users\
    \ of the v1 API are encouraged to migrate to v2. \n\n[Nutanix API versions \u2013 What are they and what does each one\
    \ do?](https://www.nutanix.dev/api-versions/)"
  contact:
    name: Nutanix, Inc.
    url: http://www.nutanix.com
  license:
    name: EULA
    url: http://www.nutanix.com/eula
servers:
- url: https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0
security: []
paths:
  /protection_domains/{pd_name}/consistency_groups/{cg_name}:
    put:
      summary: Updates Consistency Group for a specific protection domain.
      description: Updates Consistency Group for a specific protection domain.
      tags:
      - /protection_domains
      operationId: put/protection_domains/{pd_name}/consistency_groups/{cg_name}/updateConsistencyGroup
      parameters:
      - name: pd_name
        in: path
        description: Name of the Protection Domain
        required: true
        schema:
          type: string
      - name: cg_name
        in: path
        description: Name of the Consistency Group
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/update.dto.dr.ConsistencyGroupDTO'
        description: Consistency group details
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/update.dto.dr.ConsistencyGroupDTO'
        '500':
          description: Any internal exception while performing this operation
      x-codeSamples:
      - lang: cURL
        source: "curl --request PUT \\\n    --url https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/protection_domains/{pd_name}/consistency_groups/{cg_name}\
          \ \\\n    --header 'Accept: application/json' \\\n    --header 'Content-Type: application/json' \\\n    --data '{\n\
          \    \"app_consistent_snapshots\": true,\n    \"consistency_group_name\": \"string\",\n    \"marked_for_removal\"\
          : true,\n    \"nfs_file_count\": 0,\n    \"protection_domain_name\": \"string\",\n    \"total_file_count\": 0,\n\
          \    \"total_file_size_bytes\": 0,\n    \"vm_count\": 0,\n    \"within_snapshot\": true\n}'"
      - lang: Wget
        source: "wget --quiet \\\n    --method PUT \\\n    --header 'Accept: application/json' \\\n    --header 'Content-Type:\
          \ application/json' \\\n    --body-data '{\n    \"app_consistent_snapshots\": true,\n    \"consistency_group_name\"\
          : \"string\",\n    \"marked_for_removal\": true,\n    \"nfs_file_count\": 0,\n    \"protection_domain_name\": \"\
          string\",\n    \"total_file_count\": 0,\n    \"total_file_size_bytes\": 0,\n    \"vm_count\": 0,\n    \"within_snapshot\"\
          : true\n}' \\\n    --output-document \\\n    - https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/protection_domains/{pd_name}/consistency_groups/{cg_name}"
      - lang: Python
        source: "import http.client\n\nconn = http.client.HTTPSConnection(\"any_cvm_ip:9440\")\n\nheaders = {\n    \"Accept\"\
          : \"application/json\",\n    \"Content-Type\": \"application/json\"\n}\n\npayload =  \"\"\"{\n    \"app_consistent_snapshots\"\
          : true,\n    \"consistency_group_name\": \"string\",\n    \"marked_for_removal\": true,\n    \"nfs_file_count\"\
          : 0,\n    \"protection_domain_name\": \"string\",\n    \"total_file_count\": 0,\n    \"total_file_size_bytes\":\
          \ 0,\n    \"vm_count\": 0,\n    \"within_snapshot\": true\n}\"\"\"\n\nconn.request(\"PUT\",\"/PrismGateway/services/rest/v2.0/protection_domains/{pd_name}/consistency_groups/{cg_name}\"\
          , payload, headers)\n\nres = conn.getresponse()\ndata = res.read()\n\nprint(data.decode(\"utf-8\"))"
      - lang: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl\
          \ := \"https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/protection_domains/{pd_name}/consistency_groups/{cg_name}\"\
          \n\t\n\tpayload :=  strings.NewReader(`{\"app_consistent_snapshots\": true, \"consistency_group_name\": \"string\"\
          , \"marked_for_removal\": true, \"nfs_file_count\": 0, \"protection_domain_name\": \"string\", \"total_file_count\"\
          : 0, \"total_file_size_bytes\": 0, \"vm_count\": 0, \"within_snapshot\": true}`)\n\treq, err := http.NewRequest(\"\
          PUT\", url, payload)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n\
          \        req.Header.Add(\"Accept\", \"application/json\")\n        req.Header.Add(\"Content-Type\", \"application/json\"\
          )\n    \n\tres, err := http.DefaultClient.Do(req)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating request:\"\
          , err)\n\t\treturn\n\t}\n\n\tdefer res.Body.Close()\n\tbody, err := io.ReadAll(res.Body)\n\tif err != nil {\n\t\t\
          fmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n\tfmt.Println(res)\n\tfmt.Println(string(body))\n\
          \n}"
      - lang: Java
        source: "AsyncHttpClient client = new DefaultAsyncHttpClient();\nclient.prepare(\"PUT\", \"https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/protection_domains/{pd_name}/consistency_groups/{cg_name}\"\
          )\n  .setHeader(\"Accept\", \"application/json\")\n  .setHeader(\"Content-Type\", \"application/json\")\n  .setBody(\"\
          {\\\"app_consistent_snapshots\\\": true, \\\"consistency_group_name\\\": \\\"string\\\", \\\"marked_for_removal\\\
          \": true, \\\"nfs_file_count\\\": 0, \\\"protection_domain_name\\\": \\\"string\\\", \\\"total_file_count\\\": 0,\
          \ \\\"total_file_size_bytes\\\": 0, \\\"vm_count\\\": 0, \\\"within_snapshot\\\": true}\")\n  .execute()\n  .toCompletableFuture()\n\
          \  .thenAccept(System.out::println)\n  .join();\n\nclient.close();"
      - lang: JavaScript
        source: "const url = 'https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/protection_domains/{pd_name}/consistency_groups/{cg_name}';\n\
          const options = {\n  method: 'PUT',\n  headers: {'Accept': 'application/json', 'Content-Type': 'application/json'},\n\
          \  body:  `{\"app_consistent_snapshots\": true, \"consistency_group_name\": \"string\", \"marked_for_removal\":\
          \ true, \"nfs_file_count\": 0, \"protection_domain_name\": \"string\", \"total_file_count\": 0, \"total_file_size_bytes\"\
          : 0, \"vm_count\": 0, \"within_snapshot\": true}`\n};\n\ntry {\n  const response = await fetch(url, options);\n\
          \  const data = await response.json();\n  console.log(data);\n} catch (error) {\n  console.error(error);\n}"
components:
  schemas:
    update.dto.dr.ConsistencyGroupDTO:
      type: object
      properties:
        app_consistent_snapshots:
          type: boolean
        consistency_group_name:
          type: string
        marked_for_removal:
          type: boolean
        nfs_file_count:
          format: int32
          type: integer
        protection_domain_name:
          type: string
        total_file_count:
          format: int32
          type: integer
        total_file_size_bytes:
          format: int64
          type: integer
        vm_count:
          format: int32
          type: integer
        within_snapshot:
          type: boolean
