openapi: 3.0.0
info:
  version: v2.0
  title: Nutanix Prism API Reference
  description: "# Introduction\n\nThe Nutanix REST APIs allow you to create scripts that run system administration commands\
    \ against the Nutanix cluster. The API enables the use of HTTP requests to get information about the cluster as well as\
    \ make changes to the configuration. Output from the API calls are returned in JSON format.\n\nAll API users should have\
    \ valid Prism login credentials to send API calls to the Prism server. APIs on nutanix.dev portal are publicly available\
    \ to all valid users without special permissions for viewing purposes.\n\nThe v2 API is an update of the v1 API. Users\
    \ of the v1 API are encouraged to migrate to v2. \n\n[Nutanix API versions \u2013 What are they and what does each one\
    \ do?](https://www.nutanix.dev/api-versions/)"
  contact:
    name: Nutanix, Inc.
    url: http://www.nutanix.com
  license:
    name: EULA
    url: http://www.nutanix.com/eula
servers:
- url: https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0
security: []
paths:
  /cluster/domain_fault_tolerance_status:
    get:
      summary: List domain fault tolerance status for all the domains
      description: List domain fault tolerance status of the cluster for all the domains
      tags:
      - /cluster
      operationId: get/cluster/domain_fault_tolerance_status/getDomainFaultToleranceStatuses
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/get.dto.appliance.configuration.DomainFaultToleranceStatusDTO'
      x-codeSamples:
      - lang: cURL
        source: "curl --request GET \\\n    --url https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/cluster/domain_fault_tolerance_status\
          \ \\\n    --header 'Accept: application/json' \\\n    --header 'Content-Type: application/json' \\\n     "
      - lang: Wget
        source: "wget --quiet \\\n    --method GET \\\n    --header 'Accept: application/json' \\\n    --header 'Content-Type:\
          \ application/json' \\\n      \\\n    --output-document \\\n    - https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/cluster/domain_fault_tolerance_status"
      - lang: Python
        source: "import http.client\n\nconn = http.client.HTTPSConnection(\"any_cvm_ip:9440\")\n\nheaders = {\n    \"Accept\"\
          : \"application/json\",\n    \"Content-Type\": \"application/json\"\n}\n \nconn.request(\"GET\",\"/PrismGateway/services/rest/v2.0/cluster/domain_fault_tolerance_status\"\
          , headers=headers)\n\nres = conn.getresponse()\ndata = res.read()\n\nprint(data.decode(\"utf-8\"))"
      - lang: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl\
          \ := \"https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/cluster/domain_fault_tolerance_status\"\n\t \n\t\
          req, err := http.NewRequest(\"GET\", url, nil)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating request:\",\
          \ err)\n\t\treturn\n\t}\n\n        req.Header.Add(\"Accept\", \"application/json\")\n        req.Header.Add(\"Content-Type\"\
          , \"application/json\")\n    \n\tres, err := http.DefaultClient.Do(req)\n\tif err != nil {\n\t\tfmt.Println(\"Error\
          \ creating request:\", err)\n\t\treturn\n\t}\n\n\tdefer res.Body.Close()\n\tbody, err := io.ReadAll(res.Body)\n\t\
          if err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n\tfmt.Println(res)\n\tfmt.Println(string(body))\n\
          \n}"
      - lang: Java
        source: "AsyncHttpClient client = new DefaultAsyncHttpClient();\nclient.prepare(\"GET\", \"https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/cluster/domain_fault_tolerance_status\"\
          )\n  .setHeader(\"Accept\", \"application/json\")\n  .setHeader(\"Content-Type\", \"application/json\")\n  .execute()\n\
          \  .toCompletableFuture()\n  .thenAccept(System.out::println)\n  .join();\n\nclient.close();"
      - lang: JavaScript
        source: "const url = 'https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/cluster/domain_fault_tolerance_status';\n\
          const options = {\n  method: 'GET',\n  headers: {'Accept': 'application/json', 'Content-Type': 'application/json'}\
          \ \n};\n\ntry {\n  const response = await fetch(url, options);\n  const data = await response.json();\n  console.log(data);\n\
          } catch (error) {\n  console.error(error);\n}"
  /cluster/domain_fault_tolerance_status/{domainType}:
    get:
      summary: Get domain fault tolerance status for the specified domain
      description: Get domain fault tolerance status of the cluster for the specified domain
      tags:
      - /cluster
      operationId: get/cluster/domain_fault_tolerance_status/{domainType}/getDomainFaultToleranceStatus
      parameters:
      - name: domainType
        in: path
        description: Type of tolerance domain
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/get.dto.appliance.configuration.DomainFaultToleranceStatusDTO'
      x-codeSamples:
      - lang: cURL
        source: "curl --request GET \\\n    --url https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/cluster/domain_fault_tolerance_status/{domainType}\
          \ \\\n    --header 'Accept: application/json' \\\n    --header 'Content-Type: application/json' \\\n     "
      - lang: Wget
        source: "wget --quiet \\\n    --method GET \\\n    --header 'Accept: application/json' \\\n    --header 'Content-Type:\
          \ application/json' \\\n      \\\n    --output-document \\\n    - https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/cluster/domain_fault_tolerance_status/{domainType}"
      - lang: Python
        source: "import http.client\n\nconn = http.client.HTTPSConnection(\"any_cvm_ip:9440\")\n\nheaders = {\n    \"Accept\"\
          : \"application/json\",\n    \"Content-Type\": \"application/json\"\n}\n \nconn.request(\"GET\",\"/PrismGateway/services/rest/v2.0/cluster/domain_fault_tolerance_status/{domainType}\"\
          , headers=headers)\n\nres = conn.getresponse()\ndata = res.read()\n\nprint(data.decode(\"utf-8\"))"
      - lang: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl\
          \ := \"https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/cluster/domain_fault_tolerance_status/{domainType}\"\
          \n\t \n\treq, err := http.NewRequest(\"GET\", url, nil)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating request:\"\
          , err)\n\t\treturn\n\t}\n\n        req.Header.Add(\"Accept\", \"application/json\")\n        req.Header.Add(\"Content-Type\"\
          , \"application/json\")\n    \n\tres, err := http.DefaultClient.Do(req)\n\tif err != nil {\n\t\tfmt.Println(\"Error\
          \ creating request:\", err)\n\t\treturn\n\t}\n\n\tdefer res.Body.Close()\n\tbody, err := io.ReadAll(res.Body)\n\t\
          if err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n\tfmt.Println(res)\n\tfmt.Println(string(body))\n\
          \n}"
      - lang: Java
        source: "AsyncHttpClient client = new DefaultAsyncHttpClient();\nclient.prepare(\"GET\", \"https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/cluster/domain_fault_tolerance_status/{domainType}\"\
          )\n  .setHeader(\"Accept\", \"application/json\")\n  .setHeader(\"Content-Type\", \"application/json\")\n  .execute()\n\
          \  .toCompletableFuture()\n  .thenAccept(System.out::println)\n  .join();\n\nclient.close();"
      - lang: JavaScript
        source: "const url = 'https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/cluster/domain_fault_tolerance_status/{domainType}';\n\
          const options = {\n  method: 'GET',\n  headers: {'Accept': 'application/json', 'Content-Type': 'application/json'}\
          \ \n};\n\ntry {\n  const response = await fetch(url, options);\n  const data = await response.json();\n  console.log(data);\n\
          } catch (error) {\n  console.error(error);\n}"
components:
  schemas:
    get.dto.base.ParameterizedMessageDTO:
      type: object
      properties:
        attributes:
          additionalProperties:
            type: string
          type: object
        message:
          type: string
    get.dto.appliance.configuration.DomainFaultToleranceStatusDTO:
      type: object
      properties:
        cluster_non_fault_tolerant_entries:
          format: int64
          type: integer
        cluster_under_replicated_data_bytes:
          format: int64
          type: integer
        component_fault_tolerance_status:
          additionalProperties:
            $ref: '#/components/schemas/get.dto.appliance.configuration.ComponentFaultToleranceStatusDTO'
          type: object
        domain_type:
          enum:
          - RACK
          - RACKABLE_UNIT
          - NODE
          - DISK
          - CLUSTER
          - CUSTOM
          type: string
    get.dto.appliance.configuration.ComponentFaultToleranceStatusDTO:
      type: object
      properties:
        component_type:
          enum:
          - EXTENT_GROUPS
          - OPLOG
          - METADATA
          - ZOOKEEPER
          - FREE_SPACE
          - STATIC_CONFIGURATION
          - ERASURE_CODE_STRIP_SIZE
          - STARGATE_HEALTH
          type: string
        details:
          $ref: '#/components/schemas/get.dto.base.ParameterizedMessageDTO'
        last_updated_time_in_usecs:
          format: int64
          type: integer
        number_of_failures_tolerable:
          format: int32
          type: integer
        under_computation:
          type: boolean
