openapi: 3.0.0
info:
  version: v2.0
  title: Nutanix Prism API Reference
  description: "# Introduction\n\nThe Nutanix REST APIs allow you to create scripts that run system administration commands\
    \ against the Nutanix cluster. The API enables the use of HTTP requests to get information about the cluster as well as\
    \ make changes to the configuration. Output from the API calls are returned in JSON format.\n\nAll API users should have\
    \ valid Prism login credentials to send API calls to the Prism server. APIs on nutanix.dev portal are publicly available\
    \ to all valid users without special permissions for viewing purposes.\n\nThe v2 API is an update of the v1 API. Users\
    \ of the v1 API are encouraged to migrate to v2. \n\n[Nutanix API versions \u2013 What are they and what does each one\
    \ do?](https://www.nutanix.dev/api-versions/)"
  contact:
    name: Nutanix, Inc.
    url: http://www.nutanix.com
  license:
    name: EULA
    url: http://www.nutanix.com/eula
servers:
- url: https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0
security: []
paths:
  /ha:
    get:
      summary: Get current HA configuration.
      tags:
      - /ha
      operationId: get/ha/getHaConfig
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/get.dto.acropolis.HaConfigDTO'
      x-codeSamples:
      - lang: cURL
        source: "curl --request GET \\\n    --url https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/ha \\\n    --header\
          \ 'Accept: application/json' \\\n    --header 'Content-Type: application/json' \\\n     "
      - lang: Wget
        source: "wget --quiet \\\n    --method GET \\\n    --header 'Accept: application/json' \\\n    --header 'Content-Type:\
          \ application/json' \\\n      \\\n    --output-document \\\n    - https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/ha"
      - lang: Python
        source: "import http.client\n\nconn = http.client.HTTPSConnection(\"any_cvm_ip:9440\")\n\nheaders = {\n    \"Accept\"\
          : \"application/json\",\n    \"Content-Type\": \"application/json\"\n}\n \nconn.request(\"GET\",\"/PrismGateway/services/rest/v2.0/ha\"\
          , headers=headers)\n\nres = conn.getresponse()\ndata = res.read()\n\nprint(data.decode(\"utf-8\"))"
      - lang: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl\
          \ := \"https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/ha\"\n\t \n\treq, err := http.NewRequest(\"GET\"\
          , url, nil)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n        req.Header.Add(\"\
          Accept\", \"application/json\")\n        req.Header.Add(\"Content-Type\", \"application/json\")\n    \n\tres, err\
          \ := http.DefaultClient.Do(req)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\
          \t}\n\n\tdefer res.Body.Close()\n\tbody, err := io.ReadAll(res.Body)\n\tif err != nil {\n\t\tfmt.Println(\"Error\
          \ creating request:\", err)\n\t\treturn\n\t}\n\n\tfmt.Println(res)\n\tfmt.Println(string(body))\n\n}"
      - lang: Java
        source: "AsyncHttpClient client = new DefaultAsyncHttpClient();\nclient.prepare(\"GET\", \"https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/ha\"\
          )\n  .setHeader(\"Accept\", \"application/json\")\n  .setHeader(\"Content-Type\", \"application/json\")\n  .execute()\n\
          \  .toCompletableFuture()\n  .thenAccept(System.out::println)\n  .join();\n\nclient.close();"
      - lang: JavaScript
        source: "const url = 'https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/ha';\nconst options = {\n  method: 'GET',\n\
          \  headers: {'Accept': 'application/json', 'Content-Type': 'application/json'} \n};\n\ntry {\n  const response =\
          \ await fetch(url, options);\n  const data = await response.json();\n  console.log(data);\n} catch (error) {\n \
          \ console.error(error);\n}"
    put:
      summary: Enable, disable or modify HA configuration.
      tags:
      - /ha
      operationId: put/ha/updateHaConfig
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/update.dto.acropolis.HaUpdateDTO'
        description: HA configuration
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/update.dto.acropolis.ReturnValueDTO_TaskIdDTO'
      x-codeSamples:
      - lang: cURL
        source: "curl --request PUT \\\n    --url https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/ha \\\n    --header\
          \ 'Accept: application/json' \\\n    --header 'Content-Type: application/json' \\\n    --data '{\n    \"enable_failover\"\
          : true,\n    \"evacuation_option\": \"POWER_OFF\",\n    \"logical_timestamp\": 0,\n    \"num_host_failures_to_tolerate\"\
          : 0,\n    \"reservation_type\": \"RESERVE_HOSTS\"\n}'"
      - lang: Wget
        source: "wget --quiet \\\n    --method PUT \\\n    --header 'Accept: application/json' \\\n    --header 'Content-Type:\
          \ application/json' \\\n    --body-data '{\n    \"enable_failover\": true,\n    \"evacuation_option\": \"POWER_OFF\"\
          ,\n    \"logical_timestamp\": 0,\n    \"num_host_failures_to_tolerate\": 0,\n    \"reservation_type\": \"RESERVE_HOSTS\"\
          \n}' \\\n    --output-document \\\n    - https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/ha"
      - lang: Python
        source: "import http.client\n\nconn = http.client.HTTPSConnection(\"any_cvm_ip:9440\")\n\nheaders = {\n    \"Accept\"\
          : \"application/json\",\n    \"Content-Type\": \"application/json\"\n}\n\npayload =  \"\"\"{\n    \"enable_failover\"\
          : true,\n    \"evacuation_option\": \"POWER_OFF\",\n    \"logical_timestamp\": 0,\n    \"num_host_failures_to_tolerate\"\
          : 0,\n    \"reservation_type\": \"RESERVE_HOSTS\"\n}\"\"\"\n\nconn.request(\"PUT\",\"/PrismGateway/services/rest/v2.0/ha\"\
          , payload, headers)\n\nres = conn.getresponse()\ndata = res.read()\n\nprint(data.decode(\"utf-8\"))"
      - lang: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl\
          \ := \"https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/ha\"\n\t\n\tpayload :=  strings.NewReader(`{\"enable_failover\"\
          : true, \"evacuation_option\": \"POWER_OFF\", \"logical_timestamp\": 0, \"num_host_failures_to_tolerate\": 0, \"\
          reservation_type\": \"RESERVE_HOSTS\"}`)\n\treq, err := http.NewRequest(\"PUT\", url, payload)\n\tif err != nil\
          \ {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n        req.Header.Add(\"Accept\", \"\
          application/json\")\n        req.Header.Add(\"Content-Type\", \"application/json\")\n    \n\tres, err := http.DefaultClient.Do(req)\n\
          \tif err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n\tdefer res.Body.Close()\n\
          \tbody, err := io.ReadAll(res.Body)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\t\
          return\n\t}\n\n\tfmt.Println(res)\n\tfmt.Println(string(body))\n\n}"
      - lang: Java
        source: "AsyncHttpClient client = new DefaultAsyncHttpClient();\nclient.prepare(\"PUT\", \"https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/ha\"\
          )\n  .setHeader(\"Accept\", \"application/json\")\n  .setHeader(\"Content-Type\", \"application/json\")\n  .setBody(\"\
          {\\\"enable_failover\\\": true, \\\"evacuation_option\\\": \\\"POWER_OFF\\\", \\\"logical_timestamp\\\": 0, \\\"\
          num_host_failures_to_tolerate\\\": 0, \\\"reservation_type\\\": \\\"RESERVE_HOSTS\\\"}\")\n  .execute()\n  .toCompletableFuture()\n\
          \  .thenAccept(System.out::println)\n  .join();\n\nclient.close();"
      - lang: JavaScript
        source: "const url = 'https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/ha';\nconst options = {\n  method: 'PUT',\n\
          \  headers: {'Accept': 'application/json', 'Content-Type': 'application/json'},\n  body:  `{\"enable_failover\"\
          : true, \"evacuation_option\": \"POWER_OFF\", \"logical_timestamp\": 0, \"num_host_failures_to_tolerate\": 0, \"\
          reservation_type\": \"RESERVE_HOSTS\"}`\n};\n\ntry {\n  const response = await fetch(url, options);\n  const data\
          \ = await response.json();\n  console.log(data);\n} catch (error) {\n  console.error(error);\n}"
components:
  schemas:
    update.dto.acropolis.ReturnValueDTO_TaskIdDTO:
      type: object
      properties:
        task_uuid:
          type: string
    update.dto.acropolis.HaUpdateDTO:
      type: object
      properties:
        enable_failover:
          type: boolean
        evacuation_option:
          enum:
          - POWER_OFF
          - COLD_MIGRATE
          - LIVE_MIGRATE
          type: string
        logical_timestamp:
          format: int64
          type: integer
        num_host_failures_to_tolerate:
          format: int64
          type: integer
        reservation_type:
          enum:
          - RESERVE_HOSTS
          - RESERVE_SEGMENTS
          - NO_RESERVATIONS
          type: string
    get.dto.acropolis.HaConfigDTO:
      type: object
      properties:
        failover_enabled:
          type: boolean
        failover_in_progress_host_uuids:
          items:
            type: string
          type: array
        ha_state:
          enum:
          - HIGHLY_AVAILABLE
          - HEALING
          - BEST_EFFORT
          - DISABLED
          type: string
        logical_timestamp:
          format: int64
          type: integer
        num_host_failures_to_tolerate:
          format: int64
          type: integer
        reservation_type:
          enum:
          - RESERVE_HOSTS
          - RESERVE_SEGMENTS
          - NO_RESERVATIONS
          type: string
        reserved_host_uuids:
          items:
            type: string
          type: array
