openapi: 3.0.0
info:
  version: v2.0
  title: Nutanix Prism API Reference
  description: "# Introduction\n\nThe Nutanix REST APIs allow you to create scripts that run system administration commands\
    \ against the Nutanix cluster. The API enables the use of HTTP requests to get information about the cluster as well as\
    \ make changes to the configuration. Output from the API calls are returned in JSON format.\n\nAll API users should have\
    \ valid Prism login credentials to send API calls to the Prism server. APIs on nutanix.dev portal are publicly available\
    \ to all valid users without special permissions for viewing purposes.\n\nThe v2 API is an update of the v1 API. Users\
    \ of the v1 API are encouraged to migrate to v2. \n\n[Nutanix API versions \u2013 What are they and what does each one\
    \ do?](https://www.nutanix.dev/api-versions/)"
  contact:
    name: Nutanix, Inc.
    url: http://www.nutanix.com
  license:
    name: EULA
    url: http://www.nutanix.com/eula
servers:
- url: https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0
security: []
paths:
  /hosts/{uuid}/host_gpus/{gpu_uuid}/stats:
    get:
      summary: Get stats for a particular GPU for a physical Host.
      description: Get stats for a particular GPU for a physical Host.
      tags:
      - /hosts
      operationId: get/hosts/{uuid}/host_gpus/{gpu_uuid}/stats/getHostGpuStats
      parameters:
      - name: uuid
        in: path
        description: Uuid of the Host
        required: true
        schema:
          type: string
      - name: gpu_uuid
        in: path
        description: UUID of the Host GPU
        required: true
        schema:
          type: string
      - name: metrics
        in: query
        description: List of metrics
        required: true
        style: form
        explode: false
        schema:
          type: array
          items:
            type: string
      - name: start_time_in_usecs
        in: query
        description: Start time in microseconds
        required: false
        schema:
          type: integer
          format: int64
      - name: end_time_in_usecs
        in: query
        description: End time in microseconds
        required: false
        schema:
          type: integer
          format: int64
      - name: interval_in_secs
        in: query
        description: Sampling interval of stats
        required: false
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/get.data.StatsResponse'
      x-codeSamples:
      - lang: cURL
        source: "curl --request GET \\\n    --url https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/hosts/{uuid}/host_gpus/{gpu_uuid}/stats\
          \ \\\n    --header 'Accept: application/json' \\\n    --header 'Content-Type: application/json' \\\n     "
      - lang: Wget
        source: "wget --quiet \\\n    --method GET \\\n    --header 'Accept: application/json' \\\n    --header 'Content-Type:\
          \ application/json' \\\n      \\\n    --output-document \\\n    - https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/hosts/{uuid}/host_gpus/{gpu_uuid}/stats"
      - lang: Python
        source: "import http.client\n\nconn = http.client.HTTPSConnection(\"any_cvm_ip:9440\")\n\nheaders = {\n    \"Accept\"\
          : \"application/json\",\n    \"Content-Type\": \"application/json\"\n}\n \nconn.request(\"GET\",\"/PrismGateway/services/rest/v2.0/hosts/{uuid}/host_gpus/{gpu_uuid}/stats\"\
          , headers=headers)\n\nres = conn.getresponse()\ndata = res.read()\n\nprint(data.decode(\"utf-8\"))"
      - lang: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl\
          \ := \"https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/hosts/{uuid}/host_gpus/{gpu_uuid}/stats\"\n\t \n\t\
          req, err := http.NewRequest(\"GET\", url, nil)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating request:\",\
          \ err)\n\t\treturn\n\t}\n\n        req.Header.Add(\"Accept\", \"application/json\")\n        req.Header.Add(\"Content-Type\"\
          , \"application/json\")\n    \n\tres, err := http.DefaultClient.Do(req)\n\tif err != nil {\n\t\tfmt.Println(\"Error\
          \ creating request:\", err)\n\t\treturn\n\t}\n\n\tdefer res.Body.Close()\n\tbody, err := io.ReadAll(res.Body)\n\t\
          if err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n\tfmt.Println(res)\n\tfmt.Println(string(body))\n\
          \n}"
      - lang: Java
        source: "AsyncHttpClient client = new DefaultAsyncHttpClient();\nclient.prepare(\"GET\", \"https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/hosts/{uuid}/host_gpus/{gpu_uuid}/stats\"\
          )\n  .setHeader(\"Accept\", \"application/json\")\n  .setHeader(\"Content-Type\", \"application/json\")\n  .execute()\n\
          \  .toCompletableFuture()\n  .thenAccept(System.out::println)\n  .join();\n\nclient.close();"
      - lang: JavaScript
        source: "const url = 'https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/hosts/{uuid}/host_gpus/{gpu_uuid}/stats';\n\
          const options = {\n  method: 'GET',\n  headers: {'Accept': 'application/json', 'Content-Type': 'application/json'}\
          \ \n};\n\ntry {\n  const response = await fetch(url, options);\n  const data = await response.json();\n  console.log(data);\n\
          } catch (error) {\n  console.error(error);\n}"
components:
  schemas:
    get.data.StatsResponse:
      type: object
      properties:
        stats_specific_responses:
          items:
            $ref: '#/components/schemas/get.data.StatsResponse_StatsSpecificResponse'
          type: array
    get.data.StatsResponse_StatsSpecificResponse:
      type: object
      properties:
        interval_in_secs:
          format: int64
          type: integer
        message:
          type: string
        metric:
          type: string
        start_time_in_usecs:
          format: int64
          type: integer
        successful:
          type: boolean
        values:
          items:
            format: int64
            type: integer
          type: array
