openapi: 3.0.0
info:
  version: v2.0
  title: Nutanix Prism API Reference
  description: "# Introduction\n\nThe Nutanix REST APIs allow you to create scripts that run system administration commands\
    \ against the Nutanix cluster. The API enables the use of HTTP requests to get information about the cluster as well as\
    \ make changes to the configuration. Output from the API calls are returned in JSON format.\n\nAll API users should have\
    \ valid Prism login credentials to send API calls to the Prism server. APIs on nutanix.dev portal are publicly available\
    \ to all valid users without special permissions for viewing purposes.\n\nThe v2 API is an update of the v1 API. Users\
    \ of the v1 API are encouraged to migrate to v2. \n\n[Nutanix API versions \u2013 What are they and what does each one\
    \ do?](https://www.nutanix.dev/api-versions/)"
  contact:
    name: Nutanix, Inc.
    url: http://www.nutanix.com
  license:
    name: EULA
    url: http://www.nutanix.com/eula
servers:
- url: https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0
security: []
paths:
  /authconfig/remove_auth_types:
    post:
      summary: Remove Auth types.
      description: Remove Auth types from the existing Auth types.
      tags:
      - /authconfig
      operationId: post/authconfig/remove_auth_types/deleteAuthTypes
      requestBody:
        $ref: '#/components/requestBodies/post_authconfig_add_auth_types_addAuthTypesArg0'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  enum:
                  - LOCAL
                  - DIRECTORY_SERVICE
                  type: string
      x-codeSamples:
      - lang: cURL
        source: "curl --request POST \\\n    --url https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/authconfig/remove_auth_types\
          \ \\\n    --header 'Accept: application/json' \\\n    --header 'Content-Type: application/json' \\\n     "
      - lang: Wget
        source: "wget --quiet \\\n    --method POST \\\n    --header 'Accept: application/json' \\\n    --header 'Content-Type:\
          \ application/json' \\\n      \\\n    --output-document \\\n    - https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/authconfig/remove_auth_types"
      - lang: Python
        source: "import http.client\n\nconn = http.client.HTTPSConnection(\"any_cvm_ip:9440\")\n\nheaders = {\n    \"Accept\"\
          : \"application/json\",\n    \"Content-Type\": \"application/json\"\n}\n\npayload =  \"\"\"{}\"\"\"\n\nconn.request(\"\
          POST\",\"/PrismGateway/services/rest/v2.0/authconfig/remove_auth_types\", payload, headers)\n\nres = conn.getresponse()\n\
          data = res.read()\n\nprint(data.decode(\"utf-8\"))"
      - lang: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl\
          \ := \"https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/authconfig/remove_auth_types\"\n\t \n\treq, err :=\
          \ http.NewRequest(\"POST\", url, nil)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\t\
          return\n\t}\n\n        req.Header.Add(\"Accept\", \"application/json\")\n        req.Header.Add(\"Content-Type\"\
          , \"application/json\")\n    \n\tres, err := http.DefaultClient.Do(req)\n\tif err != nil {\n\t\tfmt.Println(\"Error\
          \ creating request:\", err)\n\t\treturn\n\t}\n\n\tdefer res.Body.Close()\n\tbody, err := io.ReadAll(res.Body)\n\t\
          if err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n\tfmt.Println(res)\n\tfmt.Println(string(body))\n\
          \n}"
      - lang: Java
        source: "AsyncHttpClient client = new DefaultAsyncHttpClient();\nclient.prepare(\"POST\", \"https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/authconfig/remove_auth_types\"\
          )\n  .setHeader(\"Accept\", \"application/json\")\n  .setHeader(\"Content-Type\", \"application/json\")\n  .execute()\n\
          \  .toCompletableFuture()\n  .thenAccept(System.out::println)\n  .join();\n\nclient.close();"
      - lang: JavaScript
        source: "const url = 'https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/authconfig/remove_auth_types';\nconst\
          \ options = {\n  method: 'POST',\n  headers: {'Accept': 'application/json', 'Content-Type': 'application/json'}\
          \ \n};\n\ntry {\n  const response = await fetch(url, options);\n  const data = await response.json();\n  console.log(data);\n\
          } catch (error) {\n  console.error(error);\n}"
components:
  requestBodies:
    post_authconfig_add_auth_types_addAuthTypesArg0:
      content:
        application/json:
          schema:
            type: array
            items:
              enum:
              - LOCAL
              - DIRECTORY_SERVICE
              type: string
      description: List of Auth types
      required: true
