openapi: 3.0.0
info:
  version: v2.0
  title: Nutanix Prism API Reference
  description: "# Introduction\n\nThe Nutanix REST APIs allow you to create scripts that run system administration commands\
    \ against the Nutanix cluster. The API enables the use of HTTP requests to get information about the cluster as well as\
    \ make changes to the configuration. Output from the API calls are returned in JSON format.\n\nAll API users should have\
    \ valid Prism login credentials to send API calls to the Prism server. APIs on nutanix.dev portal are publicly available\
    \ to all valid users without special permissions for viewing purposes.\n\nThe v2 API is an update of the v1 API. Users\
    \ of the v1 API are encouraged to migrate to v2. \n\n[Nutanix API versions \u2013 What are they and what does each one\
    \ do?](https://www.nutanix.dev/api-versions/)"
  contact:
    name: Nutanix, Inc.
    url: http://www.nutanix.com
  license:
    name: EULA
    url: http://www.nutanix.com/eula
servers:
- url: https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0
security: []
paths:
  /protection_domains/{name}/replications:
    get:
      summary: Get list of replications in a Protection Domain.
      tags:
      - /protection_domains
      operationId: get/protection_domains/{name}/replications/getReplicationsForPd
      parameters:
      - name: name
        in: path
        description: Name of the Protection Domain
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/get.base.EntityCollection_get.dto.dr.ReplicationDTO_'
      x-codeSamples:
      - lang: cURL
        source: "curl --request GET \\\n    --url https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/protection_domains/{name}/replications\
          \ \\\n    --header 'Accept: application/json' \\\n    --header 'Content-Type: application/json' \\\n     "
      - lang: Wget
        source: "wget --quiet \\\n    --method GET \\\n    --header 'Accept: application/json' \\\n    --header 'Content-Type:\
          \ application/json' \\\n      \\\n    --output-document \\\n    - https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/protection_domains/{name}/replications"
      - lang: Python
        source: "import http.client\n\nconn = http.client.HTTPSConnection(\"any_cvm_ip:9440\")\n\nheaders = {\n    \"Accept\"\
          : \"application/json\",\n    \"Content-Type\": \"application/json\"\n}\n \nconn.request(\"GET\",\"/PrismGateway/services/rest/v2.0/protection_domains/{name}/replications\"\
          , headers=headers)\n\nres = conn.getresponse()\ndata = res.read()\n\nprint(data.decode(\"utf-8\"))"
      - lang: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl\
          \ := \"https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/protection_domains/{name}/replications\"\n\t \n\t\
          req, err := http.NewRequest(\"GET\", url, nil)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating request:\",\
          \ err)\n\t\treturn\n\t}\n\n        req.Header.Add(\"Accept\", \"application/json\")\n        req.Header.Add(\"Content-Type\"\
          , \"application/json\")\n    \n\tres, err := http.DefaultClient.Do(req)\n\tif err != nil {\n\t\tfmt.Println(\"Error\
          \ creating request:\", err)\n\t\treturn\n\t}\n\n\tdefer res.Body.Close()\n\tbody, err := io.ReadAll(res.Body)\n\t\
          if err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n\tfmt.Println(res)\n\tfmt.Println(string(body))\n\
          \n}"
      - lang: Java
        source: "AsyncHttpClient client = new DefaultAsyncHttpClient();\nclient.prepare(\"GET\", \"https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/protection_domains/{name}/replications\"\
          )\n  .setHeader(\"Accept\", \"application/json\")\n  .setHeader(\"Content-Type\", \"application/json\")\n  .execute()\n\
          \  .toCompletableFuture()\n  .thenAccept(System.out::println)\n  .join();\n\nclient.close();"
      - lang: JavaScript
        source: "const url = 'https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/protection_domains/{name}/replications';\n\
          const options = {\n  method: 'GET',\n  headers: {'Accept': 'application/json', 'Content-Type': 'application/json'}\
          \ \n};\n\ntry {\n  const response = await fetch(url, options);\n  const data = await response.json();\n  console.log(data);\n\
          } catch (error) {\n  console.error(error);\n}"
components:
  schemas:
    get.base.ErrorInfo:
      type: object
      properties:
        count:
          format: int64
          type: integer
        entity_list:
          items:
            type: string
          type: array
        message:
          type: string
    get.base.EntityCollection_get.dto.dr.ReplicationDTO_:
      type: object
      properties:
        entities:
          items:
            $ref: '#/components/schemas/get.dto.dr.ReplicationDTO'
          type: array
        error_info:
          $ref: '#/components/schemas/get.base.ErrorInfo'
        metadata:
          $ref: '#/components/schemas/get.base.Metadata'
    get.base.Metadata:
      type: object
      properties:
        count:
          format: int32
          type: integer
        end_index:
          format: int32
          type: integer
        filter_criteria:
          type: string
        grand_total_entities:
          format: int32
          type: integer
        next_cursor:
          type: string
        page:
          format: int32
          type: integer
        previous_cursor:
          type: string
        search_string:
          type: string
        sort_criteria:
          type: string
        start_index:
          format: int32
          type: integer
        total_entities:
          format: int32
          type: integer
    get.dto.dr.ReplicationDTO:
      type: object
      properties:
        aborted:
          type: boolean
        completed_bytes:
          format: int64
          type: integer
        completed_percentage:
          format: float
          type: number
        id:
          format: int64
          type: integer
        paused:
          type: boolean
        protection_domain_name:
          type: string
        remote_site_name:
          type: string
        replication_time_to_complete_secs:
          format: int64
          type: integer
        sender:
          type: boolean
        snapshot_id:
          type: string
        start_replication_time_usecs:
          format: int64
          type: integer
