openapi: 3.0.0
info:
  version: v2.0
  title: Nutanix Prism API Reference
  description: "# Introduction\n\nThe Nutanix REST APIs allow you to create scripts that run system administration commands\
    \ against the Nutanix cluster. The API enables the use of HTTP requests to get information about the cluster as well as\
    \ make changes to the configuration. Output from the API calls are returned in JSON format.\n\nAll API users should have\
    \ valid Prism login credentials to send API calls to the Prism server. APIs on nutanix.dev portal are publicly available\
    \ to all valid users without special permissions for viewing purposes.\n\nThe v2 API is an update of the v1 API. Users\
    \ of the v1 API are encouraged to migrate to v2. \n\n[Nutanix API versions \u2013 What are they and what does each one\
    \ do?](https://www.nutanix.dev/api-versions/)"
  contact:
    name: Nutanix, Inc.
    url: http://www.nutanix.com
  license:
    name: EULA
    url: http://www.nutanix.com/eula
servers:
- url: https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0
security: []
paths:
  /vms/{uuid}/set_power_state:
    post:
      summary: Set power state of a Virtual Machine.
      description: Set power state of a Virtual Machine. If the Virtual Machine is being powered on and no host is specified,
        the scheduler will pick the one with the most available CPU and memory that can support the Virtual Machine. Note
        that no such host may not be available. If the Virtual Machine is being power cycled, a different host can be specified
        to start it on. The logical timestamp can optionally be provided for consistency. If a logical timestamp is specified,
        then this operation will be rejected if the logical timestamp specified is not the value of the Virtual Machine logical
        timestamp. The logical timestamp can be obtained from the Virtual Machine object. This is also an asynchronous operation
        that results in the creation of a task object. The UUID of this task object is returned as the response of this operation.
        This task can be monitored by using the /tasks/poll API.
      tags:
      - /vms
      operationId: post/vms/{uuid}/set_power_state/setPowerState
      parameters:
      - name: uuid
        in: path
        description: Id of the Virtual Machine
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create.dto.uhura.VMPowerStateDTO'
        description: Virtual Machine Power State Info
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/create.dto.acropolis.ReturnValueDTO_TaskIdDTO'
      x-codeSamples:
      - lang: cURL
        source: "curl --request POST \\\n    --url https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/vms/{uuid}/set_power_state\
          \ \\\n    --header 'Accept: application/json' \\\n    --header 'Content-Type: application/json' \\\n    --data '{\n\
          \    \"host_uuid\": \"string\",\n    \"transition\": \"ON\",\n    \"uuid\": \"string\",\n    \"vm_logical_timestamp\"\
          : 0\n}'"
      - lang: Wget
        source: "wget --quiet \\\n    --method POST \\\n    --header 'Accept: application/json' \\\n    --header 'Content-Type:\
          \ application/json' \\\n    --body-data '{\n    \"host_uuid\": \"string\",\n    \"transition\": \"ON\",\n    \"\
          uuid\": \"string\",\n    \"vm_logical_timestamp\": 0\n}' \\\n    --output-document \\\n    - https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/vms/{uuid}/set_power_state"
      - lang: Python
        source: "import http.client\n\nconn = http.client.HTTPSConnection(\"any_cvm_ip:9440\")\n\nheaders = {\n    \"Accept\"\
          : \"application/json\",\n    \"Content-Type\": \"application/json\"\n}\n\npayload =  \"\"\"{\n    \"host_uuid\"\
          : \"string\",\n    \"transition\": \"ON\",\n    \"uuid\": \"string\",\n    \"vm_logical_timestamp\": 0\n}\"\"\"\n\
          \nconn.request(\"POST\",\"/PrismGateway/services/rest/v2.0/vms/{uuid}/set_power_state\", payload, headers)\n\nres\
          \ = conn.getresponse()\ndata = res.read()\n\nprint(data.decode(\"utf-8\"))"
      - lang: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl\
          \ := \"https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/vms/{uuid}/set_power_state\"\n\t\n\tpayload :=  strings.NewReader(`{\"\
          host_uuid\": \"string\", \"transition\": \"ON\", \"uuid\": \"string\", \"vm_logical_timestamp\": 0}`)\n\treq, err\
          \ := http.NewRequest(\"POST\", url, payload)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\
          \t\treturn\n\t}\n\n        req.Header.Add(\"Accept\", \"application/json\")\n        req.Header.Add(\"Content-Type\"\
          , \"application/json\")\n    \n\tres, err := http.DefaultClient.Do(req)\n\tif err != nil {\n\t\tfmt.Println(\"Error\
          \ creating request:\", err)\n\t\treturn\n\t}\n\n\tdefer res.Body.Close()\n\tbody, err := io.ReadAll(res.Body)\n\t\
          if err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n\tfmt.Println(res)\n\tfmt.Println(string(body))\n\
          \n}"
      - lang: Java
        source: "AsyncHttpClient client = new DefaultAsyncHttpClient();\nclient.prepare(\"POST\", \"https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/vms/{uuid}/set_power_state\"\
          )\n  .setHeader(\"Accept\", \"application/json\")\n  .setHeader(\"Content-Type\", \"application/json\")\n  .setBody(\"\
          {\\\"host_uuid\\\": \\\"string\\\", \\\"transition\\\": \\\"ON\\\", \\\"uuid\\\": \\\"string\\\", \\\"vm_logical_timestamp\\\
          \": 0}\")\n  .execute()\n  .toCompletableFuture()\n  .thenAccept(System.out::println)\n  .join();\n\nclient.close();"
      - lang: JavaScript
        source: "const url = 'https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/vms/{uuid}/set_power_state';\nconst\
          \ options = {\n  method: 'POST',\n  headers: {'Accept': 'application/json', 'Content-Type': 'application/json'},\n\
          \  body:  `{\"host_uuid\": \"string\", \"transition\": \"ON\", \"uuid\": \"string\", \"vm_logical_timestamp\": 0}`\n\
          };\n\ntry {\n  const response = await fetch(url, options);\n  const data = await response.json();\n  console.log(data);\n\
          } catch (error) {\n  console.error(error);\n}"
components:
  schemas:
    create.dto.uhura.VMPowerStateDTO:
      type: object
      properties:
        host_uuid:
          type: string
        transition:
          enum:
          - 'ON'
          - 'OFF'
          - POWERCYCLE
          - RESET
          - PAUSE
          - SUSPEND
          - RESUME
          - SAVE
          - ACPI_SHUTDOWN
          - ACPI_REBOOT
          type: string
        uuid:
          type: string
        vm_logical_timestamp:
          format: int64
          type: integer
    create.dto.acropolis.ReturnValueDTO_TaskIdDTO:
      type: object
      properties:
        task_uuid:
          type: string
