openapi: 3.0.0
info:
  version: v2.0
  title: Nutanix Prism API Reference
  description: "# Introduction\n\nThe Nutanix REST APIs allow you to create scripts that run system administration commands\
    \ against the Nutanix cluster. The API enables the use of HTTP requests to get information about the cluster as well as\
    \ make changes to the configuration. Output from the API calls are returned in JSON format.\n\nAll API users should have\
    \ valid Prism login credentials to send API calls to the Prism server. APIs on nutanix.dev portal are publicly available\
    \ to all valid users without special permissions for viewing purposes.\n\nThe v2 API is an update of the v1 API. Users\
    \ of the v1 API are encouraged to migrate to v2. \n\n[Nutanix API versions \u2013 What are they and what does each one\
    \ do?](https://www.nutanix.dev/api-versions/)"
  contact:
    name: Nutanix, Inc.
    url: http://www.nutanix.com
  license:
    name: EULA
    url: http://www.nutanix.com/eula
servers:
- url: https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0
security: []
paths:
  /hosts/unjoin_domain:
    post:
      tags:
      - /hosts
      operationId: post/hosts/unjoin_domain/unjoinNodeFromDomain
      requestBody:
        $ref: '#/components/requestBodies/create.dto.hyperv.ConfigureHypervNodeRequestDTO_HypervNodeDomainConfigurationDTO'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/create.dto.hyperv.MultiNodeConfigurationOperationResponseDTO'
      x-codeSamples:
      - lang: cURL
        source: "curl --request POST \\\n    --url https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/hosts/unjoin_domain\
          \ \\\n    --header 'Accept: application/json' \\\n    --header 'Content-Type: application/json' \\\n    --data '{\n\
          \    \"credential\": {\n        \"logon_name\": \"string\",\n        \"password\": \"string\"\n    },\n    \"domain_descriptor\"\
          : {\n        \"domain_name\": \"string\",\n        \"name_prefix\": \"string\",\n        \"name_server\": \"string\"\
          ,\n        \"ou_path\": \"string\"\n    },\n    \"force\": true,\n    \"node_descriptors\": [\n        {\n     \
          \       \"name\": \"string\",\n            \"node_id\": \"string\",\n            \"node_uuid\": \"string\"\n   \
          \     }\n    ],\n    \"node_name_prefix\": \"string\",\n    \"restart\": true\n}'"
      - lang: Wget
        source: "wget --quiet \\\n    --method POST \\\n    --header 'Accept: application/json' \\\n    --header 'Content-Type:\
          \ application/json' \\\n    --body-data '{\n    \"credential\": {\n        \"logon_name\": \"string\",\n       \
          \ \"password\": \"string\"\n    },\n    \"domain_descriptor\": {\n        \"domain_name\": \"string\",\n       \
          \ \"name_prefix\": \"string\",\n        \"name_server\": \"string\",\n        \"ou_path\": \"string\"\n    },\n\
          \    \"force\": true,\n    \"node_descriptors\": [\n        {\n            \"name\": \"string\",\n            \"\
          node_id\": \"string\",\n            \"node_uuid\": \"string\"\n        }\n    ],\n    \"node_name_prefix\": \"string\"\
          ,\n    \"restart\": true\n}' \\\n    --output-document \\\n    - https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/hosts/unjoin_domain"
      - lang: Python
        source: "import http.client\n\nconn = http.client.HTTPSConnection(\"any_cvm_ip:9440\")\n\nheaders = {\n    \"Accept\"\
          : \"application/json\",\n    \"Content-Type\": \"application/json\"\n}\n\npayload =  \"\"\"{\n    \"credential\"\
          : {\n        \"logon_name\": \"string\",\n        \"password\": \"string\"\n    },\n    \"domain_descriptor\": {\n\
          \        \"domain_name\": \"string\",\n        \"name_prefix\": \"string\",\n        \"name_server\": \"string\"\
          ,\n        \"ou_path\": \"string\"\n    },\n    \"force\": true,\n    \"node_descriptors\": [\n        {\n     \
          \       \"name\": \"string\",\n            \"node_id\": \"string\",\n            \"node_uuid\": \"string\"\n   \
          \     }\n    ],\n    \"node_name_prefix\": \"string\",\n    \"restart\": true\n}\"\"\"\n\nconn.request(\"POST\"\
          ,\"/PrismGateway/services/rest/v2.0/hosts/unjoin_domain\", payload, headers)\n\nres = conn.getresponse()\ndata =\
          \ res.read()\n\nprint(data.decode(\"utf-8\"))"
      - lang: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl\
          \ := \"https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/hosts/unjoin_domain\"\n\t\n\tpayload :=  strings.NewReader(`{\"\
          credential\": {\"logon_name\": \"string\", \"password\": \"string\"}, \"domain_descriptor\": {\"domain_name\": \"\
          string\", \"name_prefix\": \"string\", \"name_server\": \"string\", \"ou_path\": \"string\"}, \"force\": true, \"\
          node_descriptors\": [{\"name\": \"string\", \"node_id\": \"string\", \"node_uuid\": \"string\"}], \"node_name_prefix\"\
          : \"string\", \"restart\": true}`)\n\treq, err := http.NewRequest(\"POST\", url, payload)\n\tif err != nil {\n\t\
          \tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n        req.Header.Add(\"Accept\", \"application/json\"\
          )\n        req.Header.Add(\"Content-Type\", \"application/json\")\n    \n\tres, err := http.DefaultClient.Do(req)\n\
          \tif err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n\tdefer res.Body.Close()\n\
          \tbody, err := io.ReadAll(res.Body)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\t\
          return\n\t}\n\n\tfmt.Println(res)\n\tfmt.Println(string(body))\n\n}"
      - lang: Java
        source: "AsyncHttpClient client = new DefaultAsyncHttpClient();\nclient.prepare(\"POST\", \"https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/hosts/unjoin_domain\"\
          )\n  .setHeader(\"Accept\", \"application/json\")\n  .setHeader(\"Content-Type\", \"application/json\")\n  .setBody(\"\
          {\\\"credential\\\": {\\\"logon_name\\\": \\\"string\\\", \\\"password\\\": \\\"string\\\"}, \\\"domain_descriptor\\\
          \": {\\\"domain_name\\\": \\\"string\\\", \\\"name_prefix\\\": \\\"string\\\", \\\"name_server\\\": \\\"string\\\
          \", \\\"ou_path\\\": \\\"string\\\"}, \\\"force\\\": true, \\\"node_descriptors\\\": [{\\\"name\\\": \\\"string\\\
          \", \\\"node_id\\\": \\\"string\\\", \\\"node_uuid\\\": \\\"string\\\"}], \\\"node_name_prefix\\\": \\\"string\\\
          \", \\\"restart\\\": true}\")\n  .execute()\n  .toCompletableFuture()\n  .thenAccept(System.out::println)\n  .join();\n\
          \nclient.close();"
      - lang: JavaScript
        source: "const url = 'https://any_cvm_ip:9440/PrismGateway/services/rest/v2.0/hosts/unjoin_domain';\nconst options\
          \ = {\n  method: 'POST',\n  headers: {'Accept': 'application/json', 'Content-Type': 'application/json'},\n  body:\
          \  `{\"credential\": {\"logon_name\": \"string\", \"password\": \"string\"}, \"domain_descriptor\": {\"domain_name\"\
          : \"string\", \"name_prefix\": \"string\", \"name_server\": \"string\", \"ou_path\": \"string\"}, \"force\": true,\
          \ \"node_descriptors\": [{\"name\": \"string\", \"node_id\": \"string\", \"node_uuid\": \"string\"}], \"node_name_prefix\"\
          : \"string\", \"restart\": true}`\n};\n\ntry {\n  const response = await fetch(url, options);\n  const data = await\
          \ response.json();\n  console.log(data);\n} catch (error) {\n  console.error(error);\n}"
components:
  requestBodies:
    create.dto.hyperv.ConfigureHypervNodeRequestDTO_HypervNodeDomainConfigurationDTO:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/create.dto.hyperv.ConfigureHypervNodeRequestDTO_HypervNodeDomainConfigurationDTO'
  schemas:
    create.dto.hyperv.MultiNodeConfigurationOperationResponseDTO_NodeSpecificStatus:
      type: object
      properties:
        message:
          type: string
        node_id:
          type: string
        node_uuid:
          type: string
        reboot_initiated:
          type: boolean
        successful:
          type: boolean
    create.dto.hyperv.MultiNodeConfigurationOperationResponseDTO:
      type: object
      properties:
        node_specific_status:
          items:
            $ref: '#/components/schemas/create.dto.hyperv.MultiNodeConfigurationOperationResponseDTO_NodeSpecificStatus'
          type: array
    create.dto.hyperv.CredentialDTO:
      type: object
      properties:
        logon_name:
          type: string
        password:
          type: string
    create.dto.hyperv.DomainDescriptorDTO:
      type: object
      properties:
        domain_name:
          type: string
        name_prefix:
          type: string
        name_server:
          type: string
        ou_path:
          type: string
    create.dto.hyperv.HypervNodeDescriptorDTO:
      type: object
      properties:
        name:
          type: string
        node_id:
          type: string
        node_uuid:
          type: string
    create.dto.hyperv.ConfigureHypervNodeRequestDTO_HypervNodeDomainConfigurationDTO:
      type: object
      properties:
        credential:
          $ref: '#/components/schemas/create.dto.hyperv.CredentialDTO'
        domain_descriptor:
          $ref: '#/components/schemas/create.dto.hyperv.DomainDescriptorDTO'
        force:
          type: boolean
        node_descriptors:
          items:
            $ref: '#/components/schemas/create.dto.hyperv.HypervNodeDescriptorDTO'
          type: array
        node_name_prefix:
          type: string
        restart:
          type: boolean
