configuration: {name: nutanix-pc, namespace: nutanix-system, authSecret: {name: nutanix-pc-auth, namespace: nutanix-system}}
vm: {name: krateo-lk-vm, memorySizeBytes: 2147483648, numSockets: 1, numCoresPerSocket: 1, clusterExtId: ""}
child: {serialPortIndex: 1}
