# GENERATED 1:1 from selfservice-v1.yaml — resource 'Abort'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-abort
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-abort-oas/abort.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: Abort
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /apps/{uuid}/app_runlogs/{runlog_uuid}/abort
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
      - inPath: runlog_uuid
        inCustomResource: spec.runlog_uuid
