# GENERATED 1:1 from selfservice-v1.yaml — resource 'AppIcon'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-appicon
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-appicon-oas/appicon.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: AppIcon
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - uuid
    verbsDescription:
    - action: get
      method: GET
      path: /app_icons/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /app_icons/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
