# GENERATED 1:1 from selfservice-v1.yaml — resource 'ApplicationSecurityGroupsList'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-applicationsecuritygroupslist
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-applicationsecuritygroupslist-oas/applicationsecuritygroupslist.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: ApplicationSecurityGroupsList
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /azure_rm/v1/application_security_groups/list
