# GENERATED 1:1 from selfservice-v1.yaml — resource 'AppProfileList'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-appprofilelist
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-appprofilelist-oas/appprofilelist.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: AppProfileList
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /blueprints/{uuid}/app_profile/{app_profile_uuid}/config_spec/{config_uuid}/app_protection_policies/list
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
      - inPath: app_profile_uuid
        inCustomResource: spec.app_profile_uuid
      - inPath: config_uuid
        inCustomResource: spec.config_uuid
