# GENERATED 1:1 from selfservice-v1.yaml — resource 'ApprovalPolicy'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-approvalpolicy
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-approvalpolicy-oas/approvalpolicy.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: ApprovalPolicy
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /features/approval_policy
