# GENERATED 1:1 from selfservice-v1.yaml — resource 'ApprovalElement'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-approvalelement
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-approvalelement-oas/approvalelement.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: ApprovalElement
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - element_uuid
    verbsDescription:
    - action: update
      method: PUT
      path: /approvals/{uuid}/approval_sets/{set_uuid}/approval_elements/{element_uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
      - inPath: set_uuid
        inCustomResource: spec.set_uuid
      - inPath: element_uuid
        inCustomResource: status.extId
