# GENERATED 1:1 from selfservice-v1.yaml — resource 'AppRunlogsList'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-apprunlogslist
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-apprunlogslist-oas/apprunlogslist.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: AppRunlogsList
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /apps/{uuid}/app_runlogs/list
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
