# GENERATED 1:1 from selfservice-v1.yaml — resource 'AppRunlogsDownload'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-apprunlogsdownload
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-apprunlogsdownload-oas/apprunlogsdownload.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: AppRunlogsDownload
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /apps/{uuid}/app_runlogs/{runlog_uuid}/output/download
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
      - inPath: runlog_uuid
        inCustomResource: spec.runlog_uuid
