# GENERATED 1:1 from selfservice-v1.yaml — resource 'ApprovalRequest'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-approvalrequest
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-approvalrequest-oas/approvalrequest.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: ApprovalRequest
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - uuid
    verbsDescription:
    - action: get
      method: GET
      path: /approval_requests/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
