# GENERATED 1:1 from selfservice-v1.yaml — resource 'ArchivalPolicy'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-archivalpolicy
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-archivalpolicy-oas/archivalpolicy.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: ArchivalPolicy
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - uuid
    verbsDescription:
    - action: get
      method: GET
      path: /app_runlogs/archival_policy/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
