# GENERATED 1:1 from selfservice-v1.yaml — resource 'AvailabilityZonesList'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-availabilityzoneslist
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-availabilityzoneslist-oas/availabilityzoneslist.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: AvailabilityZonesList
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /aws/v1/availability_zones/list
