# GENERATED 1:1 from selfservice-v1.yaml — resource 'AvailabilitySetsList'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-availabilitysetslist
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-availabilitysetslist-oas/availabilitysetslist.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: AvailabilitySetsList
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /azure_rm/v1/availability_sets/list
