# GENERATED 1:1 from selfservice-v1.yaml — resource 'Blueprint'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-blueprint
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-blueprint-oas/blueprint.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: Blueprint
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - uuid
    verbsDescription:
    - action: create
      method: POST
      path: /blueprints
    - action: get
      method: GET
      path: /blueprints/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /blueprints/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /blueprints/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
