# GENERATED 1:1 from selfservice-v1.yaml — resource 'CalmMarketplaceItem'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-calmmarketplaceitem
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-calmmarketplaceitem-oas/calmmarketplaceitem.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: CalmMarketplaceItem
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - uuid
    verbsDescription:
    - action: create
      method: POST
      path: /calm_marketplace_items
    - action: get
      method: GET
      path: /calm_marketplace_items/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /calm_marketplace_items/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /calm_marketplace_items/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
