# GENERATED 1:1 from selfservice-v1.yaml — resource 'CalmOrchDr'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-calmorchdr
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-calmorchdr-oas/calmorchdr.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: CalmOrchDr
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /features/calm_orch_dr
