# GENERATED 1:1 from selfservice-v1.yaml — resource 'CalmDetectedDr'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-calmdetecteddr
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-calmdetecteddr-oas/calmdetecteddr.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: CalmDetectedDr
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /features/calm_detected_dr
