# GENERATED 1:1 from selfservice-v1.yaml — resource 'Cancel'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-cancel
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-cancel-oas/cancel.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: Cancel
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /app_showback/cancel
