# GENERATED 1:1 from selfservice-v1.yaml — resource 'ChildrenOutput'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-childrenoutput
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-childrenoutput-oas/childrenoutput.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: ChildrenOutput
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /runbooks/runlogs/{uuid}/children/{children_uuid}/output
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
      - inPath: children_uuid
        inCustomResource: spec.children_uuid
