# GENERATED 1:1 from selfservice-v1.yaml — resource 'ClustersList'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-clusterslist
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-clusterslist-oas/clusterslist.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: ClustersList
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /nutanix/v1/clusters/list
