# GENERATED 1:1 from selfservice-v1.yaml — resource 'ConfigFile'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-configfile
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-configfile-oas/configfile.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: ConfigFile
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /tunnels/{uuid}/config_file
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
