# GENERATED 1:1 from selfservice-v1.yaml — resource 'Consumption'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-consumption
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-consumption-oas/consumption.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: Consumption
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - limit
    - offset
    verbsDescription:
    - action: create
      method: POST
      path: /apps/{uuid}/consumption
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
