# GENERATED 1:1 from selfservice-v1.yaml — resource 'ConsumptionStat'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-consumptionstat
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-consumptionstat-oas/consumptionstat.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: ConsumptionStat
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /consumption_stats
