# GENERATED 1:1 from selfservice-v1.yaml — resource 'Consumption2'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-consumption2
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-consumption2-oas/consumption2.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: Consumption2
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - limit
    - offset
    verbsDescription:
    - action: create
      method: POST
      path: /license/consumption
