# GENERATED 1:1 from selfservice-v1.yaml — resource 'ConsumptionList'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-consumptionlist
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-consumptionlist-oas/consumptionlist.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: ConsumptionList
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - limit
    - offset
    verbsDescription:
    - action: create
      method: POST
      path: /apps/consumption_list
