# GENERATED 1:1 from selfservice-v1.yaml — resource 'CustomizationList'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-customizationlist
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-customizationlist-oas/customizationlist.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: CustomizationList
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /vmware/v6/customization/list
