# GENERATED 1:1 from selfservice-v1.yaml — resource 'Disable'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-disable
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-disable-oas/disable.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: Disable
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /app_showback/disable
