# GENERATED 1:1 from selfservice-v1.yaml — resource 'DiskTypesList'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-disktypeslist
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-disktypeslist-oas/disktypeslist.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: DiskTypesList
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /gcp/v1/disk_types/list
