# GENERATED 1:1 from selfservice-v1.yaml — resource 'EntityReference'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-entityreference
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-entityreference-oas/entityreference.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: EntityReference
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /tunnels/{uuid}/entity_references
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
