# GENERATED 1:1 from selfservice-v1.yaml — resource 'ExecutionsList'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-executionslist
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-executionslist-oas/executionslist.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: ExecutionsList
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /policies/{uuid}/executions/list
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
