# GENERATED 1:1 from selfservice-v1.yaml — resource 'ExportJson'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-exportjson
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-exportjson-oas/exportjson.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: ExportJson
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /blueprints/{uuid}/export_json
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
