# GENERATED 1:1 from selfservice-v1.yaml — resource 'ExportFile4'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-exportfile4
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-exportfile4-oas/exportfile4.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: ExportFile4
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /runbooks/{uuid}/export_file
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
    - action: create
      method: POST
      path: /runbooks/{uuid}/export_file
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
