# GENERATED 1:1 from selfservice-v1.yaml — resource 'ExportFile'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-exportfile
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-exportfile-oas/exportfile.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: ExportFile
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - project_reference
    verbsDescription:
    - action: findby
      method: GET
      path: /app_showback/export_file
