# GENERATED 1:1 from selfservice-v1.yaml — resource 'FilePathsList'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-filepathslist
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-filepathslist-oas/filepathslist.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: FilePathsList
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /vmware/v6/file_paths/list
