# GENERATED 1:1 from selfservice-v1.yaml — resource 'HostsList'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-hostslist
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-hostslist-oas/hostslist.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: HostsList
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /nutanix/v1/hosts/list
