# GENERATED 1:1 from selfservice-v1.yaml — resource 'ImagesList'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-imageslist
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-imageslist-oas/imageslist.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: ImagesList
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /aws/v1/images/list
