# GENERATED 1:1 from selfservice-v1.yaml — resource 'ImportJson3'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-importjson3
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-importjson3-oas/importjson3.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: ImportJson3
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /runbooks/import_json
