# GENERATED 1:1 from selfservice-v1.yaml — resource 'List18'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-list18
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-list18-oas/list18.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: List18
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /jobs/list
