# GENERATED 1:1 from selfservice-v1.yaml — resource 'List23'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-list23
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-list23-oas/list23.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: List23
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /network_groups/list
