# GENERATED 1:1 from selfservice-v1.yaml — resource 'List12'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-list12
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-list12-oas/list12.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: List12
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /blueprints/list
