# GENERATED 1:1 from selfservice-v1.yaml — resource 'List8'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-list8
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-list8-oas/list8.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: List8
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /app_variables/list
