# GENERATED 1:1 from selfservice-v1.yaml — resource 'NetworksList'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-networkslist
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-networkslist-oas/networkslist.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: NetworksList
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /gcp/v1/networks/list
