# GENERATED 1:1 from selfservice-v1.yaml — resource 'NetworkGroup'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-networkgroup
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-networkgroup-oas/networkgroup.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: NetworkGroup
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - uuid
    verbsDescription:
    - action: create
      method: POST
      path: /network_groups
    - action: get
      method: GET
      path: /network_groups/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /network_groups/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
