# GENERATED 1:1 from selfservice-v1.yaml — resource 'New'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-new
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-new-oas/new.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: New
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /apps/{uuid}/blueprints/new
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
