# GENERATED 1:1 from selfservice-v1.yaml — resource 'PatchRun'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-patchrun
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-patchrun-oas/patchrun.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: PatchRun
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /apps/{uuid}/patch/{patch_uuid}/run
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
      - inPath: patch_uuid
        inCustomResource: spec.patch_uuid
