# GENERATED 1:1 from selfservice-v1.yaml — resource 'PendingLaunch'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-pendinglaunch
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-pendinglaunch-oas/pendinglaunch.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: PendingLaunch
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - launched_uuid
    verbsDescription:
    - action: get
      method: GET
      path: /blueprints/{uuid}/pending_launches/{launched_uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
      - inPath: launched_uuid
        inCustomResource: status.extId
