# GENERATED 1:1 from selfservice-v1.yaml — resource 'PendingTask2'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-pendingtask2
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-pendingtask2-oas/pendingtask2.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: PendingTask2
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - task_uuid
    verbsDescription:
    - action: get
      method: GET
      path: /projects/{uuid}/pending_tasks/{task_uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
      - inPath: task_uuid
        inCustomResource: status.extId
