# GENERATED 1:1 from selfservice-v1.yaml — resource 'Play'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-play
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-play-oas/play.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: Play
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /runbooks/runlogs/{uuid}/play
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
