# GENERATED 1:1 from selfservice-v1.yaml — resource 'PostUpdate'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-postupdate
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-postupdate-oas/postupdate.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: PostUpdate
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /calm_projects/{uuid}/post_update
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
