# GENERATED 1:1 from selfservice-v1.yaml — resource 'Precheck'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-precheck
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-precheck-oas/precheck.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: Precheck
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /features/policy/prechecks
