# GENERATED 1:1 from selfservice-v1.yaml — resource 'Project'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-project
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-project-oas/project.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: Project
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - uuid
    verbsDescription:
    - action: create
      method: POST
      path: /projects
    - action: get
      method: GET
      path: /projects/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /projects/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /projects/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
