# GENERATED 1:1 from selfservice-v1.yaml — resource 'ProjectSaml'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-projectsaml
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-projectsaml-oas/projectsaml.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: ProjectSaml
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /features/project_saml
