# GENERATED 1:1 from selfservice-v1.yaml — resource 'PublishedService'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-publishedservice
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-publishedservice-oas/publishedservice.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: PublishedService
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - published_service_uuid
    verbsDescription:
    - action: get
      method: GET
      path: /apps/{uuid}/published_services/{published_service_uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
      - inPath: published_service_uuid
        inCustomResource: status.extId
