# GENERATED 1:1 from selfservice-v1.yaml — resource 'Quota'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-quota
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-quota-oas/quota.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: Quota
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - uuid
    verbsDescription:
    - action: create
      method: POST
      path: /quotas
    - action: update
      method: PUT
      path: /quotas/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /quotas/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
