# GENERATED 1:1 from selfservice-v1.yaml — resource 'RecoveryGroupsList'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-recoverygroupslist
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-recoverygroupslist-oas/recoverygroupslist.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: RecoveryGroupsList
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /apps/{uuid}/recovery_groups/list
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
