# GENERATED 1:1 from selfservice-v1.yaml — resource 'ReplicationConnection'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-replicationconnection
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-replicationconnection-oas/replicationconnection.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: ReplicationConnection
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - uuid
    verbsDescription:
    - action: create
      method: POST
      path: /replication_connections
    - action: get
      method: GET
      path: /replication_connections/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /replication_connections/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /replication_connections/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
