# GENERATED 1:1 from selfservice-v1.yaml — resource 'ResourceTypesList'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-resourcetypeslist
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-resourcetypeslist-oas/resourcetypeslist.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: ResourceTypesList
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /accounts/{uuid}/resource_types/list
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
