# GENERATED 1:1 from selfservice-v1.yaml — resource 'ResourceGroupsList'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-resourcegroupslist
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-resourcegroupslist-oas/resourcegroupslist.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: ResourceGroupsList
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /azure_rm/v1/resource_groups/list
