# GENERATED 1:1 from selfservice-v1.yaml — resource 'Resume'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-resume
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-resume-oas/resume.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: Resume
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /runbooks/runlogs/{uuid}/children/{children_uuid}/resume
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
      - inPath: children_uuid
        inCustomResource: spec.children_uuid
