# GENERATED 1:1 from selfservice-v1.yaml — resource 'RolesList'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-roleslist
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-roleslist-oas/roleslist.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: RolesList
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /aws/v1/roles/list
