# GENERATED 1:1 from selfservice-v1.yaml — resource 'Run'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-run
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-run-oas/run.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: Run
    identifiers:
    - name
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /apps/{uuid}/actions/run
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
