# GENERATED 1:1 from selfservice-v1.yaml — resource 'Run2'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-run2
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-run2-oas/run2.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: Run2
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /runbooks/{uuid}/run
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
