# GENERATED 1:1 from selfservice-v1.yaml — resource 'Runbook'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-runbook
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-runbook-oas/runbook.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: Runbook
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - uuid
    verbsDescription:
    - action: create
      method: POST
      path: /runbooks
    - action: get
      method: GET
      path: /runbooks/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /runbooks/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /runbooks/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
