# GENERATED 1:1 from selfservice-v1.yaml — resource 'Runlog'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-runlog
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-runlog-oas/runlog.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: Runlog
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - uuid
    verbsDescription:
    - action: get
      method: GET
      path: /runbooks/runlogs/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
