# GENERATED 1:1 from selfservice-v1.yaml — resource 'Statu'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-statu
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-statu-oas/statu.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: Statu
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /app_showback/status
