# GENERATED 1:1 from selfservice-v1.yaml — resource 'Statu3'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-statu3
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-statu3-oas/statu3.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: Statu3
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /features/{name}/status
      requestFieldMapping:
      - inPath: name
        inCustomResource: spec.name
