# GENERATED 1:1 from selfservice-v1.yaml — resource 'Stat2'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-stat2
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-stat2-oas/stat2.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: Stat2
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /calm_projects/{uuid}/stats
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
