# GENERATED 1:1 from selfservice-v1.yaml — resource 'SubnetsList3'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-subnetslist3
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-subnetslist3-oas/subnetslist3.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: SubnetsList3
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /nutanix/v1/subnets/list
