# GENERATED 1:1 from selfservice-v1.yaml — resource 'SubscriptionsList'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-subscriptionslist
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-subscriptionslist-oas/subscriptionslist.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: SubscriptionsList
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /azure_rm/v1/subscriptions/list
