# GENERATED 1:1 from selfservice-v1.yaml — resource 'Substrate'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-substrate
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-substrate-oas/substrate.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: Substrate
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - substrate_uuid
    verbsDescription:
    - action: get
      method: GET
      path: /apps/{uuid}/substrates/{substrate_uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
      - inPath: substrate_uuid
        inCustomResource: status.extId
