# GENERATED 1:1 from selfservice-v1.yaml — resource 'TagsList'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-tagslist
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-tagslist-oas/tagslist.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: TagsList
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /vmware/v6/tags/list
