# GENERATED 1:1 from selfservice-v1.yaml — resource 'TestRunbookRun'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-testrunbookrun
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-testrunbookrun-oas/testrunbookrun.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: TestRunbookRun
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /resource_types/{uuid}/test_runbook/{action_uuid}/run
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
      - inPath: action_uuid
        inCustomResource: spec.action_uuid
