# GENERATED 1:1 from selfservice-v1.yaml — resource 'Tunnel2'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-tunnel2
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-tunnel2-oas/tunnel2.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: Tunnel2
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - tunnel_uuid
    verbsDescription:
    - action: create
      method: POST
      path: /network_groups/{uuid}/tunnels
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
    - action: delete
      method: DELETE
      path: /network_groups/{uuid}/tunnels/{tunnel_uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
      - inPath: tunnel_uuid
        inCustomResource: status.extId
