# GENERATED 1:1 from selfservice-v1.yaml — resource 'UserPreference'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-userpreference
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-userpreference-oas/userpreference.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: UserPreference
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /user_preference
    - action: create
      method: POST
      path: /user_preference
