# GENERATED 1:1 from selfservice-v1.yaml — resource 'Validate5'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-validate5
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-validate5-oas/validate5.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: Validate5
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /tunnels/{uuid}/validate
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
