# GENERATED 1:1 from selfservice-v1.yaml — resource 'Variable'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-variable
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-variable-oas/variable.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: Variable
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /apps/{uuid}/actions/{action_name}/variables
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
      - inPath: action_name
        inCustomResource: spec.action_name
