# GENERATED 1:1 from selfservice-v1.yaml — resource 'VariablesValue2'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-variablesvalue2
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-variablesvalue2-oas/variablesvalue2.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: VariablesValue2
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - overridden_field
    - requestId
    - trlId
    verbsDescription:
    - action: findby
      method: GET
      path: /calm_marketplace_items/{uuid}/variables/{variable_uuid}/values
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
      - inPath: variable_uuid
        inCustomResource: spec.variable_uuid
    - action: create
      method: POST
      path: /calm_marketplace_items/{uuid}/variables/{variable_uuid}/values
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
      - inPath: variable_uuid
        inCustomResource: spec.variable_uuid
