# GENERATED 1:1 from selfservice-v1.yaml — resource 'Verify'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-verify
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-verify-oas/verify.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: Verify
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /accounts/{uuid}/verify
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
