# GENERATED 1:1 from selfservice-v1.yaml — resource 'VmSizesList'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-vmsizeslist
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-vmsizeslist-oas/vmsizeslist.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: VmSizesList
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /azure_rm/v1/vm_sizes/list
