# GENERATED 1:1 from selfservice-v1.yaml — resource 'VmsList'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-selfservice-vmslist
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-selfservice-vmslist-oas/vmslist.yaml
  resourceGroup: selfservice.nutanix.krateo.io
  resource:
    kind: VmsList
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /accounts/{uuid}/vms/list
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
