# GENERATED 1:1 from ndb-v0.9.yaml — resource 'Alert'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-alert
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-alert-oas/alert.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: Alert
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - alertId
    - client_tz
    - resolved
    - summary
    - timeInterval
    verbsDescription:
    - action: findby
      method: GET
      path: /alerts
    - action: get
      method: GET
      path: /alerts/{alertId}
      requestFieldMapping:
      - inPath: alertId
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /alerts/{alertId}
      requestFieldMapping:
      - inPath: alertId
        inCustomResource: status.extId
