# GENERATED 1:1 from ndb-v0.9.yaml — resource 'CandidateDbserver'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-candidatedbserver
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-candidatedbserver-oas/candidatedbserver.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: CandidateDbserver
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - usable
    verbsDescription:
    - action: findby
      method: GET
      path: /tms/{timemachine_id}/candidate-dbservers
      requestFieldMapping:
      - inPath: timemachine_id
        inCustomResource: spec.timemachine_id
