# GENERATED 1:1 from ndb-v0.9.yaml — resource 'Cert'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-cert
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-cert-oas/cert.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: Cert
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - id
    verbsDescription:
    - action: findby
      method: GET
      path: /resources/certs
    - action: create
      method: POST
      path: /resources/certs
    - action: delete
      method: DELETE
      path: /resources/certs/{id}
      requestFieldMapping:
      - inPath: id
        inCustomResource: status.extId
