# GENERATED 1:1 from ndb-v0.9.yaml — resource 'Cfg'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-cfg
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-cfg-oas/cfg.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: Cfg
    identifiers:
    - name
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - cfg-id
    - db-type
    - limit
    - load-details
    - name
    - offset
    verbsDescription:
    - action: findby
      method: GET
      path: /encryptions/tde/kms/{kms-id}/cfg
      requestFieldMapping:
      - inPath: kms-id
        inCustomResource: spec.kms-id
    - action: create
      method: POST
      path: /encryptions/tde/kms/{kms-id}/cfg
      requestFieldMapping:
      - inPath: kms-id
        inCustomResource: spec.kms-id
    - action: get
      method: GET
      path: /encryptions/tde/kms/{kms-id}/cfg/{cfg-id}
      requestFieldMapping:
      - inPath: kms-id
        inCustomResource: spec.kms-id
      - inPath: cfg-id
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /encryptions/tde/kms/{kms-id}/cfg/{cfg-id}
      requestFieldMapping:
      - inPath: kms-id
        inCustomResource: spec.kms-id
      - inPath: cfg-id
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /encryptions/tde/kms/{kms-id}/cfg/{cfg-id}
      requestFieldMapping:
      - inPath: kms-id
        inCustomResource: spec.kms-id
      - inPath: cfg-id
        inCustomResource: status.extId
