# GENERATED 1:1 from ndb-v0.9.yaml — resource 'ClonesInputFile'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-clonesinputfile
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-clonesinputfile-oas/clonesinputfile.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: ClonesInputFile
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - category
    verbsDescription:
    - action: findby
      method: GET
      path: /tms/name/{timemachine_name}/clones/input-file
      requestFieldMapping:
      - inPath: timemachine_name
        inCustomResource: spec.timemachine_name
