# GENERATED 1:1 from ndb-v0.9.yaml — resource 'ClonesInputFile2'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-clonesinputfile2
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-clonesinputfile2-oas/clonesinputfile2.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: ClonesInputFile2
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - category
    verbsDescription:
    - action: findby
      method: GET
      path: /tms/{timemachine_id}/clones/input-file
      requestFieldMapping:
      - inPath: timemachine_id
        inCustomResource: spec.timemachine_id
