# GENERATED 1:1 from ndb-v0.9.yaml — resource 'Clone'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-clone
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-clone-oas/clone.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: Clone
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - any-status
    - clone_id
    - detailed
    - load-dbserver-cluster
    - order-by-dbserver-cluster
    - order-by-dbserver-logical-cluster
    - time-zone
    - value
    - value-type
    verbsDescription:
    - action: findby
      method: GET
      path: /clones
    - action: get
      method: GET
      path: /clones/{clone_id}
      requestFieldMapping:
      - inPath: clone_id
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /clones/{clone_id}
      requestFieldMapping:
      - inPath: clone_id
        inCustomResource: status.extId
