# GENERATED 1:1 from ndb-v0.9.yaml — resource 'ClustersTrend'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-clusterstrend
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-clusterstrend-oas/clusterstrend.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: ClustersTrend
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - limit
    - tmEntity
    verbsDescription:
    - action: findby
      method: GET
      path: /storage/tms/{tmId}/clusters/{clusterId}/trend
      requestFieldMapping:
      - inPath: tmId
        inCustomResource: spec.tmId
      - inPath: clusterId
        inCustomResource: spec.clusterId
