# GENERATED 1:1 from ndb-v0.9.yaml — resource 'Consumption'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-consumption
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-consumption-oas/consumption.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: Consumption
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /storage/tms/{timeMachineId}/consumption
      requestFieldMapping:
      - inPath: timeMachineId
        inCustomResource: spec.timeMachineId
