# GENERATED 1:1 from ndb-v0.9.yaml — resource 'Cred'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-cred
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-cred-oas/cred.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: Cred
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /dbservers/{dbserver_id}/creds
      requestFieldMapping:
      - inPath: dbserver_id
        inCustomResource: spec.dbserver_id
