# GENERATED 1:1 from ndb-v0.9.yaml — resource 'Database2'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-database2
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-database2-oas/database2.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: Database2
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - database_id
    - detailed
    - load-dbserver-cluster
    - order-by-dbserver-cluster
    - order-by-dbserver-logical-cluster
    - time-zone
    - value
    - value-type
    verbsDescription:
    - action: findby
      method: GET
      path: /databases
    - action: get
      method: GET
      path: /databases/{database_id}
      requestFieldMapping:
      - inPath: database_id
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /databases/{database_id}
      requestFieldMapping:
      - inPath: database_id
        inCustomResource: status.extId
