# GENERATED 1:1 from ndb-v0.9.yaml — resource 'Database'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-database
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-database-oas/database.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: Database
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - any-status
    - database_id
    - detailed
    - load-dbserver-cluster
    - load-group-info
    - load-group-state-info
    - load-metrics
    - order-by-database-groups
    - order-by-dbserver-cluster
    - order-by-dbserver-logical-cluster
    - tag-name
    - tag-value
    - time-zone
    - value
    - value-type
    verbsDescription:
    - action: findby
      method: GET
      path: /database-groups/{database_group_id}/databases
      requestFieldMapping:
      - inPath: database_group_id
        inCustomResource: spec.database_group_id
    - action: get
      method: GET
      path: /database-groups/{database_group_id}/databases/{database_id}
      requestFieldMapping:
      - inPath: database_group_id
        inCustomResource: spec.database_group_id
      - inPath: database_id
        inCustomResource: status.extId
