# GENERATED 1:1 from ndb-v0.9.yaml — resource 'Dbserver'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-dbserver
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-dbserver-oas/dbserver.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: Dbserver
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - curator
    - dbserver_id
    - detailed
    - load-clones
    - load-databases
    - load-dbserver-cluster
    - load-metrics
    - set-lcm-config
    - time-zone
    - unset-lcm-config
    - value
    - value-type
    verbsDescription:
    - action: findby
      method: GET
      path: /dbservers
    - action: get
      method: GET
      path: /dbservers/{dbserver_id}
      requestFieldMapping:
      - inPath: dbserver_id
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /dbservers/{dbserver_id}
      requestFieldMapping:
      - inPath: dbserver_id
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /dbservers/{dbserver_id}
      requestFieldMapping:
      - inPath: dbserver_id
        inCustomResource: status.extId
