# GENERATED 1:1 from ndb-v0.9.yaml — resource 'Domain'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-domain
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-domain-oas/domain.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: Domain
    identifiers:
    - name
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - available-to-register
    - domain-id
    - limit
    - offset
    - skip-version-check
    - value
    - value-type
    verbsDescription:
    - action: findby
      method: GET
      path: /domains
    - action: create
      method: POST
      path: /domains
    - action: get
      method: GET
      path: /domains/{domain-id}
      requestFieldMapping:
      - inPath: domain-id
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /domains/{domain-id}
      requestFieldMapping:
      - inPath: domain-id
        inCustomResource: status.extId
