# GENERATED 1:1 from ndb-v0.9.yaml — resource 'Dpc'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-dpc
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-dpc-oas/dpc.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: Dpc
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - any-status
    - dbserver-cluster-id
    - detailed
    - load-clones
    - load-databases
    - load-metrics
    - time-zone
    - value
    - value-type
    verbsDescription:
    - action: findby
      method: GET
      path: /dpcs
    - action: get
      method: GET
      path: /dpcs/{dbserver-cluster-id}
      requestFieldMapping:
      - inPath: dbserver-cluster-id
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /dpcs/{dbserver-cluster-id}
      requestFieldMapping:
      - inPath: dbserver-cluster-id
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /dpcs/{dbserver-cluster-id}
      requestFieldMapping:
      - inPath: dbserver-cluster-id
        inCustomResource: status.extId
