# GENERATED 1:1 from ndb-v0.9.yaml — resource 'Drconfig'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-drconfig
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-drconfig-oas/drconfig.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: Drconfig
    identifiers:
    - name
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - drconfig-id
    verbsDescription:
    - action: create
      method: POST
      path: /dbservers/{dbserver_id}/drconfigs
      requestFieldMapping:
      - inPath: dbserver_id
        inCustomResource: spec.dbserver_id
    - action: get
      method: GET
      path: /dbservers/{dbserver_id}/drconfigs/{drconfig-id}
      requestFieldMapping:
      - inPath: dbserver_id
        inCustomResource: spec.dbserver_id
      - inPath: drconfig-id
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /dbservers/{dbserver_id}/drconfigs/{drconfig-id}
      requestFieldMapping:
      - inPath: dbserver_id
        inCustomResource: spec.dbserver_id
      - inPath: drconfig-id
        inCustomResource: status.extId
