# GENERATED 1:1 from ndb-v0.9.yaml — resource 'Drconfig2'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-drconfig2
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-drconfig2-oas/drconfig2.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: Drconfig2
    identifiers:
    - name
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - drconfig-id
    verbsDescription:
    - action: create
      method: POST
      path: /dpcs/{dbserver-cluster-id}/drconfigs
      requestFieldMapping:
      - inPath: dbserver-cluster-id
        inCustomResource: spec.dbserver-cluster-id
    - action: get
      method: GET
      path: /dpcs/{dbserver-cluster-id}/drconfigs/{drconfig-id}
      requestFieldMapping:
      - inPath: dbserver-cluster-id
        inCustomResource: spec.dbserver-cluster-id
      - inPath: drconfig-id
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /dpcs/{dbserver-cluster-id}/drconfigs/{drconfig-id}
      requestFieldMapping:
      - inPath: dbserver-cluster-id
        inCustomResource: spec.dbserver-cluster-id
      - inPath: drconfig-id
        inCustomResource: status.extId
