# GENERATED 1:1 from ndb-v0.9.yaml — resource 'InputFile2'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-inputfile2
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-inputfile2-oas/inputfile2.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: InputFile2
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /clones/refresh/{database_engine}/input-file
      requestFieldMapping:
      - inPath: database_engine
        inCustomResource: spec.database_engine
