# GENERATED 1:1 from ndb-v0.9.yaml — resource 'InputFile3'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-inputfile3
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-inputfile3-oas/inputfile3.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: InputFile3
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - db-version
    - engine
    - id
    - name
    - topology
    - type
    verbsDescription:
    - action: findby
      method: GET
      path: /profiles/input-file
