# GENERATED 1:1 from ndb-v0.9.yaml — resource 'KmsDatabase'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-kmsdatabase
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-kmsdatabase-oas/kmsdatabase.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: KmsDatabase
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /encryptions/tde/kms/{kms-id}/cfg/{cfg-id}/databases
      requestFieldMapping:
      - inPath: kms-id
        inCustomResource: spec.kms-id
      - inPath: cfg-id
        inCustomResource: spec.cfg-id
