# GENERATED 1:1 from ndb-v0.9.yaml — resource 'Latest'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-latest
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-latest-oas/latest.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: Latest
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - client_tz
    verbsDescription:
    - action: findby
      method: GET
      path: /profiles/{profile_id}/versions/latest
      requestFieldMapping:
      - inPath: profile_id
        inCustomResource: spec.profile_id
