# GENERATED 1:1 from ndb-v0.9.yaml — resource 'LogCatchup'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-logcatchup
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-logcatchup-oas/logcatchup.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: LogCatchup
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /tms/{timemachine_id}/log-catchups
      requestFieldMapping:
      - inPath: timemachine_id
        inCustomResource: spec.timemachine_id
