# GENERATED 1:1 from ndb-v0.9.yaml — resource 'Me'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-me
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-me-oas/me.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: Me
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /users/me
