# GENERATED 1:1 from ndb-v0.9.yaml — resource 'Mongo'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-mongo
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-mongo-oas/mongo.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: Mongo
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - mongos-id
    verbsDescription:
    - action: delete
      method: DELETE
      path: /dpcs/{dbserver-cluster-id}/mongos/{mongos-id}
      requestFieldMapping:
      - inPath: dbserver-cluster-id
        inCustomResource: spec.dbserver-cluster-id
      - inPath: mongos-id
        inCustomResource: status.extId
