# GENERATED 1:1 from ndb-v0.9.yaml — resource 'Name'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-name
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-name-oas/name.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: Name
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - alertPolicyName
    verbsDescription:
    - action: get
      method: GET
      path: /alerts/policy/name/{alertPolicyName}
      requestFieldMapping:
      - inPath: alertPolicyName
        inCustomResource: status.extId
