# GENERATED 1:1 from ndb-v0.9.yaml — resource 'Network'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-network
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-network-oas/network.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: Network
    identifiers:
    - name
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - detailed
    - id
    - name
    - vlan_id
    verbsDescription:
    - action: findby
      method: GET
      path: /resources/networks
    - action: create
      method: POST
      path: /resources/networks
    - action: update
      method: PUT
      path: /resources/networks/{vlan_id}
      requestFieldMapping:
      - inPath: vlan_id
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /resources/networks/{vlan_id}
      requestFieldMapping:
      - inPath: vlan_id
        inCustomResource: status.extId
