# GENERATED 1:1 from ndb-v0.9.yaml — resource 'Operation'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-operation
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-operation-oas/operation.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: Operation
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - client_tz
    - days
    - display
    - internalOps
    - operation_id
    - scheduledOps
    - sysOps
    - time-zone
    verbsDescription:
    - action: findby
      method: GET
      path: /operations
    - action: get
      method: GET
      path: /operations/{operation_id}
      requestFieldMapping:
      - inPath: operation_id
        inCustomResource: status.extId
