# GENERATED 1:1 from ndb-v0.9.yaml — resource 'OpsManagersMapping'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-opsmanagersmapping
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-opsmanagersmapping-oas/opsmanagersmapping.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: OpsManagersMapping
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - limit
    - offset
    verbsDescription:
    - action: findby
      method: GET
      path: /databases/ui/ops-managers-mapping
