# GENERATED 1:1 from ndb-v0.9.yaml — resource 'Overview2'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-overview2
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-overview2-oas/overview2.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: Overview2
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - limit
    - offset
    - viewType
    verbsDescription:
    - action: findby
      method: GET
      path: /storage/tms/overview
