# GENERATED 1:1 from ndb-v0.9.yaml — resource 'ProvisionShard'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-provisionshard
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-provisionshard-oas/provisionshard.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: ProvisionShard
    identifiers:
    - name
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /databases/{sharded_cluster_database_id}/provision-shard
      requestFieldMapping:
      - inPath: sharded_cluster_database_id
        inCustomResource: spec.sharded_cluster_database_id
