# GENERATED 1:1 from ndb-v0.9.yaml — resource 'Provision3'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-provision3
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-provision3-oas/provision3.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: Provision3
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /dbservers/provision
