# GENERATED 1:1 from ndb-v0.9.yaml — resource 'Provision2'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-provision2
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-provision2-oas/provision2.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: Provision2
    identifiers:
    - name
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /databases/provision
