# GENERATED 1:1 from ndb-v0.9.yaml — resource 'PurgeInterval'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-purgeinterval
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-purgeinterval-oas/purgeinterval.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: PurgeInterval
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /alerts/purgeInterval
