# GENERATED 1:1 from ndb-v0.9.yaml — resource 'Refresh'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-refresh
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-refresh-oas/refresh.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: Refresh
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /clones/{clone_id}/refresh
      requestFieldMapping:
      - inPath: clone_id
        inCustomResource: spec.clone_id
