# GENERATED 1:1 from ndb-v0.9.yaml — resource 'RegisterInputFile'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-registerinputfile
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-registerinputfile-oas/registerinputfile.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: RegisterInputFile
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - category
    - entity-type
    verbsDescription:
    - action: findby
      method: GET
      path: /app_types/{database_engine}/register/input-file
      requestFieldMapping:
      - inPath: database_engine
        inCustomResource: spec.database_engine
