# GENERATED 1:1 from ndb-v0.9.yaml — resource 'RemoveDbserver'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-removedbserver
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-removedbserver-oas/removedbserver.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: RemoveDbserver
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /dpcs/{dbserver-cluster-id}/remove-dbservers
      requestFieldMapping:
      - inPath: dbserver-cluster-id
        inCustomResource: spec.dbserver-cluster-id
