# GENERATED 1:1 from ndb-v0.9.yaml — resource 'Restore2'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-restore2
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-restore2-oas/restore2.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: Restore2
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /databases/{database_id}/restore
      requestFieldMapping:
      - inPath: database_id
        inCustomResource: spec.database_id
