# GENERATED 1:1 from ndb-v0.9.yaml — resource 'ScaleOut2'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-scaleout2
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-scaleout2-oas/scaleout2.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: ScaleOut2
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /dpcs/{dbserver-cluster-id}/scale-out
      requestFieldMapping:
      - inPath: dbserver-cluster-id
        inCustomResource: spec.dbserver-cluster-id
