# GENERATED 1:1 from ndb-v0.9.yaml — resource 'Shard'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-shard
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-shard-oas/shard.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: Shard
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - shard_id
    verbsDescription:
    - action: delete
      method: DELETE
      path: /databases/{sharded_cluster_database_id}/shards/{shard_id}
      requestFieldMapping:
      - inPath: sharded_cluster_database_id
        inCustomResource: spec.sharded_cluster_database_id
      - inPath: shard_id
        inCustomResource: status.extId
