# GENERATED 1:1 from ndb-v0.9.yaml — resource 'ShortInfo'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-shortinfo
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-shortinfo-oas/shortinfo.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: ShortInfo
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - client-id
    - cluster_id
    - count-summary
    - date-submitted
    - days
    - dbserver-id
    - deprecated
    - descending
    - entity-id
    - entity-name
    - entity-type
    - era-server
    - finished-after-time
    - from-time
    - hide-subops
    - ip
    - limit
    - operation-id
    - operations-count-only
    - orderby
    - owner_id
    - scheduled
    - search-text
    - skip
    - status
    - system-triggered
    - time-zone
    - timeout
    - timestamp
    - to-time
    - type
    - user-triggered
    verbsDescription:
    - action: findby
      method: GET
      path: /operations/short-info
