# GENERATED 1:1 from ndb-v0.9.yaml — resource 'Sla'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-sla
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-sla-oas/sla.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: Sla
    identifiers:
    - name
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - sla_id
    verbsDescription:
    - action: findby
      method: GET
      path: /slas
    - action: create
      method: POST
      path: /slas
    - action: get
      method: GET
      path: /slas/{sla_id}
      requestFieldMapping:
      - inPath: sla_id
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /slas/{sla_id}
      requestFieldMapping:
      - inPath: sla_id
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /slas/{sla_id}
      requestFieldMapping:
      - inPath: sla_id
        inCustomResource: status.extId
