# GENERATED 1:1 from ndb-v0.9.yaml — resource 'StorageResource'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-storageresource
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-storageresource-oas/storageresource.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: StorageResource
    identifiers:
    - name
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - force-delete
    - include-details
    - skip-credential-validation
    - skip-version-check
    - storage-resource-id
    verbsDescription:
    - action: findby
      method: GET
      path: /storage-resources
    - action: create
      method: POST
      path: /storage-resources
    - action: get
      method: GET
      path: /storage-resources/{storage-resource-id}
      requestFieldMapping:
      - inPath: storage-resource-id
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /storage-resources/{storage-resource-id}
      requestFieldMapping:
      - inPath: storage-resource-id
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /storage-resources/{storage-resource-id}
      requestFieldMapping:
      - inPath: storage-resource-id
        inCustomResource: status.extId
