# GENERATED 1:1 from ndb-v0.9.yaml — resource 'SystemDisabledFeat'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-systemdisabledfeat
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-systemdisabledfeat-oas/systemdisabledfeat.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: SystemDisabledFeat
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /config/system-disabled-feats
