# GENERATED 1:1 from ndb-v0.9.yaml — resource 'TimelineSummary'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-timelinesummary
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-timelinesummary-oas/timelinesummary.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: TimelineSummary
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - end_date
    - start_date
    - timezone
    verbsDescription:
    - action: findby
      method: GET
      path: /tms/{timemachine_id}/timeline-summary
      requestFieldMapping:
      - inPath: timemachine_id
        inCustomResource: spec.timemachine_id
