# GENERATED 1:1 from ndb-v0.9.yaml — resource 'Timeline'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-timeline
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-timeline-oas/timeline.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: Timeline
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - end_time
    - start_time
    - timezone
    verbsDescription:
    - action: findby
      method: GET
      path: /tms/{timemachine_id}/timeline
      requestFieldMapping:
      - inPath: timemachine_id
        inCustomResource: spec.timemachine_id
