# GENERATED 1:1 from ndb-v0.9.yaml — resource 'Tm'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-tm
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-tm-oas/tm.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: Tm
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - child-tms
    - clone-tms
    - database-tms
    - detailed
    - load-clones
    - load-database
    - time-zone
    - timemachine_id
    - value
    - value-type
    verbsDescription:
    - action: findby
      method: GET
      path: /tms
    - action: get
      method: GET
      path: /tms/{timemachine_id}
      requestFieldMapping:
      - inPath: timemachine_id
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /tms/{timemachine_id}
      requestFieldMapping:
      - inPath: timemachine_id
        inCustomResource: status.extId
