# GENERATED 1:1 from ndb-v0.9.yaml — resource 'Topology'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-topology
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-topology-oas/topology.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: Topology
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - time-zone
    - value-type
    verbsDescription:
    - action: findby
      method: GET
      path: /dpcs/{dbserver-cluster-id}/topology
      requestFieldMapping:
      - inPath: dbserver-cluster-id
        inCustomResource: spec.dbserver-cluster-id
