# GENERATED 1:1 from ndb-v0.9.yaml — resource 'Trend'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-trend
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-trend-oas/trend.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: Trend
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - limit
    verbsDescription:
    - action: findby
      method: GET
      path: /storage/clones/{cloneId}/trend
      requestFieldMapping:
      - inPath: cloneId
        inCustomResource: spec.cloneId
