# GENERATED 1:1 from ndb-v0.9.yaml — resource 'Trend2'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-trend2
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-trend2-oas/trend2.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: Trend2
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - limit
    verbsDescription:
    - action: findby
      method: GET
      path: /storage/clusters/{clusterId}/trend
      requestFieldMapping:
      - inPath: clusterId
        inCustomResource: spec.clusterId
