# GENERATED 1:1 from ndb-v0.9.yaml — resource 'User'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-user
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-user-oas/user.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: User
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - transferToUser
    - user_id
    verbsDescription:
    - action: findby
      method: GET
      path: /users
    - action: create
      method: POST
      path: /users
    - action: get
      method: GET
      path: /users/{user_id}
      requestFieldMapping:
      - inPath: user_id
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /users/{user_id}
      requestFieldMapping:
      - inPath: user_id
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /users/{user_id}
      requestFieldMapping:
      - inPath: user_id
        inCustomResource: status.extId
