# GENERATED 1:1 from ndb-v0.9.yaml — resource 'Verify'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-verify
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-verify-oas/verify.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: Verify
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /users/external/verify
