# GENERATED 1:1 from ndb-v0.9.yaml — resource 'Version'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-ndb-version
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-ndb-version-oas/version.yaml
  resourceGroup: ndb.nutanix.krateo.io
  resource:
    kind: Version
    identifiers:
    - name
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - client_tz
    - version-id
    verbsDescription:
    - action: create
      method: POST
      path: /profiles/{profile_id}/versions
      requestFieldMapping:
      - inPath: profile_id
        inCustomResource: spec.profile_id
    - action: get
      method: GET
      path: /profiles/{profile_id}/versions/{version-id}
      requestFieldMapping:
      - inPath: profile_id
        inCustomResource: spec.profile_id
      - inPath: version-id
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /profiles/{profile_id}/versions/{version-id}
      requestFieldMapping:
      - inPath: profile_id
        inCustomResource: spec.profile_id
      - inPath: version-id
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /profiles/{profile_id}/versions/{version-id}
      requestFieldMapping:
      - inPath: profile_id
        inCustomResource: spec.profile_id
      - inPath: version-id
        inCustomResource: status.extId
