# GENERATED 1:1 from prismv3-v1.yaml — resource 'Abort'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv3-abort
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv3-abort-oas/abort.yaml
  resourceGroup: prismv3.nutanix.krateo.io
  resource:
    kind: Abort
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /tasks/{uuid}/abort
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
