# GENERATED 1:1 from prismv3-v1.yaml — resource 'Batch'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv3-batch
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv3-batch-oas/batch.yaml
  resourceGroup: prismv3.nutanix.krateo.io
  resource:
    kind: Batch
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /batch
