# GENERATED 1:1 from prismv3-v1.yaml — resource 'Category'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv3-category
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv3-category-oas/category.yaml
  resourceGroup: prismv3.nutanix.krateo.io
  resource:
    kind: Category
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - name
    verbsDescription:
    - action: get
      method: GET
      path: /categories/{name}
      requestFieldMapping:
      - inPath: name
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /categories/{name}
      requestFieldMapping:
      - inPath: name
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /categories/{name}
      requestFieldMapping:
      - inPath: name
        inCustomResource: status.extId
