# GENERATED 1:1 from prismv3-v1.yaml — resource 'Disk'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv3-disk
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv3-disk-oas/disk.yaml
  resourceGroup: prismv3.nutanix.krateo.io
  resource:
    kind: Disk
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - disk_id
    verbsDescription:
    - action: findby
      method: GET
      path: /ovas/{uuid}/disks
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
    - action: get
      method: GET
      path: /ovas/{uuid}/disks/{disk_id}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
      - inPath: disk_id
        inCustomResource: status.extId
