# GENERATED 1:1 from prismv3-v1.yaml — resource 'DryRun'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv3-dryrun
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv3-dryrun-oas/dryrun.yaml
  resourceGroup: prismv3.nutanix.krateo.io
  resource:
    kind: DryRun
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /network_security_rules/import/dry_run
