# GENERATED 1:1 from prismv3-v1.yaml — resource 'Entity'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv3-entity
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv3-entity-oas/entity.yaml
  resourceGroup: prismv3.nutanix.krateo.io
  resource:
    kind: Entity
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - action_type
    - failed_availability_zone_info_list
    - recovery_availability_zone_info_list
    - recovery_reference_time
    verbsDescription:
    - action: findby
      method: GET
      path: /recovery_plans/{uuid}/entities
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
