# GENERATED 1:1 from prismv3-v1.yaml — resource 'File2'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv3-file2
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv3-file2-oas/file2.yaml
  resourceGroup: prismv3.nutanix.krateo.io
  resource:
    kind: File2
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /ovas/{uuid}/file
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
