# GENERATED 1:1 from prismv3-v1.yaml — resource 'IdempotenceIdentifier'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv3-idempotenceidentifier
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv3-idempotenceidentifier-oas/idempotenceidentifier.yaml
  resourceGroup: prismv3.nutanix.krateo.io
  resource:
    kind: IdempotenceIdentifier
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - client_identifier
    verbsDescription:
    - action: create
      method: POST
      path: /idempotence_identifiers
    - action: get
      method: GET
      path: /idempotence_identifiers/{client_identifier}
      requestFieldMapping:
      - inPath: client_identifier
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /idempotence_identifiers/{client_identifier}
      requestFieldMapping:
      - inPath: client_identifier
        inCustomResource: status.extId
