# GENERATED 1:1 from prismv3-v1.yaml — resource 'IdentityProvider'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv3-identityprovider
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv3-identityprovider-oas/identityprovider.yaml
  resourceGroup: prismv3.nutanix.krateo.io
  resource:
    kind: IdentityProvider
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - uuid
    verbsDescription:
    - action: create
      method: POST
      path: /identity_providers
    - action: get
      method: GET
      path: /identity_providers/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /identity_providers/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /identity_providers/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
