# GENERATED 1:1 from prismv3-v1.yaml — resource 'Permission'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv3-permission
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv3-permission-oas/permission.yaml
  resourceGroup: prismv3.nutanix.krateo.io
  resource:
    kind: Permission
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - uuid
    verbsDescription:
    - action: get
      method: GET
      path: /permissions/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
