# GENERATED 1:1 from prismv3-v1.yaml — resource 'RemoteSyslogServer'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv3-remotesyslogserver
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv3-remotesyslogserver-oas/remotesyslogserver.yaml
  resourceGroup: prismv3.nutanix.krateo.io
  resource:
    kind: RemoteSyslogServer
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - uuid
    verbsDescription:
    - action: create
      method: POST
      path: /remote_syslog_servers
    - action: get
      method: GET
      path: /remote_syslog_servers/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /remote_syslog_servers/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /remote_syslog_servers/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
