# GENERATED 1:1 from prismv3-v1.yaml — resource 'ReportInstance'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv3-reportinstance
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv3-reportinstance-oas/reportinstance.yaml
  resourceGroup: prismv3.nutanix.krateo.io
  resource:
    kind: ReportInstance
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - uuid
    verbsDescription:
    - action: create
      method: POST
      path: /report_instances
    - action: get
      method: GET
      path: /report_instances/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /report_instances/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
