# GENERATED 1:1 from prismv3-v1.yaml — resource 'RoutingPoliciesResetCounter'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv3-routingpoliciesresetcounter
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv3-routingpoliciesresetcounter-oas/routingpoliciesresetcounter.yaml
  resourceGroup: prismv3.nutanix.krateo.io
  resource:
    kind: RoutingPoliciesResetCounter
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /vpcs/{uuid}/routing_policies/reset_counters
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
