# GENERATED 1:1 from prismv3-v1.yaml — resource 'SpMetadata'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv3-spmetadata
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv3-spmetadata-oas/spmetadata.yaml
  resourceGroup: prismv3.nutanix.krateo.io
  resource:
    kind: SpMetadata
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /identity_providers/sp_metadata
