# GENERATED 1:1 from prismv3-v1.yaml — resource 'UserGroup'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv3-usergroup
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv3-usergroup-oas/usergroup.yaml
  resourceGroup: prismv3.nutanix.krateo.io
  resource:
    kind: UserGroup
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - uuid
    verbsDescription:
    - action: create
      method: POST
      path: /user_groups
    - action: get
      method: GET
      path: /user_groups/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /user_groups/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
