# GENERATED 1:1 from prismv3-v1.yaml — resource 'VmHostAffinityLegacyPolicy'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv3-vmhostaffinitylegacypolicy
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv3-vmhostaffinitylegacypolicy-oas/vmhostaffinitylegacypolicy.yaml
  resourceGroup: prismv3.nutanix.krateo.io
  resource:
    kind: VmHostAffinityLegacyPolicy
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - uuid
    verbsDescription:
    - action: delete
      method: DELETE
      path: /vm_host_affinity_legacy_policies/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
