# GENERATED 1:1 from prismv3-v1.yaml — resource 'VmHostAffinityPolicy'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv3-vmhostaffinitypolicy
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv3-vmhostaffinitypolicy-oas/vmhostaffinitypolicy.yaml
  resourceGroup: prismv3.nutanix.krateo.io
  resource:
    kind: VmHostAffinityPolicy
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - include_vms_hosts_count
    - uuid
    verbsDescription:
    - action: create
      method: POST
      path: /vm_host_affinity_policies
    - action: get
      method: GET
      path: /vm_host_affinity_policies/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /vm_host_affinity_policies/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /vm_host_affinity_policies/{uuid}
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: status.extId
