# GENERATED 1:1 from prismv3-v1.yaml — resource 'VmsList'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv3-vmslist
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv3-vmslist-oas/vmslist.yaml
  resourceGroup: prismv3.nutanix.krateo.io
  resource:
    kind: VmsList
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - status
    verbsDescription:
    - action: create
      method: POST
      path: /vm_host_affinity_policies/{uuid}/vms_list
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
