# GENERATED 1:1 from prismv3-v1.yaml — resource 'VmSpec'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-prismv3-vmspec
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-prismv3-vmspec-oas/vmspec.yaml
  resourceGroup: prismv3.nutanix.krateo.io
  resource:
    kind: VmSpec
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - ignore_unknown_fields
    verbsDescription:
    - action: findby
      method: GET
      path: /ovas/{uuid}/vm_spec
      requestFieldMapping:
      - inPath: uuid
        inCustomResource: spec.uuid
