# GENERATED 1:1 from foundationcentral-v1.yaml — resource 'ApiKey'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-foundationcentral-apikey
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-foundationcentral-apikey-oas/apikey.yaml
  resourceGroup: foundationcentral.nutanix.krateo.io
  resource:
    kind: ApiKey
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - key_uuid
    verbsDescription:
    - action: create
      method: POST
      path: /api_keys
    - action: get
      method: GET
      path: /api_keys/{key_uuid}
      requestFieldMapping:
      - inPath: key_uuid
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /api_keys/{key_uuid}
      requestFieldMapping:
      - inPath: key_uuid
        inCustomResource: status.extId
