# GENERATED 1:1 from foundationcentral-v1.yaml — resource 'Cluster'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-foundationcentral-cluster
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-foundationcentral-cluster-oas/cluster.yaml
  resourceGroup: foundationcentral.nutanix.krateo.io
  resource:
    kind: Cluster
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - cluster_uuid
    verbsDescription:
    - action: get
      method: GET
      path: /pc/clusters/{cluster_uuid}
      requestFieldMapping:
      - inPath: cluster_uuid
        inCustomResource: status.extId
