# GENERATED 1:1 from foundationcentral-v1.yaml — resource 'Detail'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-foundationcentral-detail
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-foundationcentral-detail-oas/detail.yaml
  resourceGroup: foundationcentral.nutanix.krateo.io
  resource:
    kind: Detail
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /details
