# GENERATED 1:1 from foundationcentral-v1.yaml — resource 'HardwareManager'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-foundationcentral-hardwaremanager
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-foundationcentral-hardwaremanager-oas/hardwaremanager.yaml
  resourceGroup: foundationcentral.nutanix.krateo.io
  resource:
    kind: HardwareManager
    identifiers:
    - name
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - hardware_manager_uuid
    verbsDescription:
    - action: create
      method: POST
      path: /hardware_managers
    - action: get
      method: GET
      path: /hardware_managers/{hardware_manager_uuid}
      requestFieldMapping:
      - inPath: hardware_manager_uuid
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /hardware_managers/{hardware_manager_uuid}
      requestFieldMapping:
      - inPath: hardware_manager_uuid
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /hardware_managers/{hardware_manager_uuid}
      requestFieldMapping:
      - inPath: hardware_manager_uuid
        inCustomResource: status.extId
