# GENERATED 1:1 from foundationcentral-v1.yaml — resource 'ImagedCluster'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-foundationcentral-imagedcluster
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-foundationcentral-imagedcluster-oas/imagedcluster.yaml
  resourceGroup: foundationcentral.nutanix.krateo.io
  resource:
    kind: ImagedCluster
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - imaged_cluster_uuid
    verbsDescription:
    - action: create
      method: POST
      path: /imaged_clusters
    - action: get
      method: GET
      path: /imaged_clusters/{imaged_cluster_uuid}
      requestFieldMapping:
      - inPath: imaged_cluster_uuid
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /imaged_clusters/{imaged_cluster_uuid}
      requestFieldMapping:
      - inPath: imaged_cluster_uuid
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /imaged_clusters/{imaged_cluster_uuid}
      requestFieldMapping:
      - inPath: imaged_cluster_uuid
        inCustomResource: status.extId
