# GENERATED 1:1 from foundationcentral-v1.yaml — resource 'NodesList'
# synchronous
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-foundationcentral-nodeslist
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-foundationcentral-nodeslist-oas/nodeslist.yaml
  resourceGroup: foundationcentral.nutanix.krateo.io
  resource:
    kind: NodesList
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: create
      method: POST
      path: /hardware_managers/{hardware_manager_uuid}/nodes/list
      requestFieldMapping:
      - inPath: hardware_manager_uuid
        inCustomResource: spec.hardware_manager_uuid
