# GENERATED 1:1 from volumes-v4.0.yaml — resource 'CategoryAssociation'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-volumes-categoryassociation
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-volumes-categoryassociation-oas/categoryassociation.yaml
  resourceGroup: volumes.nutanix.krateo.io
  resource:
    kind: CategoryAssociation
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $limit
    - $page
    verbsDescription:
    - action: findby
      method: GET
      path: /volumes/v4.0/config/volume-groups/{volumeGroupExtId}/category-associations
      requestFieldMapping:
      - inPath: volumeGroupExtId
        inCustomResource: spec.volumeGroupExtId
