# GENERATED 1:1 from volumes-v4.0.yaml — resource 'Disk'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-volumes-disk
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-volumes-disk-oas/disk.yaml
  resourceGroup: volumes.nutanix.krateo.io
  resource:
    kind: Disk
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $limit
    - $orderby
    - $page
    - $select
    verbsDescription:
    - action: findby
      method: GET
      path: /volumes/v4.0/config/volume-groups/{volumeGroupExtId}/disks
      requestFieldMapping:
      - inPath: volumeGroupExtId
        inCustomResource: spec.volumeGroupExtId
    - action: create
      method: POST
      path: /volumes/v4.0/config/volume-groups/{volumeGroupExtId}/disks
      requestFieldMapping:
      - inPath: volumeGroupExtId
        inCustomResource: spec.volumeGroupExtId
    - action: get
      method: GET
      path: /volumes/v4.0/config/volume-groups/{volumeGroupExtId}/disks/{extId}
      requestFieldMapping:
      - inPath: volumeGroupExtId
        inCustomResource: spec.volumeGroupExtId
      - inPath: extId
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /volumes/v4.0/config/volume-groups/{volumeGroupExtId}/disks/{extId}
      requestFieldMapping:
      - inPath: volumeGroupExtId
        inCustomResource: spec.volumeGroupExtId
      - inPath: extId
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /volumes/v4.0/config/volume-groups/{volumeGroupExtId}/disks/{extId}
      requestFieldMapping:
      - inPath: volumeGroupExtId
        inCustomResource: spec.volumeGroupExtId
      - inPath: extId
        inCustomResource: status.extId
