# GENERATED 1:1 from volumes-v4.0.yaml — resource 'ExternalIscsiAttachment'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-volumes-externaliscsiattachment
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-volumes-externaliscsiattachment-oas/externaliscsiattachment.yaml
  resourceGroup: volumes.nutanix.krateo.io
  resource:
    kind: ExternalIscsiAttachment
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $expand
    - $filter
    - $limit
    - $orderby
    - $page
    - $select
    verbsDescription:
    - action: findby
      method: GET
      path: /volumes/v4.0/config/volume-groups/{volumeGroupExtId}/external-iscsi-attachments
      requestFieldMapping:
      - inPath: volumeGroupExtId
        inCustomResource: spec.volumeGroupExtId
