# GENERATED 1:1 from volumes-v4.0.yaml — resource 'IscsiClient'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-volumes-iscsiclient
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-volumes-iscsiclient-oas/iscsiclient.yaml
  resourceGroup: volumes.nutanix.krateo.io
  resource:
    kind: IscsiClient
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $expand
    - $filter
    - $limit
    - $orderby
    - $page
    - $select
    verbsDescription:
    - action: findby
      method: GET
      path: /volumes/v4.0/config/iscsi-clients
    - action: get
      method: GET
      path: /volumes/v4.0/config/iscsi-clients/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /volumes/v4.0/config/iscsi-clients/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
