# GENERATED 1:1 from volumes-v4.0.yaml — resource 'Metadata'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-volumes-metadata
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-volumes-metadata-oas/metadata.yaml
  resourceGroup: volumes.nutanix.krateo.io
  resource:
    kind: Metadata
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /volumes/v4.0/config/volume-groups/{volumeGroupExtId}/metadata
      requestFieldMapping:
      - inPath: volumeGroupExtId
        inCustomResource: spec.volumeGroupExtId
