# GENERATED 1:1 from datapolicies-v4.0.yaml — resource 'ProtectionPolicy'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-datapolicies-protectionpolicy
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-datapolicies-protectionpolicy-oas/protectionpolicy.yaml
  resourceGroup: datapolicies.nutanix.krateo.io
  resource:
    kind: ProtectionPolicy
    identifiers:
    - name
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $limit
    - $orderby
    - $page
    - $select
    verbsDescription:
    - action: findby
      method: GET
      path: /datapolicies/v4.0/config/protection-policies
    - action: create
      method: POST
      path: /datapolicies/v4.0/config/protection-policies
    - action: get
      method: GET
      path: /datapolicies/v4.0/config/protection-policies/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /datapolicies/v4.0/config/protection-policies/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /datapolicies/v4.0/config/protection-policies/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
