# GENERATED 1:1 from multidomain-v4.2.yaml — resource 'ExternalRepository'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-multidomain-externalrepository
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-multidomain-externalrepository-oas/externalrepository.yaml
  resourceGroup: multidomain.nutanix.krateo.io
  resource:
    kind: ExternalRepository
    identifiers:
    - name
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $filter
    - $limit
    - $orderby
    - $page
    - $select
    verbsDescription:
    - action: findby
      method: GET
      path: /multidomain/v4.2/config/external-repositories
    - action: create
      method: POST
      path: /multidomain/v4.2/config/external-repositories
    - action: get
      method: GET
      path: /multidomain/v4.2/config/external-repositories/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /multidomain/v4.2/config/external-repositories/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /multidomain/v4.2/config/external-repositories/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
