openapi: 3.0.0
info:
  title: Foundation Central Service
  description: '# Introduction


    **Foundation Central** creates clusters from factory-imaged nodes and reimages existing nodes that are already registered
    with Foundation Central, remotely from Prism Central. This provides benefits such as creating clusters on remote sites
    (for example, ROBO), without arranging for a deployment personnel visit.


    **[Contact Us by Email](mailto:foundation@nutanix.com)**


    **License: Copyright Nutanix Inc. All rights reserved**

    '
  contact:
    name: Foundation Central Developers
    email: foundation@nutanix.com
  license:
    name: Copyright Nutanix Inc. All rights reserved
  version: '1.0'
servers:
- url: /api/fc/v1
security:
- BasicAuth: []
- CookieAuth: []
paths:
  /api_keys:
    post:
      description: Creates a new API key, which will be used by remote nodes to authenticate to Foundation Central.
      tags:
      - api_keys
      summary: Create an API key
      operationId: PostApiKeys
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/api_keys_input'
        required: true
      responses:
        '200':
          description: New API key created.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/api_key_details'
      x-codeSamples:
      - lang: cURL
        source: "curl --request POST \\\n    --url https://www.nutanix.dev/api/fc/v1/api_keys \\\n    --header 'Authorization:\
          \ Basic <basic_auth_token>' \\\n    --data '{\n    \"alias\": \"string\"\n}'"
      - lang: Wget
        source: "wget --quiet \\\n    --method POST \\\n    --header 'Authorization: Basic <basic_auth_token>' \\\n    --body-data\
          \ '{\n    \"alias\": \"string\"\n}' \\\n    --output-document \\\n    - https://www.nutanix.dev/api/fc/v1/api_keys"
      - lang: Python
        source: "import http.client\n\nconn = http.client.HTTPSConnection(\"www.nutanix.dev\")\n\nheaders = {\n    \"Authorization\"\
          : \"Basic <basic_auth_token>\"\n}\n\npayload =  \"\"\"{\n    \"alias\": \"string\"\n}\"\"\"\n\nconn.request(\"POST\"\
          ,\"/api/fc/v1/api_keys\", payload, headers)\n\nres = conn.getresponse()\ndata = res.read()\n\nprint(data.decode(\"\
          utf-8\"))"
      - lang: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl\
          \ := \"https://www.nutanix.dev/api/fc/v1/api_keys\"\n\t\n\tpayload :=  strings.NewReader(`{\"alias\": \"string\"\
          }`)\n\treq, err := http.NewRequest(\"POST\", url, payload)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating\
          \ request:\", err)\n\t\treturn\n\t}\n\n        req.Header.Add(\"Authorization\", \"Basic <basic_auth_token>\")\n\
          \    \n\tres, err := http.DefaultClient.Do(req)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating request:\"\
          , err)\n\t\treturn\n\t}\n\n\tdefer res.Body.Close()\n\tbody, err := io.ReadAll(res.Body)\n\tif err != nil {\n\t\t\
          fmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n\tfmt.Println(res)\n\tfmt.Println(string(body))\n\
          \n}"
      - lang: Java
        source: "AsyncHttpClient client = new DefaultAsyncHttpClient();\nclient.prepare(\"POST\", \"https://www.nutanix.dev/api/fc/v1/api_keys\"\
          )\n  .setHeader(\"Authorization\", \"Basic <basic_auth_token>\")\n  .setBody(\"{\\\"alias\\\": \\\"string\\\"}\"\
          )\n  .execute()\n  .toCompletableFuture()\n  .thenAccept(System.out::println)\n  .join();\n\nclient.close();"
      - lang: JavaScript
        source: "const url = 'https://www.nutanix.dev/api/fc/v1/api_keys';\nconst options = {\n  method: 'POST',\n  headers:\
          \ {'Authorization': 'Basic <basic_auth_token>'},\n  body:  `{\"alias\": \"string\"}`\n};\n\ntry {\n  const response\
          \ = await fetch(url, options);\n  const data = await response.json();\n  console.log(data);\n} catch (error) {\n\
          \  console.error(error);\n}"
  /api_keys/{key_uuid}:
    get:
      description: Get an API key based on its UUID.
      tags:
      - api_keys
      summary: Get an API key
      operationId: GetApiKey
      parameters:
      - description: UUID of the API key that must be fetched.
        name: key_uuid
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Details of the API key.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/api_key_details'
      x-codeSamples:
      - lang: cURL
        source: "curl --request GET \\\n    --url https://www.nutanix.dev/api/fc/v1/api_keys/{key_uuid} \\\n    --header 'Authorization:\
          \ Basic <basic_auth_token>' \\\n     "
      - lang: Wget
        source: "wget --quiet \\\n    --method GET \\\n    --header 'Authorization: Basic <basic_auth_token>' \\\n      \\\
          \n    --output-document \\\n    - https://www.nutanix.dev/api/fc/v1/api_keys/{key_uuid}"
      - lang: Python
        source: "import http.client\n\nconn = http.client.HTTPSConnection(\"www.nutanix.dev\")\n\nheaders = {\n    \"Authorization\"\
          : \"Basic <basic_auth_token>\"\n}\n \nconn.request(\"GET\",\"/api/fc/v1/api_keys/{key_uuid}\", headers=headers)\n\
          \nres = conn.getresponse()\ndata = res.read()\n\nprint(data.decode(\"utf-8\"))"
      - lang: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl\
          \ := \"https://www.nutanix.dev/api/fc/v1/api_keys/{key_uuid}\"\n\t \n\treq, err := http.NewRequest(\"GET\", url,\
          \ nil)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n        req.Header.Add(\"\
          Authorization\", \"Basic <basic_auth_token>\")\n    \n\tres, err := http.DefaultClient.Do(req)\n\tif err != nil\
          \ {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n\tdefer res.Body.Close()\n\tbody, err\
          \ := io.ReadAll(res.Body)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t\
          }\n\n\tfmt.Println(res)\n\tfmt.Println(string(body))\n\n}"
      - lang: Java
        source: "AsyncHttpClient client = new DefaultAsyncHttpClient();\nclient.prepare(\"GET\", \"https://www.nutanix.dev/api/fc/v1/api_keys/{key_uuid}\"\
          )\n  .setHeader(\"Authorization\", \"Basic <basic_auth_token>\")\n  .execute()\n  .toCompletableFuture()\n  .thenAccept(System.out::println)\n\
          \  .join();\n\nclient.close();"
      - lang: JavaScript
        source: "const url = 'https://www.nutanix.dev/api/fc/v1/api_keys/{key_uuid}';\nconst options = {\n  method: 'GET',\n\
          \  headers: {'Authorization': 'Basic <basic_auth_token>'} \n};\n\ntry {\n  const response = await fetch(url, options);\n\
          \  const data = await response.json();\n  console.log(data);\n} catch (error) {\n  console.error(error);\n}"
    delete:
      description: Delete the API key based on its UUID.
      tags:
      - api_keys
      summary: Delete an API key
      operationId: DeleteApiKey
      parameters:
      - description: UUID of the API key that must be deleted.
        name: key_uuid
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Deleted the API key from Foundation Central.
      x-codeSamples:
      - lang: cURL
        source: "curl --request DELETE \\\n    --url https://www.nutanix.dev/api/fc/v1/api_keys/{key_uuid} \\\n    --header\
          \ 'Authorization: Basic <basic_auth_token>' \\\n     "
      - lang: Wget
        source: "wget --quiet \\\n    --method DELETE \\\n    --header 'Authorization: Basic <basic_auth_token>' \\\n    \
          \  \\\n    --output-document \\\n    - https://www.nutanix.dev/api/fc/v1/api_keys/{key_uuid}"
      - lang: Python
        source: "import http.client\n\nconn = http.client.HTTPSConnection(\"www.nutanix.dev\")\n\nheaders = {\n    \"Authorization\"\
          : \"Basic <basic_auth_token>\"\n}\n \nconn.request(\"DELETE\",\"/api/fc/v1/api_keys/{key_uuid}\", headers=headers)\n\
          \nres = conn.getresponse()\ndata = res.read()\n\nprint(data.decode(\"utf-8\"))"
      - lang: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl\
          \ := \"https://www.nutanix.dev/api/fc/v1/api_keys/{key_uuid}\"\n\t \n\treq, err := http.NewRequest(\"DELETE\", url,\
          \ nil)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n        req.Header.Add(\"\
          Authorization\", \"Basic <basic_auth_token>\")\n    \n\tres, err := http.DefaultClient.Do(req)\n\tif err != nil\
          \ {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n\tdefer res.Body.Close()\n\tbody, err\
          \ := io.ReadAll(res.Body)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t\
          }\n\n\tfmt.Println(res)\n\tfmt.Println(string(body))\n\n}"
      - lang: Java
        source: "AsyncHttpClient client = new DefaultAsyncHttpClient();\nclient.prepare(\"DELETE\", \"https://www.nutanix.dev/api/fc/v1/api_keys/{key_uuid}\"\
          )\n  .setHeader(\"Authorization\", \"Basic <basic_auth_token>\")\n  .execute()\n  .toCompletableFuture()\n  .thenAccept(System.out::println)\n\
          \  .join();\n\nclient.close();"
      - lang: JavaScript
        source: "const url = 'https://www.nutanix.dev/api/fc/v1/api_keys/{key_uuid}';\nconst options = {\n  method: 'DELETE',\n\
          \  headers: {'Authorization': 'Basic <basic_auth_token>'} \n};\n\ntry {\n  const response = await fetch(url, options);\n\
          \  const data = await response.json();\n  console.log(data);\n} catch (error) {\n  console.error(error);\n}"
components:
  securitySchemes:
    APIKeyAuth:
      type: apiKey
      name: X-API-Key
      in: header
    APIKeyKubAuth:
      type: apiKey
      name: X-API-Key-Kub
      in: header
    BasicAuth:
      type: http
      scheme: basic
    CookieAuth:
      type: apiKey
      name: Cookie
      in: header
    OpenIDAuth:
      type: apiKey
      name: code
      in: query
  schemas:
    api_keys_input:
      description: Input parameters for creating a new API key.
      type: object
      required:
      - alias
      properties:
        alias:
          description: Alias for the API key to be created.
          type: string
    error_response:
      type: object
      properties:
        code:
          description: HTTP response code from the API.
          type: integer
          format: int32
        message_list:
          description: Error message in detail.
          type: array
          items:
            type: string
    api_key_details:
      description: Details of an API key.
      type: object
      properties:
        alias:
          description: Alias of the API key.
          type: string
        api_key:
          description: API key in string format.
          type: string
        created_timestamp:
          description: Time when the API key was created.
          type: string
          format: date-time
        current_time:
          description: Current time of the VM where service foundation central is running.
          type: string
          format: date-time
        key_uuid:
          description: UUID of the API key.
          type: string
          format: uuid
