openapi: 3.0.0
info:
  title: Foundation Central Service
  description: '# Introduction


    **Foundation Central** creates clusters from factory-imaged nodes and reimages existing nodes that are already registered
    with Foundation Central, remotely from Prism Central. This provides benefits such as creating clusters on remote sites
    (for example, ROBO), without arranging for a deployment personnel visit.


    **[Contact Us by Email](mailto:foundation@nutanix.com)**


    **License: Copyright Nutanix Inc. All rights reserved**

    '
  contact:
    name: Foundation Central Developers
    email: foundation@nutanix.com
  license:
    name: Copyright Nutanix Inc. All rights reserved
  version: '1.0'
servers:
- url: /api/fc/v1
security:
- BasicAuth: []
- CookieAuth: []
paths:
  /hardware_managers/{hardware_manager_uuid}/auth_data/list:
    post:
      description: Lists all the authentication data for a hardware manager created in Foundation Central.
      tags:
      - hardware_manager_auth_data
      summary: List all the authentication data for a hardware manager
      operationId: ListHwMgrAuthData
      parameters:
      - description: UUID of the hardware manager.
        name: hardware_manager_uuid
        in: path
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        $ref: '#/components/requestBodies/list_metadata_input'
      responses:
        '200':
          description: Details of all the authentication data for a hardware manager.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/hardware_manager_auth_list_response'
      x-codeSamples:
      - lang: cURL
        source: "curl --request POST \\\n    --url https://www.nutanix.dev/api/fc/v1/hardware_managers/{hardware_manager_uuid}/auth_data/list\
          \ \\\n    --header 'Authorization: Basic <basic_auth_token>' \\\n    --data '{\n    \"length\": 0,\n    \"offset\"\
          : 0\n}'"
      - lang: Wget
        source: "wget --quiet \\\n    --method POST \\\n    --header 'Authorization: Basic <basic_auth_token>' \\\n    --body-data\
          \ '{\n    \"length\": 0,\n    \"offset\": 0\n}' \\\n    --output-document \\\n    - https://www.nutanix.dev/api/fc/v1/hardware_managers/{hardware_manager_uuid}/auth_data/list"
      - lang: Python
        source: "import http.client\n\nconn = http.client.HTTPSConnection(\"www.nutanix.dev\")\n\nheaders = {\n    \"Authorization\"\
          : \"Basic <basic_auth_token>\"\n}\n\npayload =  \"\"\"{\n    \"length\": 0,\n    \"offset\": 0\n}\"\"\"\n\nconn.request(\"\
          POST\",\"/api/fc/v1/hardware_managers/{hardware_manager_uuid}/auth_data/list\", payload, headers)\n\nres = conn.getresponse()\n\
          data = res.read()\n\nprint(data.decode(\"utf-8\"))"
      - lang: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl\
          \ := \"https://www.nutanix.dev/api/fc/v1/hardware_managers/{hardware_manager_uuid}/auth_data/list\"\n\t\n\tpayload\
          \ :=  strings.NewReader(`{\"length\": 0, \"offset\": 0}`)\n\treq, err := http.NewRequest(\"POST\", url, payload)\n\
          \tif err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n        req.Header.Add(\"\
          Authorization\", \"Basic <basic_auth_token>\")\n    \n\tres, err := http.DefaultClient.Do(req)\n\tif err != nil\
          \ {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n\tdefer res.Body.Close()\n\tbody, err\
          \ := io.ReadAll(res.Body)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t\
          }\n\n\tfmt.Println(res)\n\tfmt.Println(string(body))\n\n}"
      - lang: Java
        source: "AsyncHttpClient client = new DefaultAsyncHttpClient();\nclient.prepare(\"POST\", \"https://www.nutanix.dev/api/fc/v1/hardware_managers/{hardware_manager_uuid}/auth_data/list\"\
          )\n  .setHeader(\"Authorization\", \"Basic <basic_auth_token>\")\n  .setBody(\"{\\\"length\\\": 0, \\\"offset\\\"\
          : 0}\")\n  .execute()\n  .toCompletableFuture()\n  .thenAccept(System.out::println)\n  .join();\n\nclient.close();"
      - lang: JavaScript
        source: "const url = 'https://www.nutanix.dev/api/fc/v1/hardware_managers/{hardware_manager_uuid}/auth_data/list';\n\
          const options = {\n  method: 'POST',\n  headers: {'Authorization': 'Basic <basic_auth_token>'},\n  body:  `{\"length\"\
          : 0, \"offset\": 0}`\n};\n\ntry {\n  const response = await fetch(url, options);\n  const data = await response.json();\n\
          \  console.log(data);\n} catch (error) {\n  console.error(error);\n}"
components:
  requestBodies:
    list_metadata_input:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/list_metadata_input'
      required: true
  securitySchemes:
    APIKeyAuth:
      type: apiKey
      name: X-API-Key
      in: header
    APIKeyKubAuth:
      type: apiKey
      name: X-API-Key-Kub
      in: header
    BasicAuth:
      type: http
      scheme: basic
    CookieAuth:
      type: apiKey
      name: Cookie
      in: header
    OpenIDAuth:
      type: apiKey
      name: code
      in: query
  schemas:
    hardware_manager_auth_details:
      description: Details of a hardware manager authentication data.
      type: object
      required:
      - auth_data_uuid
      - created_timestamp
      - current_time
      properties:
        api_key:
          $ref: '#/components/schemas/api_key_auth_details'
        auth_data_uuid:
          description: UUID of the authentication data.
          type: string
          format: uuid
        created_timestamp:
          description: Time when the authentication data was added in Foundation Central.
          type: string
          format: date-time
        current_time:
          description: Current time of Foundation Central.
          type: string
          format: date-time
    hardware_manager_auth_list_response:
      description: Response with authentication data details for a hardware manager.
      type: object
      properties:
        auth_data:
          type: array
          items:
            $ref: '#/components/schemas/hardware_manager_auth_details'
        metadata:
          $ref: '#/components/schemas/list_metadata_output'
    error_response:
      type: object
      properties:
        code:
          description: HTTP response code from the API.
          type: integer
          format: int32
        message_list:
          description: Error message in detail.
          type: array
          items:
            type: string
    list_metadata_output:
      description: List metadata output for all the list APIs.
      type: object
      required:
      - length
      properties:
        length:
          description: The number of records retrieved.
          type: integer
        offset:
          description: Offset from the start of the object list.
          type: integer
        total_matches:
          description: Total matches found.
          type: integer
    list_metadata_input:
      description: List metadata input for all the list APIs.
      type: object
      properties:
        length:
          description: The number of records to retrieve.
          type: integer
        offset:
          description: Offset from the start of the object list. If omitted, the default value is 0.
          type: integer
          minimum: 0
    api_key_auth_details:
      description: Details of API key which was added for a hardware manager.
      type: object
      required:
      - key_id
      properties:
        key_id:
          description: API key ID of the API key.
          type: string
