openapi: 3.0.0
info:
  title: Foundation Central Service
  description: '# Introduction


    **Foundation Central** creates clusters from factory-imaged nodes and reimages existing nodes that are already registered
    with Foundation Central, remotely from Prism Central. This provides benefits such as creating clusters on remote sites
    (for example, ROBO), without arranging for a deployment personnel visit.


    **[Contact Us by Email](mailto:foundation@nutanix.com)**


    **License: Copyright Nutanix Inc. All rights reserved**

    '
  contact:
    name: Foundation Central Developers
    email: foundation@nutanix.com
  license:
    name: Copyright Nutanix Inc. All rights reserved
  version: '1.0'
servers:
- url: /api/fc/v1
security:
- BasicAuth: []
- CookieAuth: []
paths:
  /details:
    get:
      security:
      - BasicAuth: []
      - APIKeyAuth: []
      - CookieAuth: []
      - APIKeyKubAuth: []
      description: Get the details of Foundation Central like version, commit ID and more.
      tags:
      - details
      summary: Get details of Foundation Central
      operationId: GetDetails
      responses:
        '200':
          description: Details of Foundation Central.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/details_response'
      x-codeSamples:
      - lang: cURL
        source: "curl --request GET \\\n    --url https://www.nutanix.dev/api/fc/v1/details \\\n    --header 'Authorization:\
          \ Basic <basic_auth_token>' \\\n     "
      - lang: Wget
        source: "wget --quiet \\\n    --method GET \\\n    --header 'Authorization: Basic <basic_auth_token>' \\\n      \\\
          \n    --output-document \\\n    - https://www.nutanix.dev/api/fc/v1/details"
      - lang: Python
        source: "import http.client\n\nconn = http.client.HTTPSConnection(\"www.nutanix.dev\")\n\nheaders = {\n    \"Authorization\"\
          : \"Basic <basic_auth_token>\"\n}\n \nconn.request(\"GET\",\"/api/fc/v1/details\", headers=headers)\n\nres = conn.getresponse()\n\
          data = res.read()\n\nprint(data.decode(\"utf-8\"))"
      - lang: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl\
          \ := \"https://www.nutanix.dev/api/fc/v1/details\"\n\t \n\treq, err := http.NewRequest(\"GET\", url, nil)\n\tif\
          \ err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n        req.Header.Add(\"\
          Authorization\", \"Basic <basic_auth_token>\")\n    \n\tres, err := http.DefaultClient.Do(req)\n\tif err != nil\
          \ {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n\tdefer res.Body.Close()\n\tbody, err\
          \ := io.ReadAll(res.Body)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t\
          }\n\n\tfmt.Println(res)\n\tfmt.Println(string(body))\n\n}"
      - lang: Java
        source: "AsyncHttpClient client = new DefaultAsyncHttpClient();\nclient.prepare(\"GET\", \"https://www.nutanix.dev/api/fc/v1/details\"\
          )\n  .setHeader(\"Authorization\", \"Basic <basic_auth_token>\")\n  .execute()\n  .toCompletableFuture()\n  .thenAccept(System.out::println)\n\
          \  .join();\n\nclient.close();"
      - lang: JavaScript
        source: "const url = 'https://www.nutanix.dev/api/fc/v1/details';\nconst options = {\n  method: 'GET',\n  headers:\
          \ {'Authorization': 'Basic <basic_auth_token>'} \n};\n\ntry {\n  const response = await fetch(url, options);\n \
          \ const data = await response.json();\n  console.log(data);\n} catch (error) {\n  console.error(error);\n}"
components:
  securitySchemes:
    APIKeyAuth:
      type: apiKey
      name: X-API-Key
      in: header
    APIKeyKubAuth:
      type: apiKey
      name: X-API-Key-Kub
      in: header
    BasicAuth:
      type: http
      scheme: basic
    CookieAuth:
      type: apiKey
      name: Cookie
      in: header
    OpenIDAuth:
      type: apiKey
      name: code
      in: query
  schemas:
    details_response:
      description: Response parameters with Foundation Central details.
      type: object
      properties:
        commit_id:
          description: Commit ID of Foundation Central service.
          type: string
        version:
          description: Version of Foundation Central service.
          type: string
    error_response:
      type: object
      properties:
        code:
          description: HTTP response code from the API.
          type: integer
          format: int32
        message_list:
          description: Error message in detail.
          type: array
          items:
            type: string
