openapi: 3.0.0
info:
  title: Foundation Central Service
  description: '# Introduction


    **Foundation Central** creates clusters from factory-imaged nodes and reimages existing nodes that are already registered
    with Foundation Central, remotely from Prism Central. This provides benefits such as creating clusters on remote sites
    (for example, ROBO), without arranging for a deployment personnel visit.


    **[Contact Us by Email](mailto:foundation@nutanix.com)**


    **License: Copyright Nutanix Inc. All rights reserved**

    '
  contact:
    name: Foundation Central Developers
    email: foundation@nutanix.com
  license:
    name: Copyright Nutanix Inc. All rights reserved
  version: '1.0'
servers:
- url: /api/fc/v1
security:
- BasicAuth: []
- CookieAuth: []
paths:
  /api_keys/list:
    post:
      description: List all the API keys available in Foundation Central.
      tags:
      - api_keys
      summary: List all the API keys
      operationId: ListApiKeys
      requestBody:
        $ref: '#/components/requestBodies/list_metadata_input'
      responses:
        '200':
          description: Details of all the API keys.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/api_keys_list_response'
      x-codeSamples:
      - lang: cURL
        source: "curl --request POST \\\n    --url https://www.nutanix.dev/api/fc/v1/api_keys/list \\\n    --header 'Authorization:\
          \ Basic <basic_auth_token>' \\\n    --data '{\n    \"length\": 0,\n    \"offset\": 0\n}'"
      - lang: Wget
        source: "wget --quiet \\\n    --method POST \\\n    --header 'Authorization: Basic <basic_auth_token>' \\\n    --body-data\
          \ '{\n    \"length\": 0,\n    \"offset\": 0\n}' \\\n    --output-document \\\n    - https://www.nutanix.dev/api/fc/v1/api_keys/list"
      - lang: Python
        source: "import http.client\n\nconn = http.client.HTTPSConnection(\"www.nutanix.dev\")\n\nheaders = {\n    \"Authorization\"\
          : \"Basic <basic_auth_token>\"\n}\n\npayload =  \"\"\"{\n    \"length\": 0,\n    \"offset\": 0\n}\"\"\"\n\nconn.request(\"\
          POST\",\"/api/fc/v1/api_keys/list\", payload, headers)\n\nres = conn.getresponse()\ndata = res.read()\n\nprint(data.decode(\"\
          utf-8\"))"
      - lang: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl\
          \ := \"https://www.nutanix.dev/api/fc/v1/api_keys/list\"\n\t\n\tpayload :=  strings.NewReader(`{\"length\": 0, \"\
          offset\": 0}`)\n\treq, err := http.NewRequest(\"POST\", url, payload)\n\tif err != nil {\n\t\tfmt.Println(\"Error\
          \ creating request:\", err)\n\t\treturn\n\t}\n\n        req.Header.Add(\"Authorization\", \"Basic <basic_auth_token>\"\
          )\n    \n\tres, err := http.DefaultClient.Do(req)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating request:\"\
          , err)\n\t\treturn\n\t}\n\n\tdefer res.Body.Close()\n\tbody, err := io.ReadAll(res.Body)\n\tif err != nil {\n\t\t\
          fmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n\tfmt.Println(res)\n\tfmt.Println(string(body))\n\
          \n}"
      - lang: Java
        source: "AsyncHttpClient client = new DefaultAsyncHttpClient();\nclient.prepare(\"POST\", \"https://www.nutanix.dev/api/fc/v1/api_keys/list\"\
          )\n  .setHeader(\"Authorization\", \"Basic <basic_auth_token>\")\n  .setBody(\"{\\\"length\\\": 0, \\\"offset\\\"\
          : 0}\")\n  .execute()\n  .toCompletableFuture()\n  .thenAccept(System.out::println)\n  .join();\n\nclient.close();"
      - lang: JavaScript
        source: "const url = 'https://www.nutanix.dev/api/fc/v1/api_keys/list';\nconst options = {\n  method: 'POST',\n  headers:\
          \ {'Authorization': 'Basic <basic_auth_token>'},\n  body:  `{\"length\": 0, \"offset\": 0}`\n};\n\ntry {\n  const\
          \ response = await fetch(url, options);\n  const data = await response.json();\n  console.log(data);\n} catch (error)\
          \ {\n  console.error(error);\n}"
components:
  requestBodies:
    list_metadata_input:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/list_metadata_input'
      required: true
  securitySchemes:
    APIKeyAuth:
      type: apiKey
      name: X-API-Key
      in: header
    APIKeyKubAuth:
      type: apiKey
      name: X-API-Key-Kub
      in: header
    BasicAuth:
      type: http
      scheme: basic
    CookieAuth:
      type: apiKey
      name: Cookie
      in: header
    OpenIDAuth:
      type: apiKey
      name: code
      in: query
  schemas:
    error_response:
      type: object
      properties:
        code:
          description: HTTP response code from the API.
          type: integer
          format: int32
        message_list:
          description: Error message in detail.
          type: array
          items:
            type: string
    list_metadata_output:
      description: List metadata output for all the list APIs.
      type: object
      required:
      - length
      properties:
        length:
          description: The number of records retrieved.
          type: integer
        offset:
          description: Offset from the start of the object list.
          type: integer
        total_matches:
          description: Total matches found.
          type: integer
    list_metadata_input:
      description: List metadata input for all the list APIs.
      type: object
      properties:
        length:
          description: The number of records to retrieve.
          type: integer
        offset:
          description: Offset from the start of the object list. If omitted, the default value is 0.
          type: integer
          minimum: 0
    api_key_details:
      description: Details of an API key.
      type: object
      properties:
        alias:
          description: Alias of the API key.
          type: string
        api_key:
          description: API key in string format.
          type: string
        created_timestamp:
          description: Time when the API key was created.
          type: string
          format: date-time
        current_time:
          description: Current time of the VM where service foundation central is running.
          type: string
          format: date-time
        key_uuid:
          description: UUID of the API key.
          type: string
          format: uuid
    api_keys_list_response:
      description: Response with API key details.
      type: object
      properties:
        api_keys:
          type: array
          items:
            $ref: '#/components/schemas/api_key_details'
        metadata:
          $ref: '#/components/schemas/list_metadata_output'
