openapi: 3.0.0
info:
  title: Foundation Central Service
  description: '# Introduction


    **Foundation Central** creates clusters from factory-imaged nodes and reimages existing nodes that are already registered
    with Foundation Central, remotely from Prism Central. This provides benefits such as creating clusters on remote sites
    (for example, ROBO), without arranging for a deployment personnel visit.


    **[Contact Us by Email](mailto:foundation@nutanix.com)**


    **License: Copyright Nutanix Inc. All rights reserved**

    '
  contact:
    name: Foundation Central Developers
    email: foundation@nutanix.com
  license:
    name: Copyright Nutanix Inc. All rights reserved
  version: '1.0'
servers:
- url: /api/fc/v1
security:
- BasicAuth: []
- CookieAuth: []
paths:
  /imaged_nodes/onboard:
    post:
      security:
      - BasicAuth: []
      - CookieAuth: []
      description: Onboards a node by pre-authorizing the node serial in Foundation Central.
      tags:
      - imaged_nodes
      summary: Onboard a node in Foundation Central.
      operationId: OnboardImagedNodes
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/imaged_nodes_onboard_input'
        required: true
      responses:
        '200':
          description: Onboarded a new node.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/imaged_nodes_response'
      x-codeSamples:
      - lang: cURL
        source: "curl --request POST \\\n    --url https://www.nutanix.dev/api/fc/v1/imaged_nodes/onboard \\\n    --header\
          \ 'Authorization: Basic <basic_auth_token>' \\\n    --data '{\n    \"block_serial\": \"string\",\n    \"cpu_core_count\"\
          : 0,\n    \"hardware_manager_data\": {\n        \"intersight_data\": {\n            \"classification\": \"NUTANIX\"\
          ,\n            \"domain\": \"string\",\n            \"management_mode\": \"ISM\",\n            \"node_name\": \"\
          string\",\n            \"organizations\": [\n                \"string\"\n            ],\n            \"tags\": [\n\
          \                {\n                    \"key\": \"string\",\n                    \"value\": \"string\"\n      \
          \          }\n            ]\n        }\n    },\n    \"hardware_manager_uuid\": \"b4d15375-1097-4c96-a4c4-4cb5809b05bb\"\
          ,\n    \"memory_gb\": null,\n    \"model\": \"string\",\n    \"node_serial\": \"string\"\n}'"
      - lang: Wget
        source: "wget --quiet \\\n    --method POST \\\n    --header 'Authorization: Basic <basic_auth_token>' \\\n    --body-data\
          \ '{\n    \"block_serial\": \"string\",\n    \"cpu_core_count\": 0,\n    \"hardware_manager_data\": {\n        \"\
          intersight_data\": {\n            \"classification\": \"NUTANIX\",\n            \"domain\": \"string\",\n      \
          \      \"management_mode\": \"ISM\",\n            \"node_name\": \"string\",\n            \"organizations\": [\n\
          \                \"string\"\n            ],\n            \"tags\": [\n                {\n                    \"\
          key\": \"string\",\n                    \"value\": \"string\"\n                }\n            ]\n        }\n   \
          \ },\n    \"hardware_manager_uuid\": \"b4d15375-1097-4c96-a4c4-4cb5809b05bb\",\n    \"memory_gb\": null,\n    \"\
          model\": \"string\",\n    \"node_serial\": \"string\"\n}' \\\n    --output-document \\\n    - https://www.nutanix.dev/api/fc/v1/imaged_nodes/onboard"
      - lang: Python
        source: "import http.client\n\nconn = http.client.HTTPSConnection(\"www.nutanix.dev\")\n\nheaders = {\n    \"Authorization\"\
          : \"Basic <basic_auth_token>\"\n}\n\npayload =  \"\"\"{\n    \"block_serial\": \"string\",\n    \"cpu_core_count\"\
          : 0,\n    \"hardware_manager_data\": {\n        \"intersight_data\": {\n            \"classification\": \"NUTANIX\"\
          ,\n            \"domain\": \"string\",\n            \"management_mode\": \"ISM\",\n            \"node_name\": \"\
          string\",\n            \"organizations\": [\n                \"string\"\n            ],\n            \"tags\": [\n\
          \                {\n                    \"key\": \"string\",\n                    \"value\": \"string\"\n      \
          \          }\n            ]\n        }\n    },\n    \"hardware_manager_uuid\": \"b4d15375-1097-4c96-a4c4-4cb5809b05bb\"\
          ,\n    \"memory_gb\": null,\n    \"model\": \"string\",\n    \"node_serial\": \"string\"\n}\"\"\"\n\nconn.request(\"\
          POST\",\"/api/fc/v1/imaged_nodes/onboard\", payload, headers)\n\nres = conn.getresponse()\ndata = res.read()\n\n\
          print(data.decode(\"utf-8\"))"
      - lang: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl\
          \ := \"https://www.nutanix.dev/api/fc/v1/imaged_nodes/onboard\"\n\t\n\tpayload :=  strings.NewReader(`{\"block_serial\"\
          : \"string\", \"cpu_core_count\": 0, \"hardware_manager_data\": {\"intersight_data\": {\"classification\": \"NUTANIX\"\
          , \"domain\": \"string\", \"management_mode\": \"ISM\", \"node_name\": \"string\", \"organizations\": [\"string\"\
          ], \"tags\": [{\"key\": \"string\", \"value\": \"string\"}]}}, \"hardware_manager_uuid\": \"b4d15375-1097-4c96-a4c4-4cb5809b05bb\"\
          , \"memory_gb\": null, \"model\": \"string\", \"node_serial\": \"string\"}`)\n\treq, err := http.NewRequest(\"POST\"\
          , url, payload)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n     \
          \   req.Header.Add(\"Authorization\", \"Basic <basic_auth_token>\")\n    \n\tres, err := http.DefaultClient.Do(req)\n\
          \tif err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\treturn\n\t}\n\n\tdefer res.Body.Close()\n\
          \tbody, err := io.ReadAll(res.Body)\n\tif err != nil {\n\t\tfmt.Println(\"Error creating request:\", err)\n\t\t\
          return\n\t}\n\n\tfmt.Println(res)\n\tfmt.Println(string(body))\n\n}"
      - lang: Java
        source: "AsyncHttpClient client = new DefaultAsyncHttpClient();\nclient.prepare(\"POST\", \"https://www.nutanix.dev/api/fc/v1/imaged_nodes/onboard\"\
          )\n  .setHeader(\"Authorization\", \"Basic <basic_auth_token>\")\n  .setBody(\"{\\\"block_serial\\\": \\\"string\\\
          \", \\\"cpu_core_count\\\": 0, \\\"hardware_manager_data\\\": {\\\"intersight_data\\\": {\\\"classification\\\"\
          : \\\"NUTANIX\\\", \\\"domain\\\": \\\"string\\\", \\\"management_mode\\\": \\\"ISM\\\", \\\"node_name\\\": \\\"\
          string\\\", \\\"organizations\\\": [\\\"string\\\"], \\\"tags\\\": [{\\\"key\\\": \\\"string\\\", \\\"value\\\"\
          : \\\"string\\\"}]}}, \\\"hardware_manager_uuid\\\": \\\"b4d15375-1097-4c96-a4c4-4cb5809b05bb\\\", \\\"memory_gb\\\
          \": null, \\\"model\\\": \\\"string\\\", \\\"node_serial\\\": \\\"string\\\"}\")\n  .execute()\n  .toCompletableFuture()\n\
          \  .thenAccept(System.out::println)\n  .join();\n\nclient.close();"
      - lang: JavaScript
        source: "const url = 'https://www.nutanix.dev/api/fc/v1/imaged_nodes/onboard';\nconst options = {\n  method: 'POST',\n\
          \  headers: {'Authorization': 'Basic <basic_auth_token>'},\n  body:  `{\"block_serial\": \"string\", \"cpu_core_count\"\
          : 0, \"hardware_manager_data\": {\"intersight_data\": {\"classification\": \"NUTANIX\", \"domain\": \"string\",\
          \ \"management_mode\": \"ISM\", \"node_name\": \"string\", \"organizations\": [\"string\"], \"tags\": [{\"key\"\
          : \"string\", \"value\": \"string\"}]}}, \"hardware_manager_uuid\": \"b4d15375-1097-4c96-a4c4-4cb5809b05bb\", \"\
          memory_gb\": null, \"model\": \"string\", \"node_serial\": \"string\"}`\n};\n\ntry {\n  const response = await fetch(url,\
          \ options);\n  const data = await response.json();\n  console.log(data);\n} catch (error) {\n  console.error(error);\n\
          }"
components:
  securitySchemes:
    APIKeyAuth:
      type: apiKey
      name: X-API-Key
      in: header
    APIKeyKubAuth:
      type: apiKey
      name: X-API-Key-Kub
      in: header
    BasicAuth:
      type: http
      scheme: basic
    CookieAuth:
      type: apiKey
      name: Cookie
      in: header
    OpenIDAuth:
      type: apiKey
      name: code
      in: query
  schemas:
    imaged_nodes_response:
      description: Response returned by the server after registering a node.
      type: object
      required:
      - object_version
      properties:
        imaged_node_uuid:
          description: UUID of the node.
          type: string
          format: uuid
        object_version:
          description: Version of the node used for CAS. This will be 0 for the newly created node.
          type: integer
          minimum: 0
    hardware_manager_node_onboard_input:
      description: Node data fetched from hardware manager using discovery API.
      type: object
      properties:
        intersight_data:
          $ref: '#/components/schemas/intersight_node_onboard_input'
    error_response:
      type: object
      properties:
        code:
          description: HTTP response code from the API.
          type: integer
          format: int32
        message_list:
          description: Error message in detail.
          type: array
          items:
            type: string
    intersight_node_onboard_input:
      description: UCS server data fetched using discovery API.
      type: object
      required:
      - organizations
      - classification
      - node_name
      properties:
        classification:
          description: Classification indicates whether UCS server is installed with Nutanix stack or not.
          type: string
          enum:
          - NUTANIX
          - UNKNOWN
        domain:
          description: Name of the UCS Domain to which the node belongs. For standalone servers, this field is empty.
          type: string
        management_mode:
          $ref: '#/components/schemas/management_mode_intersight'
        node_name:
          description: Name of the node in the Intersight.
          type: string
        organizations:
          $ref: '#/components/schemas/intersight_orgs'
        tags:
          $ref: '#/components/schemas/intersight_tags'
    intersight_orgs:
      description: List of organizations to which the UCS server belongs.
      type: array
      items:
        description: Name of the organization in Intersight.
        type: string
    imaged_nodes_onboard_input:
      description: Input parameters for onboarding a node.
      type: object
      required:
      - node_serial
      properties:
        block_serial:
          description: Serial number of the block to which the node belongs.
          type: string
        cpu_core_count:
          description: Number of CPU cores in the node.
          type: integer
        hardware_manager_data:
          $ref: '#/components/schemas/hardware_manager_node_onboard_input'
        hardware_manager_uuid:
          description: UUID of the hardware manager which manages the node. This is required for the nodes managed by a hardware
            manager.
          type: string
          format: uuid
        memory_gb:
          description: Memory of the node in GB.
          type: number
          format: float
        model:
          description: Model of the node.
          type: string
        node_serial:
          description: Serial number of the node.
          type: string
          pattern: ^[A-Z0-9a-z]+$
    management_mode_intersight:
      description: Management mode of the node in Intersight.
      type: string
      enum:
      - ISM
      - IMM
    intersight_tags:
      description: List of tags of the UCS server.
      type: array
      items:
        description: UCS server tags.
        type: object
        properties:
          key:
            description: Key of the tag.
            type: string
          value:
            description: Value of the tag.
            type: string
