# GENERATED 1:1 from objects-v4.0.yaml — resource 'CertificateAuthority'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-objects-certificateauthority
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-objects-certificateauthority-oas/certificateauthority.yaml
  resourceGroup: objects.nutanix.krateo.io
  resource:
    kind: CertificateAuthority
    identifiers:
    - extId
    additionalStatusFields:
    - extId
    verbsDescription:
    - action: findby
      method: GET
      path: /objects/v4.0/config/object-stores/{objectStoreExtId}/certificates/{certificateExtId}/certificate-authority
      requestFieldMapping:
      - inPath: objectStoreExtId
        inCustomResource: spec.objectStoreExtId
      - inPath: certificateExtId
        inCustomResource: spec.certificateExtId
