# GENERATED 1:1 from objects-v4.0.yaml — resource 'ObjectStore'
# ASYNC (202+task): needs task-poll/ETag handling at runtime
apiVersion: ogen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: nutanix-objects-objectstore
  namespace: nutanix-system
spec:
  oasPath: configmap://nutanix-system/nutanix-objects-objectstore-oas/objectstore.yaml
  resourceGroup: objects.nutanix.krateo.io
  resource:
    kind: ObjectStore
    identifiers:
    - name
    additionalStatusFields:
    - extId
    excludedSpecFields:
    - $expand
    - $filter
    - $limit
    - $orderby
    - $page
    - $select
    verbsDescription:
    - action: findby
      method: GET
      path: /objects/v4.0/config/object-stores
    - action: create
      method: POST
      path: /objects/v4.0/config/object-stores
    - action: get
      method: GET
      path: /objects/v4.0/config/object-stores/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: update
      method: PUT
      path: /objects/v4.0/config/object-stores/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
    - action: delete
      method: DELETE
      path: /objects/v4.0/config/object-stores/{extId}
      requestFieldMapping:
      - inPath: extId
        inCustomResource: status.extId
